import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { formatRequestError, request } from "../../api";
import { AdminAccessProfile, AdminApprovalRequest, MealReminderDecisionRecord, MealReminderMode, MealReminderPolicy, MealReminderSummary } from "../../types";
import { DataTable, LoadState, MetricCard, Panel, SectionToolbar } from "../../AdminPrimitives";
import { CommunicationBars, CommunicationHero } from "../../CommunicationsPrimitives";
import { useAdminLocale } from "../../admin/locale";
import { ApprovalSubmissionNotice } from "../../admin/shared";

type Draft = Pick<MealReminderPolicy, "mode" | "kcalEnabled" | "breakfastTime" | "lunchTime" | "dinnerTime" | "slotAgeMinutes" | "maxDaily" | "maxRolling" | "maxCatchups" | "minimumGapMinutes" | "routineGapMinutes" | "quietStart" | "quietEnd"> & { version: number | null; pilotUserIds: string };
type Scenario = { evaluatedAt: string; localDate: string; timeZone: string; language: "en" | "tr"; breakfast: string; lunch: string; dinner: string; targetCalories: string; consumedCalories: string; fastingActive: boolean; pushEnabled: boolean; mealRemindersEnabled: boolean };
const API = "/api/v1/admin/meal-reminder-automation";
const MEAL_STATES = ["MISSING", "RECORDED", "EXCLUDED", "UNKNOWN"];
const REASONS: Record<string, string> = {
  ELIGIBLE: "This scenario is eligible for a friendly reminder.", PREVIOUS_MEAL_MISSING: "An earlier meal is missing, so a meal-specific evening reminder is skipped; only the general daily check-in may be used.",
  MEAL_ALREADY_RECORDED: "The meal is already recorded.", PREFERENCE_DISABLED: "The user's push or meal reminder preference is off.", QUIET_HOURS: "The user's local quiet hours are active.",
  FASTING_ACTIVE: "An active fast suppresses this reminder.", DAILY_LIMIT: "The daily reminder limit has been reached.", ROLLING_LIMIT: "The rolling 24-hour limit has been reached.",
  COOLDOWN: "Another meal reminder was sent too recently.", ROUTINE_COOLDOWN: "A water, fasting, or step reminder was sent too recently.", NO_VALID_TOKEN: "No valid device token is available.",
  NOT_DUE: "No reminder slot is due at this user-local time.", STALE_SLOT: "The slot has expired; restart will not send old reminders.", OUTSIDE_COHORT: "The test account is outside the approved pilot cohort.",
  SYSTEM_DISABLED: "The automation or its deployment gate is off.", DATA_UNAVAILABLE: "Required diary or timezone data is unavailable, so the decision fails closed."
};

function localInput(date = new Date()) { const shifted = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return shifted.toISOString().slice(0, 16); }
function initialScenario(): Scenario { const now = new Date(); return { evaluatedAt: localInput(now), localDate: localInput(now).slice(0, 10), timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC", language: "en", breakfast: "MISSING", lunch: "MISSING", dinner: "MISSING", targetCalories: "2000", consumedCalories: "900", fastingActive: false, pushEnabled: true, mealRemindersEnabled: true }; }
function toDraft(policy: MealReminderPolicy): Draft { return { version: policy.status === "DRAFT" ? policy.version : null, mode: policy.mode, kcalEnabled: policy.kcalEnabled, breakfastTime: policy.breakfastTime, lunchTime: policy.lunchTime, dinnerTime: policy.dinnerTime, slotAgeMinutes: policy.slotAgeMinutes, maxDaily: policy.maxDaily, maxRolling: policy.maxRolling, maxCatchups: policy.maxCatchups, minimumGapMinutes: policy.minimumGapMinutes, routineGapMinutes: policy.routineGapMinutes, quietStart: policy.quietStart, quietEnd: policy.quietEnd, pilotUserIds: policy.pilotUserIds.join(", ") }; }
function dateLabel(value?: string) { return value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }
function percent(value?: number) { return `${((value ?? 0) * 100).toFixed(1)}%`; }

export function MealReminderAutomationView({ accessProfile, onError, onNavigate }: { accessProfile: AdminAccessProfile | null; onError: (message: string | null) => void; onNavigate: (section: "notificationDefinitions") => void }) {
  const { locale } = useAdminLocale(); const tx = (en: string, tr: string) => locale === "tr" ? tr : en;
  const canManage = Boolean(accessProfile?.permissions?.includes("GROWTH_MANAGE"));
  const [config, setConfig] = useState<MealReminderPolicy | null>(null); const [history, setHistory] = useState<MealReminderPolicy[]>([]); const [decisions, setDecisions] = useState<MealReminderDecisionRecord[]>([]); const [summary, setSummary] = useState<MealReminderSummary | null>(null);
  const [state, setState] = useState<LoadState>("idle"); const [actionState, setActionState] = useState<LoadState>("idle"); const [draft, setDraft] = useState<Draft | null>(null); const [draftId, setDraftId] = useState<number | null>(null); const [scenario, setScenario] = useState(initialScenario); const [preview, setPreview] = useState<MealReminderDecisionRecord | null>(null); const [notice, setNotice] = useState<string | null>(null); const [reason, setReason] = useState(""); const [decisionPage, setDecisionPage] = useState(0); const pageSize = 10;
  const [testUserId, setTestUserId] = useState("");
  const [approvalNotice, setApprovalNotice] = useState<{ request: AdminApprovalRequest; message: string } | null>(null);
  useEffect(() => { if (notice) setApprovalNotice(null); }, [notice]);

  const load = useCallback(async () => { setState("loading"); try { const [nextConfig, nextHistory, nextDecisions, nextSummary] = await Promise.all([request<MealReminderPolicy>(`${API}/config`), request<MealReminderPolicy[]>(`${API}/history?size=50`), request<MealReminderDecisionRecord[]>(`${API}/decisions?size=100`), request<MealReminderSummary>(`${API}/summary`)]); setConfig(nextConfig); setHistory(nextHistory); setDecisions(nextDecisions); setSummary(nextSummary); const existingDraft = nextHistory.find((item) => item.status === "DRAFT"); setDraftId(existingDraft?.id ?? null); setDraft(toDraft(existingDraft ?? nextConfig)); setState("ready"); onError(null); } catch (error) { const message = formatRequestError(error); setState("error"); onError(message); } }, [onError]);
  useEffect(() => { void load(); }, [load]);
  const dirty = useMemo(() => Boolean(config && draft && JSON.stringify({ ...draft, version: null }) !== JSON.stringify({ ...toDraft(config), version: null })), [config, draft]);
  const pagedDecisions = decisions.slice(decisionPage * pageSize, (decisionPage + 1) * pageSize);
  const userTime = useMemo(() => { try { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "long", timeZone: scenario.timeZone }).format(new Date(scenario.evaluatedAt)); } catch { return "Invalid timezone"; } }, [scenario.evaluatedAt, scenario.timeZone]);

  async function saveDraft(event: FormEvent) { event.preventDefault(); if (!draft || !canManage) return; setActionState("loading"); setNotice(null); try { const payload = { ...draft, pilotUserIds: draft.pilotUserIds.split(",").map((value) => Number(value.trim())).filter((value) => Number.isInteger(value) && value > 0) }; const saved = await request<MealReminderPolicy>(draftId ? `${API}/drafts/${draftId}` : `${API}/drafts`, { method: draftId ? "PUT" : "POST", body: payload }); setDraftId(saved.id); setDraft(toDraft(saved)); setNotice("Draft saved. Nothing is live until a different authorized admin approves publication."); setActionState("ready"); await load(); } catch (error) { const message = formatRequestError(error); setActionState("error"); setNotice(message.includes("version") || message.includes("conflict") ? "This draft changed in another admin session. Refresh before editing again." : message); } }
  async function requestAction(path: string, success: string, requiresApproval = true) { if (!canManage || !reason.trim()) return; setActionState("loading"); try { if (requiresApproval) { const approval = await request<AdminApprovalRequest>(path, { method: "POST", body: { reason: reason.trim() } }); setNotice(null); setApprovalNotice({ request: approval, message: success }); } else { await request(path, { method: "POST", body: { reason: reason.trim() } }); setApprovalNotice(null); setNotice(success); } setReason(""); setActionState("ready"); await load(); } catch (error) { const message = formatRequestError(error); setApprovalNotice(null); setNotice(message); setActionState("error"); } }
  async function runPreview(event: FormEvent) { event.preventDefault(); setActionState("loading"); try { const result = await request<MealReminderDecisionRecord>(`${API}/preview`, { method: "POST", body: { evaluatedAt: new Date(scenario.evaluatedAt).toISOString(), localDate: scenario.localDate, timeZone: scenario.timeZone, language: scenario.language, mealStates: { BREAKFAST: scenario.breakfast, LUNCH: scenario.lunch, DINNER: scenario.dinner, SNACK: "UNKNOWN" }, targetCalories: scenario.targetCalories ? Number(scenario.targetCalories) : null, consumedCalories: scenario.consumedCalories ? Number(scenario.consumedCalories) : null, fastingActive: scenario.fastingActive, pushEnabled: scenario.pushEnabled, mealRemindersEnabled: scenario.mealRemindersEnabled } }); setPreview(result); setActionState("ready"); } catch (error) { setNotice(formatRequestError(error)); setActionState("error"); } }

  return <div className="stack communications-ops-view meal-reminder-automation-view meal-reminder-page">
    <SectionToolbar title={tx("Meal reminder automation", "Öğün hatırlatma otomasyonu")} description={tx("Explain, simulate, draft, and safely release friendly meal reminders without overriding user consent or the deployment gate.", "Kullanıcı onayını veya yayın kapısını aşmadan öğün hatırlatmalarını açıklayın, simüle edin, taslaklayın ve güvenle yayınlayın.")} state={state} onReload={() => void load()}>
      <button className="ghost-button" type="button" onClick={() => onNavigate("notificationDefinitions")}>{tx("Open managed copy", "Yönetilen metni aç")}</button>
    </SectionToolbar>
    <CommunicationHero eyebrow={tx("Consent-aware automation", "Onaya duyarlı otomasyon")} title={tx("Prepare meal reminders without bypassing user choice or release gates.", "Kullanıcı tercihini veya yayın kapılarını aşmadan öğün hatırlatmaları hazırlayın.")} description={tx("Scheduling, dry-run evidence and controlled publication are presented as one auditable workflow.", "Zamanlama, deneme kanıtları ve kontrollü yayın tek denetlenebilir akışta sunulur.")} status={<span className={`communication-status-pill ${summary?.deploymentGateEnabled && summary?.pushGateEnabled ? "good" : "blocked"}`}>{summary?.mode ?? "OFF"} · {summary?.deploymentGateEnabled ? tx("GATE OPEN", "KAPI AÇIK") : tx("GATE CLOSED", "KAPI KAPALI")}</span>} />
    {approvalNotice && <ApprovalSubmissionNotice {...approvalNotice} isOwner={accessProfile?.role === "OWNER"} />}
    {notice && <div className={`form-notice ${actionState === "error" ? "warning" : ""}`} role="status">{notice}</div>}
    {!canManage && <div className="form-notice warning" role="note"><strong>{tx("Read-only access.", "Salt okunur erişim.")}</strong> {tx("You can inspect rules, reasons, and previews; GROWTH_MANAGE is required to save or request a release.", "Kuralları, nedenleri ve önizlemeleri inceleyebilirsiniz; kaydetmek veya yayın talep etmek için GROWTH_MANAGE gerekir.")}</div>}
    <div className="metric-grid meal-reminder-metrics">
      <MetricCard label={tx("Policy mode", "Politika modu")} value={summary?.mode ?? "—"} hint={tx("Admin policy; not the deployment gate", "Yönetim politikası; yayın kapısı değildir")} />
      <MetricCard label={tx("Deployment gate", "Yayın kapısı")} value={summary?.deploymentGateEnabled ? tx("OPEN", "AÇIK") : tx("CLOSED", "KAPALI")} hint={tx("Cannot be opened from this screen", "Bu ekrandan açılamaz")} />
      <MetricCard label={tx("General push", "Genel push")} value={summary?.pushGateEnabled ? tx("OPEN", "AÇIK") : tx("CLOSED", "KAPALI")} hint={tx("Shared provider delivery gate", "Ortak sağlayıcı teslimat kapısı")} />
    </div>
    <section className="communication-insight-strip meal-reminder-evidence"><div><p className="eyebrow">{tx("Reminder evidence", "Hatırlatma kanıtları")}</p><h3>{tx("Delivery and engagement signals", "Teslimat ve etkileşim sinyalleri")}</h3><p>{tx("Unique open rate", "Benzersiz açılma oranı")} {percent(summary?.uniqueOpenRate)} · {tx("Meal log within 2h", "2 saat içinde öğün kaydı")} {percent(summary?.mealLogWithin2hRate)} · {tx("Reminder opt-out", "Hatırlatmayı kapatma")} {percent(summary?.reminderOptOutRate)}. {tx("Correlation is not presented as causation.", "Korelasyon nedensellik olarak sunulmaz.")}</p></div><CommunicationBars items={[{ label: tx("Queued", "Kuyrukta"), value: summary?.outboxCount ?? 0 }, { label: tx("Provider accepted", "Sağlayıcı kabul etti"), value: summary?.providerAcceptedCount ?? 0, tone: "accent" }, { label: tx("Opened", "Açıldı"), value: summary?.uniqueOpenCount ?? 0 }, { label: tx("Meal log within 2h", "2 saatte öğün kaydı"), value: summary?.mealLogWithin2hCount ?? 0 }, { label: tx("Receipt failures", "Alındı hataları"), value: summary?.receiptFailedCount ?? 0, tone: "danger" }]} /></section>
    <div className="form-notice" role="note"><strong>{tx("Measurement boundary:", "Ölçüm sınırı:")}</strong> {summary?.measurementNote ?? tx("Meal logs after an open are correlation only; this dashboard does not claim the reminder caused the meal log.", "Açılma sonrası öğün kayıtları yalnızca korelasyondur; bu ekran hatırlatmanın kayda neden olduğunu iddia etmez.")}</div>
    <div className={`meal-reminder-safety ${config?.emergencyStopped ? "stopped" : ""}`} role="status"><div><strong>{config?.emergencyStopped ? tx("Emergency stop is active", "Acil durdurma etkin") : tx("No emergency stop", "Acil durdurma yok")}</strong><span>{config?.emergencyStopped ? config.stopReason : tx("Stopping cancels pending delivery eligibility. Reopening requires maker-checker approval and does not replay expired slots.", "Durdurma bekleyen teslimat uygunluğunu iptal eder. Yeniden açma çift kontrol onayı gerektirir ve süresi dolan zamanları tekrar çalıştırmaz.")}</span></div><span className={`badge ${config?.emergencyStopped ? "danger" : "good"}`}>{config?.emergencyStopped ? tx("STOPPED", "DURDURULDU") : tx("READY", "HAZIR")}</span></div>

    <div className="meal-reminder-two-column">
      <Panel title={tx("Schedule and safety rules", "Zamanlama ve güvenlik kuralları")} description={tx("Save a versioned draft first. Publication is a separate approved action.", "Önce sürümlü bir taslak kaydedin. Yayın ayrı bir onaylı işlemdir.")}>
        {draft ? <form className="meal-reminder-policy-form" onSubmit={(event) => void saveDraft(event)}>
          <div className="form-notice span-2" role="note"><strong>User-local schedule:</strong> These times are evaluated in each user's saved IANA timezone. Europe/Dublin daylight-saving changes are applied automatically; Europe/Istanbul remains UTC+3 year-round.</div>
          <label>Policy mode<select disabled={!canManage} value={draft.mode} onChange={(e) => setDraft({ ...draft, mode: e.target.value as MealReminderMode })}><option value="OFF">Off</option><option value="DRY_RUN">Dry run</option><option value="PILOT">Pilot</option><option value="LIVE">Live</option></select></label>
          <label>Breakfast time (user local)<input disabled={!canManage} type="time" value={draft.breakfastTime} onChange={(e) => setDraft({ ...draft, breakfastTime: e.target.value })} /></label><label>Lunch time (user local)<input disabled={!canManage} type="time" value={draft.lunchTime} onChange={(e) => setDraft({ ...draft, lunchTime: e.target.value })} /></label><label>Dinner time (user local)<input disabled={!canManage} type="time" value={draft.dinnerTime} onChange={(e) => setDraft({ ...draft, dinnerTime: e.target.value })} /></label>
          <label>Quiet hours start<input disabled={!canManage} type="time" value={draft.quietStart} onChange={(e) => setDraft({ ...draft, quietStart: e.target.value })} /></label><label>Quiet hours end<input disabled={!canManage} type="time" value={draft.quietEnd} onChange={(e) => setDraft({ ...draft, quietEnd: e.target.value })} /></label>
          <label>Daily limit<input disabled={!canManage} min={0} max={3} type="number" value={draft.maxDaily} onChange={(e) => setDraft({ ...draft, maxDaily: Number(e.target.value) })} /></label><label>24-hour limit<input disabled={!canManage} min={0} max={3} type="number" value={draft.maxRolling} onChange={(e) => setDraft({ ...draft, maxRolling: Number(e.target.value) })} /></label><label>Daily catch-ups<input disabled={!canManage} min={0} max={1} type="number" value={draft.maxCatchups} onChange={(e) => setDraft({ ...draft, maxCatchups: Number(e.target.value) })} /></label><label>Slot age (minutes)<input disabled={!canManage} min={1} max={60} type="number" value={draft.slotAgeMinutes} onChange={(e) => setDraft({ ...draft, slotAgeMinutes: Number(e.target.value) })} /></label>
          <label>Meal cooldown (minutes)<input disabled={!canManage} min={180} type="number" value={draft.minimumGapMinutes} onChange={(e) => setDraft({ ...draft, minimumGapMinutes: Number(e.target.value) })} /></label><label>Routine cooldown (minutes)<input disabled={!canManage} min={30} type="number" value={draft.routineGapMinutes} onChange={(e) => setDraft({ ...draft, routineGapMinutes: Number(e.target.value) })} /></label>
          <label className="span-2">Approved pilot user IDs<input disabled={!canManage} inputMode="numeric" placeholder="12, 48" value={draft.pilotUserIds} onChange={(e) => setDraft({ ...draft, pilotUserIds: e.target.value.replace(/[^0-9, ]/g, "") })} /><small>IDs only; no health data or device tokens are shown.</small></label>
          <label className="toggle-field span-2"><input disabled={!canManage} type="checkbox" checked={draft.kcalEnabled} onChange={(e) => setDraft({ ...draft, kcalEnabled: e.target.checked })} />Allow safe rounded remaining-kcal copy when all reliability checks pass</label>
          <div className="meal-reminder-draft-state span-2"><span className={`badge ${dirty ? "warn" : "neutral"}`}>{dirty ? "UNSAVED CHANGES" : draftId ? "DRAFT SAVED" : "MATCHES ACTIVE"}</span><small>Version {draft.version ?? "new"}; concurrent saves fail visibly.</small></div>
          <div className="inline-actions span-2"><button className="ghost-button" disabled={!canManage || actionState === "loading"} type="submit">Save draft</button><button className="primary-button" disabled={!canManage || !draftId || !reason.trim() || actionState === "loading"} type="button" onClick={() => void requestAction(`${API}/drafts/${draftId}/publish-request`, "Publication is pending maker-checker approval. No delivery was started.")}>Request publication</button></div>
        </form> : <p>No policy configuration returned.</p>}
      </Panel>
      <Panel title={tx("Release controls", "Yayın kontrolleri")} description={tx("Every state-changing action requires an audit reason.", "Durum değiştiren her işlem bir denetim nedeni gerektirir.")}>
        <label>{tx("Required reason", "Zorunlu neden")}<textarea disabled={!canManage} maxLength={500} value={reason} onChange={(e) => setReason(e.target.value)} placeholder={tx("Explain the operational need and expected outcome.", "Operasyon ihtiyacını ve beklenen sonucu açıklayın.")} /><small>{reason.length}/500</small></label>
        <div className="meal-reminder-release-actions"><button className="danger-button" disabled={!canManage || !reason.trim() || config?.emergencyStopped} type="button" onClick={() => void requestAction(`${API}/emergency-stop`, "Emergency stop applied. Pending work will be revalidated and expired slots will not replay.", false)}>Emergency stop now</button><button className="ghost-button" disabled={!canManage || !reason.trim() || !config?.emergencyStopped} type="button" onClick={() => void requestAction(`${API}/reopen-request`, "Reopening is pending approval. This request does not trigger a new send.")}>Request reopening</button></div>
        <label>Approved test user ID<input disabled={!canManage} inputMode="numeric" min={1} type="number" value={testUserId} onChange={(event) => setTestUserId(event.target.value.replace(/\D/g, ""))} placeholder="6" /><small>The user must be in the approved pilot list. Test sends require approval and are limited to one per user per hour.</small></label>
        <button className="ghost-button" disabled={!canManage || !reason.trim() || !Number(testUserId) || actionState === "loading"} type="button" onClick={() => void requestAction(`${API}/test-accounts/${Number(testUserId)}/send-request`, `Test send for user ${testUserId} is pending maker-checker approval.`)}>Request test send</button>
        <div className="form-notice warning"><strong>Deployment boundary:</strong> Publishing LIVE here cannot open the environment kill switch or general push gate. Reopening never backfills stale breakfast, lunch, or dinner slots.</div>
        <button className="text-button" type="button" onClick={() => onNavigate("notificationDefinitions")}>Review protected TR/EN copy and typed placeholders →</button>
      </Panel>
    </div>

    <Panel title={tx("Synthetic scenario preview", "Sentetik senaryo önizlemesi")} description={tx("Uses example inputs only. It never reads a user's diary, creates a notification, or calls a provider.", "Yalnızca örnek girdiler kullanır; kullanıcı günlüğünü okumaz, bildirim oluşturmaz veya sağlayıcıyı çağırmaz.")}>
      <form className="meal-reminder-preview-form" onSubmit={(event) => void runPreview(event)}>
        <label>Scenario time<input type="datetime-local" value={scenario.evaluatedAt} onChange={(e) => setScenario({ ...scenario, evaluatedAt: e.target.value })} /></label><label>User timezone<input required value={scenario.timeZone} onChange={(e) => setScenario({ ...scenario, timeZone: e.target.value })} /></label><label>User local date<input type="date" value={scenario.localDate} onChange={(e) => setScenario({ ...scenario, localDate: e.target.value })} /></label><label>Language<select value={scenario.language} onChange={(e) => setScenario({ ...scenario, language: e.target.value as "en" | "tr" })}><option value="en">English</option><option value="tr">Türkçe</option></select></label>
        {(["breakfast", "lunch", "dinner"] as const).map((meal) => <label key={meal}>{meal[0].toUpperCase() + meal.slice(1)}<select value={scenario[meal]} onChange={(e) => setScenario({ ...scenario, [meal]: e.target.value })}>{MEAL_STATES.map((value) => <option key={value}>{value}</option>)}</select></label>)}
        <label>Target kcal<input min={1} type="number" value={scenario.targetCalories} onChange={(e) => setScenario({ ...scenario, targetCalories: e.target.value })} /></label><label>Consumed kcal<input min={0} type="number" value={scenario.consumedCalories} onChange={(e) => setScenario({ ...scenario, consumedCalories: e.target.value })} /></label>
        <label className="toggle-field"><input type="checkbox" checked={scenario.fastingActive} onChange={(e) => setScenario({ ...scenario, fastingActive: e.target.checked })} />Active fast</label><label className="toggle-field"><input type="checkbox" checked={scenario.pushEnabled} onChange={(e) => setScenario({ ...scenario, pushEnabled: e.target.checked })} />Push preference on</label><label className="toggle-field"><input type="checkbox" checked={scenario.mealRemindersEnabled} onChange={(e) => setScenario({ ...scenario, mealRemindersEnabled: e.target.checked })} />Meal reminders on</label>
        <div className="meal-reminder-time-compare"><span>Admin/browser time: <strong>{dateLabel(scenario.evaluatedAt)}</strong></span><span>Example user-local time: <strong>{userTime}</strong></span></div><button className="primary-button" disabled={actionState === "loading"} type="submit">Preview decision</button>
      </form>
      {preview && <div className={`meal-reminder-preview-result ${preview.shouldSend ? "eligible" : "suppressed"}`} aria-live="polite"><div><span className="eyebrow">{preview.shouldSend ? "Would send" : "Would not send"}</span><h4>{REASONS[preview.reason ?? ""] ?? "The scenario was evaluated with the active safety contract."}</h4><p>{preview.copy?.title && <strong>{preview.copy.title}: </strong>}{preview.copy?.body}</p></div><details><summary>Technical decision</summary><code>{preview.reason ?? "—"} / {preview.kcalReason ?? "—"} / {preview.slot ?? "NO_SLOT"}</code></details></div>}
    </Panel>

    <div className="meal-reminder-two-column">
      <Panel title={tx("Redacted decision records", "Maskelenmiş karar kayıtları")} description={tx("No diary values, health details, emails, or device tokens are returned.", "Günlük değerleri, sağlık ayrıntıları, e-postalar veya cihaz tokenları gösterilmez.")}><DataTable caption={tx("Meal reminder decision records", "Öğün hatırlatma karar kayıtları")} columns={[tx("Evaluated", "Değerlendirme"), tx("Candidate", "Aday"), tx("Decision", "Karar"), tx("Friendly reason", "Açıklama")]} rows={pagedDecisions.map((item) => [dateLabel(item.evaluatedAt), item.candidate ?? "—", item.shouldSend ? tx("Would send", "Gönderilirdi") : tx("Suppressed", "Engellendi"), REASONS[item.reason ?? ""] ?? item.reason ?? "—"])} empty={tx("No dry-run decisions returned.", "Deneme kararı bulunamadı.")} /><div className="inline-actions meal-reminder-pagination"><button className="ghost-button" disabled={decisionPage === 0} type="button" onClick={() => setDecisionPage((page) => Math.max(0, page - 1))}>{tx("Previous", "Önceki")}</button><span>{tx("Page", "Sayfa")} {decisionPage + 1} / {Math.max(1, Math.ceil(decisions.length / pageSize))}</span><button className="ghost-button" disabled={(decisionPage + 1) * pageSize >= decisions.length} type="button" onClick={() => setDecisionPage((page) => page + 1)}>{tx("Next", "Sonraki")}</button></div></Panel>
      <Panel title={tx("Policy publication history", "Politika yayın geçmişi")} description={tx("Draft, active, and archived versions remain visibly distinct.", "Taslak, etkin ve arşivlenmiş sürümler ayrı gösterilir.")}><DataTable caption={tx("Meal reminder policy history", "Öğün hatırlatma politika geçmişi")} columns={[tx("Version", "Sürüm"), tx("Status", "Durum"), tx("Mode", "Mod"), tx("Updated", "Güncellendi")]} rows={history.map((item) => [item.policyVersion, item.status, item.mode, dateLabel(item.updatedAt)])} empty={tx("No policy history returned.", "Politika geçmişi bulunamadı.")} /></Panel>
    </div>
  </div>;
}
