spring:
  application:
    name: grun-calorie-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/grun_calorie_db
    username: postgres
    password: Magellan1!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret:  GRun_Calorie_Tracker_SecretKey_2025!@#ZK34mdgshv7238aWQxYz

  openfoodfacts:
    api:
      base-url: "https://world.openfoodfacts.org"
      search-path: "/cgi/search.pl"
      product-path: "/api/v2/product/{barcode}.json"