package com.grun.calorietracker.service.impl;

import com.grun.calorietracker.config.AiProperties;
import com.grun.calorietracker.dto.AiInsightRequestDto;
import com.grun.calorietracker.dto.AiInsightResponseDto;
import com.grun.calorietracker.dto.AiMealDraftItemDto;
import com.grun.calorietracker.dto.AiMealDraftResponseDto;
import com.grun.calorietracker.dto.AiPhotoMealDraftRequestDto;
import com.grun.calorietracker.dto.AiProductQualityValidationRequestDto;
import com.grun.calorietracker.dto.AiProductQualityValidationResponseDto;
import com.grun.calorietracker.dto.AiRecipeIngredientSuggestionDto;
import com.grun.calorietracker.dto.AiRecipeDraftRequestDto;
import com.grun.calorietracker.dto.AiRecipeDraftResponseDto;
import com.grun.calorietracker.dto.AiVoiceFoodDraftRequestDto;
import com.grun.calorietracker.dto.AiWorkoutPlanDayDto;
import com.grun.calorietracker.dto.AiWorkoutPlanDraftRequestDto;
import com.grun.calorietracker.dto.AiWorkoutPlanDraftResponseDto;
import com.grun.calorietracker.dto.AiWorkoutPlanExerciseDto;
import com.grun.calorietracker.dto.RecipeRequestDto;
import com.grun.calorietracker.dto.RecipeNutritionDto;
import com.grun.calorietracker.dto.RecipeStepRequestDto;
import com.grun.calorietracker.enums.AiProvider;
import com.grun.calorietracker.enums.AiRequestStatus;
import com.grun.calorietracker.enums.AiRequestType;
import com.grun.calorietracker.enums.ExerciseLogMeasurementType;
import com.grun.calorietracker.enums.FoodPortionUnit;
import com.grun.calorietracker.enums.ProductQualitySuggestionType;
import com.grun.calorietracker.service.AiMealDraftProviderClient;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.List;

@Component
@RequiredArgsConstructor
public class LogAiMealDraftProviderClient implements AiMealDraftProviderClient {

    private final AiProperties properties;

    @Override
    public AiProvider provider() {
        return AiProvider.LOG;
    }

    @Override
    public AiMealDraftResponseDto createVoiceFoodDraft(AiVoiceFoodDraftRequestDto request) {
        AiMealDraftResponseDto response = baseResponse(AiRequestType.VOICE_FOOD_LOG, request.getMealType(), request.getLogDate());
        response.setSummary("Draft generated from transcript. Configure a real AI provider before production use.");
        response.setItems(List.of(sampleItem(request.getTranscript())));
        return response;
    }

    @Override
    public AiMealDraftResponseDto createPhotoMealDraft(AiPhotoMealDraftRequestDto request) {
        AiMealDraftResponseDto response = baseResponse(AiRequestType.PHOTO_MEAL_LOG, request.getMealType(), request.getLogDate());
        response.setSummary("Draft generated from image reference. Configure a real vision provider before production use.");
        response.setItems(List.of(sampleItem(request.getUserNote() == null ? request.getImageReference() : request.getUserNote())));
        return response;
    }

    @Override
    public AiRecipeDraftResponseDto createRecipeDraft(AiRecipeDraftRequestDto request) {
        AiRecipeDraftResponseDto response = new AiRecipeDraftResponseDto();
        response.setRequestType(AiRequestType.AI_RECIPE_GENERATION);
        response.setProvider(AiProvider.LOG);
        response.setModel(properties.getModel());
        response.setStatus(AiRequestStatus.DRAFT_CREATED);
        response.setSummary("Recipe draft generated by LOG provider. Configure a real AI provider before production use.");
        response.setReviewRequired(true);
        response.setSuggestedRecipe(sampleRecipe(request));
        response.setSuggestedIngredients(sampleIngredients(request));
        response.setEstimatedNutritionTotal(sampleNutritionTotal());
        response.setEstimatedNutritionPerServing(sampleNutritionPerServing());
        response.setNutritionEstimateNote("Estimated preview nutrition generated from typical ingredient values. Confirmed recipe nutrition is recalculated from matched ingredients.");
        response.setWarnings(List.of("Ingredients must be reviewed and mapped to real foodItemId values before confirmation."));
        return response;
    }

    @Override
    public AiWorkoutPlanDraftResponseDto createWorkoutPlanDraft(AiWorkoutPlanDraftRequestDto request) {
        AiWorkoutPlanDraftResponseDto response = new AiWorkoutPlanDraftResponseDto();
        response.setRequestType(AiRequestType.AI_WORKOUT_PLAN);
        response.setProvider(AiProvider.LOG);
        response.setModel(properties.getModel());
        response.setStatus(AiRequestStatus.DRAFT_CREATED);
        response.setName(request.getGoal() == null || request.getGoal().isBlank() ? "AI workout plan" : request.getGoal().trim());
        response.setSummary("Workout plan draft generated by LOG provider. Review before activating.");
        response.setReviewRequired(true);
        response.setDays(List.of(sampleWorkoutDay("Day 1", "Full body foundation"), sampleWorkoutDay("Day 2", "Cardio and mobility")));
        response.setWarnings(List.of("This draft is not medical advice. Stop if pain or dizziness occurs."));
        return response;
    }

    @Override
    public AiInsightResponseDto createDailyInsight(AiInsightRequestDto request) {
        return insight(AiRequestType.AI_DAILY_INSIGHT, "Daily coaching insight", "Review today's nutrition, movement and recovery before taking action.");
    }

    @Override
    public AiInsightResponseDto createWeeklyInsight(AiInsightRequestDto request) {
        return insight(AiRequestType.AI_WEEKLY_INSIGHT, "Weekly coaching insight", "Use this weekly review to adjust the next week's plan gradually.");
    }


    @Override
    public AiProductQualityValidationResponseDto validateProductQuality(AiProductQualityValidationRequestDto request) {
        List<AiProductQualityValidationResponseDto.AiProductQualityIssueDto> issues = new java.util.ArrayList<>();
        if (request.getCalories() == null || request.getProtein() == null || request.getFat() == null || request.getCarbs() == null) {
            issues.add(issue(ProductQualitySuggestionType.MISSING_MACRO_DATA, "macros", null, null, "Calories, protein, fat and carbs should be complete before treating this product as trusted.", 82));
        }
        if (request.getCalcium() == null || request.getIron() == null || request.getPotassium() == null || request.getVitaminC() == null) {
            issues.add(issue(ProductQualitySuggestionType.MISSING_MICRO_DATA, "micronutrients", null, null, "Key micronutrients are missing; product quality can be improved with verified label/source data.", 74));
        }
        if (request.getServingSizeGrams() == null || request.getServingSizeGrams() <= 0) {
            issues.add(issue(ProductQualitySuggestionType.MISSING_SERVING_SIZE, "servingSizeGrams", null, null, "Serving conversion may be inaccurate without a serving size in grams.", 78));
        }
        Double macroCalories = macroCalories(request);
        if (request.getCalories() != null && macroCalories != null && Math.abs(request.getCalories() - macroCalories) > 80) {
            issues.add(issue(ProductQualitySuggestionType.MACRO_CALORIE_MISMATCH, "calories", String.valueOf(request.getCalories()), String.valueOf(Math.round(macroCalories)), "Calories differ materially from protein/fat/carbs energy estimate; review label/source data.", 86));
        }
        AiProductQualityValidationResponseDto response = new AiProductQualityValidationResponseDto();
        response.setSummary(issues.isEmpty() ? "No obvious LOG-provider quality issue found." : "LOG provider found product quality issues for admin review.");
        response.setConfidence(issues.isEmpty() ? 0.35 : 0.55);
        response.setQualityScore(issues.isEmpty() ? 75 : Math.max(30, 75 - issues.size() * 10));
        response.setReviewRequired(!issues.isEmpty());
        response.setIssues(issues);
        return response;
    }

    private AiProductQualityValidationResponseDto.AiProductQualityIssueDto issue(ProductQualitySuggestionType type, String fieldName, String currentValue, String suggestedValue, String reason, Integer confidenceScore) {
        AiProductQualityValidationResponseDto.AiProductQualityIssueDto issue = new AiProductQualityValidationResponseDto.AiProductQualityIssueDto();
        issue.setSuggestionType(type);
        issue.setFieldName(fieldName);
        issue.setCurrentValue(currentValue);
        issue.setSuggestedValue(suggestedValue);
        issue.setReason(reason);
        issue.setConfidenceScore(confidenceScore);
        return issue;
    }

    private Double macroCalories(AiProductQualityValidationRequestDto request) {
        if (request.getProtein() == null || request.getFat() == null || request.getCarbs() == null) {
            return null;
        }
        return request.getProtein() * 4 + request.getFat() * 9 + request.getCarbs() * 4;
    }

    private AiInsightResponseDto insight(AiRequestType type, String title, String summary) {
        AiInsightResponseDto response = new AiInsightResponseDto();
        response.setRequestType(type);
        response.setProvider(AiProvider.LOG);
        response.setModel(properties.getModel());
        response.setStatus(AiRequestStatus.DRAFT_CREATED);
        response.setTitle(title);
        response.setSummary(summary);
        response.setHighlights(List.of("Calories, protein, exercise and consistency were reviewed together.", "Data coverage is included so the user can see what was analyzed."));
        response.setRecommendedActions(List.of("Keep changes small and review the data again after several days."));
        response.setWarnings(List.of("AI insights are guidance only and should not replace medical advice."));
        response.setTomorrowFocus("Improve one measurable habit tomorrow instead of changing everything at once.");
        response.setWatchOut("Avoid overreacting to one metric; use the full pattern before changing the plan.");
        response.setDataQualityNote("LOG provider sample uses app-scoped context and marks missing signals explicitly.");
        AiInsightResponseDto.DataCoverage coverage = new AiInsightResponseDto.DataCoverage();
        coverage.setDaysAnalyzed(type == AiRequestType.AI_WEEKLY_INSIGHT ? 7 : 1);
        coverage.setMealsLogged(type == AiRequestType.AI_WEEKLY_INSIGHT ? null : 1);
        coverage.setExerciseLogged(true);
        coverage.setExerciseMinutes(20);
        coverage.setDiaryDays(type == AiRequestType.AI_WEEKLY_INSIGHT ? 5 : 1);
        coverage.setSignalsUsed(List.of("calories", "protein", "exercise", "logging consistency"));
        coverage.setMissingSignals(List.of("water", "sleep"));
        coverage.setConfidenceLabel("MEDIUM");
        response.setDataCoverage(coverage);
        response.setKeyFindings(List.of(
                finding("trend", "Calorie control", "Calories were reviewed against the user's target instead of repeated as a raw number.", "Target and consumed calories from app summary.", "Shows whether tomorrow needs adjustment or stability.", "LOW"),
                finding("pattern", "Next improvement", "The next recommendation should focus on the weakest visible signal, not generic motivation.", "Nutrition and activity context from the app.", "Makes coaching feel personalized.", "LOW")
        ));
        response.setPersonalizedActions(List.of(
                action(1, "Choose one small nutrition improvement for tomorrow.", "Small actions are easier to follow and easier to measure.", "Clearer progress signal tomorrow.", "LOW", "nutritionQualityScore"),
                action(2, "Keep logging complete enough for the next insight.", "Missing logs reduce coaching confidence.", "More personal weekly analysis.", "LOW", "loggingConsistency")
        ));
        return response;
    }


    private AiInsightResponseDto.KeyFinding finding(String type, String label, String message, String evidence, String impact, String severity) {
        AiInsightResponseDto.KeyFinding finding = new AiInsightResponseDto.KeyFinding();
        finding.setType(type);
        finding.setLabel(label);
        finding.setMessage(message);
        finding.setEvidence(evidence);
        finding.setImpact(impact);
        finding.setSeverity(severity);
        return finding;
    }

    private AiInsightResponseDto.PersonalizedAction action(int priority, String action, String reason, String expectedImpact, String effort, String linkedMetric) {
        AiInsightResponseDto.PersonalizedAction item = new AiInsightResponseDto.PersonalizedAction();
        item.setPriority(priority);
        item.setAction(action);
        item.setReason(reason);
        item.setExpectedImpact(expectedImpact);
        item.setEffort(effort);
        item.setLinkedMetric(linkedMetric);
        return item;
    }

    private AiWorkoutPlanDayDto sampleWorkoutDay(String label, String focus) {
        AiWorkoutPlanDayDto day = new AiWorkoutPlanDayDto();
        day.setDayLabel(label);
        day.setFocus(focus);
        day.setEstimatedDurationMinutes(35);
        day.setWarmup("5 minutes easy movement, joint circles, and two light practice sets.");
        day.setCooldown("3-5 minutes easy walking followed by relaxed stretching for the trained muscles.");
        day.setExercises(List.of(sampleWorkoutExercise("Bodyweight Squat", ExerciseLogMeasurementType.SETS_REPS), sampleWorkoutExercise("Walking", ExerciseLogMeasurementType.DURATION)));
        return day;
    }

    private AiWorkoutPlanExerciseDto sampleWorkoutExercise(String name, ExerciseLogMeasurementType measurementType) {
        AiWorkoutPlanExerciseDto exercise = new AiWorkoutPlanExerciseDto();
        exercise.setName(name);
        exercise.setMeasurementType(measurementType);
        exercise.setSetCount(measurementType == ExerciseLogMeasurementType.SETS_REPS ? 3 : null);
        exercise.setReps(measurementType == ExerciseLogMeasurementType.SETS_REPS ? 10 : null);
        exercise.setDurationMinutes(measurementType == ExerciseLogMeasurementType.DURATION ? 20 : null);
        exercise.setRest("60 sec");
        exercise.setRationale("Low-risk foundation movement for consistency.");
        exercise.setExecutionInstructions("Set up with stable posture, brace your core, move through a comfortable range of motion, and finish each rep under control.");
        exercise.setFormCues(List.of("Brace core", "Keep the movement controlled", "Avoid rushing reps"));
        exercise.setCommonMistakes(List.of("Using momentum", "Losing posture", "Ignoring pain signals"));
        exercise.setTempo(measurementType == ExerciseLogMeasurementType.SETS_REPS ? "2 sec down, controlled up" : "steady conversational pace");
        exercise.setAlternatives(List.of("Easier variation", "Lower range of motion"));
        exercise.setRestSeconds(60);
        exercise.setIntensity("MODERATE");
        exercise.setProgressionNote("Add 1-2 reps or 2-5 minutes next week only if the session feels controlled.");
        exercise.setTargetMuscleGroup(measurementType == ExerciseLogMeasurementType.SETS_REPS ? "FULL_BODY" : "CARDIO");
        exercise.setEquipmentUsed("BODYWEIGHT");
        exercise.setReviewRequired(false);
        exercise.setSafetyNote("Keep the movement controlled and stop if pain appears.");
        return exercise;
    }

    private AiMealDraftResponseDto baseResponse(AiRequestType type, String mealType, LocalDateTime logDate) {
        AiMealDraftResponseDto response = new AiMealDraftResponseDto();
        response.setRequestType(type);
        response.setProvider(AiProvider.LOG);
        response.setModel(properties.getModel());
        response.setStatus(AiRequestStatus.DRAFT_CREATED);
        response.setSuggestedMealType(mealType == null || mealType.isBlank() ? "SNACK" : mealType.trim().toUpperCase());
        response.setSuggestedLogDate(logDate == null ? LocalDateTime.now() : logDate);
        return response;
    }

    private AiMealDraftItemDto sampleItem(String sourceText) {
        AiMealDraftItemDto item = new AiMealDraftItemDto();
        item.setName(resolveSampleName(sourceText));
        item.setQuantity(100.0);
        item.setUnit("g");
        item.setEstimatedCalories(150.0);
        item.setEstimatedProtein(10.0);
        item.setEstimatedCarbs(15.0);
        item.setEstimatedFat(5.0);
        item.setConfidence(0.3);
        return item;
    }

    private String resolveSampleName(String sourceText) {
        if (sourceText == null || sourceText.isBlank()) {
            return "Unverified meal item";
        }
        String normalized = sourceText.trim().replaceAll("\\s+", " ");
        return normalized.length() > 60 ? normalized.substring(0, 60) : normalized;
    }

    private RecipeRequestDto sampleRecipe(AiRecipeDraftRequestDto request) {
        RecipeRequestDto recipe = new RecipeRequestDto();
        recipe.setName(resolveRecipeName(request));
        recipe.setDescription("AI-generated recipe draft. Review ingredients and portions before saving.");
        recipe.setMealType(request.getMealType() == null || request.getMealType().isBlank()
                ? "DINNER"
                : request.getMealType().trim().toUpperCase());
        recipe.setMarketRegion(request.getMarketRegion());
        recipe.setLanguage(request.getLanguage());
        recipe.setServingCount(request.getServingCount() == null ? 1 : request.getServingCount());
        recipe.setTotalYieldGrams(100.0);
        recipe.setDefaultServingGrams(100.0);
        recipe.setIngredients(List.of());
        recipe.setCookingSteps(List.of(
                step("Season the main protein and prepare all vegetables before heating the pan."),
                step("Cook the protein until done, keeping heat controlled to avoid drying it out."),
                step("Cook or steam vegetables until tender, then season lightly."),
                step("Plate the protein with vegetables and review portions before saving.")
        ));
        return recipe;
    }


    private RecipeNutritionDto sampleNutritionTotal() {
        return new RecipeNutritionDto(520.0, 48.0, 34.0, 18.0, 8.0, 9.0, 4.5, 680.0, 980.0, 95.0, 140.0, 4.2, 85.0, 3.1, 620.0, 42.0, 2.0, 3.5, 2.4);
    }

    private RecipeNutritionDto sampleNutritionPerServing() {
        return new RecipeNutritionDto(520.0, 48.0, 34.0, 18.0, 8.0, 9.0, 4.5, 680.0, 980.0, 95.0, 140.0, 4.2, 85.0, 3.1, 620.0, 42.0, 2.0, 3.5, 2.4);
    }

    private RecipeStepRequestDto step(String instruction) {
        RecipeStepRequestDto step = new RecipeStepRequestDto();
        step.setInstruction(instruction);
        return step;
    }

    private List<AiRecipeIngredientSuggestionDto> sampleIngredients(AiRecipeDraftRequestDto request) {
        List<String> names = request.getAvailableIngredients() == null || request.getAvailableIngredients().isEmpty()
                ? List.of("Chicken breast")
                : request.getAvailableIngredients().stream().limit(5).toList();
        return names.stream().map(name -> {
            AiRecipeIngredientSuggestionDto item = new AiRecipeIngredientSuggestionDto();
            item.setName(name);
            item.setPortionSize(100.0);
            item.setPortionUnit(FoodPortionUnit.GRAM);
            item.setReviewRequired(true);
            item.setMatchReason("LOG_PROVIDER_SAMPLE");
            item.setConfidence(0.3);
            return item;
        }).toList();
    }

    private String resolveRecipeName(AiRecipeDraftRequestDto request) {
        if (request.getPrompt() == null || request.getPrompt().isBlank()) {
            return "AI recipe draft";
        }
        String normalized = request.getPrompt().trim().replaceAll("\\s+", " ");
        return normalized.length() > 120 ? normalized.substring(0, 120) : normalized;
    }
}




