package com.grun.calorietracker.service.impl;

import com.grun.calorietracker.config.AiProperties;
import com.grun.calorietracker.dto.AiInsightRequestDto;
import com.grun.calorietracker.dto.AiInsightResponseDto;
import com.grun.calorietracker.dto.AiMealDraftItemDto;
import com.grun.calorietracker.dto.AiMealDraftResponseDto;
import com.grun.calorietracker.dto.AiPhotoMealDraftRequestDto;
import com.grun.calorietracker.dto.AiRecipeIngredientSuggestionDto;
import com.grun.calorietracker.dto.AiRecipeDraftRequestDto;
import com.grun.calorietracker.dto.AiRecipeDraftResponseDto;
import com.grun.calorietracker.dto.AiVoiceFoodDraftRequestDto;
import com.grun.calorietracker.dto.AiWorkoutPlanDayDto;
import com.grun.calorietracker.dto.AiWorkoutPlanDraftRequestDto;
import com.grun.calorietracker.dto.AiWorkoutPlanDraftResponseDto;
import com.grun.calorietracker.dto.AiWorkoutPlanExerciseDto;
import com.grun.calorietracker.dto.RecipeRequestDto;
import com.grun.calorietracker.enums.AiProvider;
import com.grun.calorietracker.enums.AiRequestStatus;
import com.grun.calorietracker.enums.AiRequestType;
import com.grun.calorietracker.enums.ExerciseLogMeasurementType;
import com.grun.calorietracker.enums.FoodPortionUnit;
import com.grun.calorietracker.service.AiMealDraftProviderClient;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.List;

@Component
@RequiredArgsConstructor
public class LogAiMealDraftProviderClient implements AiMealDraftProviderClient {

    private final AiProperties properties;

    @Override
    public AiProvider provider() {
        return AiProvider.LOG;
    }

    @Override
    public AiMealDraftResponseDto createVoiceFoodDraft(AiVoiceFoodDraftRequestDto request) {
        AiMealDraftResponseDto response = baseResponse(AiRequestType.VOICE_FOOD_LOG, request.getMealType(), request.getLogDate());
        response.setSummary("Draft generated from transcript. Configure a real AI provider before production use.");
        response.setItems(List.of(sampleItem(request.getTranscript())));
        return response;
    }

    @Override
    public AiMealDraftResponseDto createPhotoMealDraft(AiPhotoMealDraftRequestDto request) {
        AiMealDraftResponseDto response = baseResponse(AiRequestType.PHOTO_MEAL_LOG, request.getMealType(), request.getLogDate());
        response.setSummary("Draft generated from image reference. Configure a real vision provider before production use.");
        response.setItems(List.of(sampleItem(request.getUserNote() == null ? request.getImageReference() : request.getUserNote())));
        return response;
    }

    @Override
    public AiRecipeDraftResponseDto createRecipeDraft(AiRecipeDraftRequestDto request) {
        AiRecipeDraftResponseDto response = new AiRecipeDraftResponseDto();
        response.setRequestType(AiRequestType.AI_RECIPE_GENERATION);
        response.setProvider(AiProvider.LOG);
        response.setModel(properties.getModel());
        response.setStatus(AiRequestStatus.DRAFT_CREATED);
        response.setSummary("Recipe draft generated by LOG provider. Configure a real AI provider before production use.");
        response.setReviewRequired(true);
        response.setSuggestedRecipe(sampleRecipe(request));
        response.setSuggestedIngredients(sampleIngredients(request));
        response.setWarnings(List.of("Ingredients must be reviewed and mapped to real foodItemId values before confirmation."));
        return response;
    }

    @Override
    public AiWorkoutPlanDraftResponseDto createWorkoutPlanDraft(AiWorkoutPlanDraftRequestDto request) {
        AiWorkoutPlanDraftResponseDto response = new AiWorkoutPlanDraftResponseDto();
        response.setRequestType(AiRequestType.AI_WORKOUT_PLAN);
        response.setProvider(AiProvider.LOG);
        response.setModel(properties.getModel());
        response.setStatus(AiRequestStatus.DRAFT_CREATED);
        response.setName(request.getGoal() == null || request.getGoal().isBlank() ? "AI workout plan" : request.getGoal().trim());
        response.setSummary("Workout plan draft generated by LOG provider. Review before activating.");
        response.setReviewRequired(true);
        response.setDays(List.of(sampleWorkoutDay("Day 1", "Full body foundation"), sampleWorkoutDay("Day 2", "Cardio and mobility")));
        response.setWarnings(List.of("This draft is not medical advice. Stop if pain or dizziness occurs."));
        return response;
    }

    @Override
    public AiInsightResponseDto createDailyInsight(AiInsightRequestDto request) {
        return insight(AiRequestType.AI_DAILY_INSIGHT, "Daily coaching insight", "Review today's nutrition, movement and recovery before taking action.");
    }

    @Override
    public AiInsightResponseDto createWeeklyInsight(AiInsightRequestDto request) {
        return insight(AiRequestType.AI_WEEKLY_INSIGHT, "Weekly coaching insight", "Use this weekly review to adjust the next week's plan gradually.");
    }

    private AiInsightResponseDto insight(AiRequestType type, String title, String summary) {
        AiInsightResponseDto response = new AiInsightResponseDto();
        response.setRequestType(type);
        response.setProvider(AiProvider.LOG);
        response.setModel(properties.getModel());
        response.setStatus(AiRequestStatus.DRAFT_CREATED);
        response.setTitle(title);
        response.setSummary(summary);
        response.setHighlights(List.of("Protein, calories, exercise, water and step data can be interpreted here."));
        response.setRecommendedActions(List.of("Keep changes small and review the data again after several days."));
        response.setWarnings(List.of("AI insights are guidance only and should not replace medical advice."));
        return response;
    }

    private AiWorkoutPlanDayDto sampleWorkoutDay(String label, String focus) {
        AiWorkoutPlanDayDto day = new AiWorkoutPlanDayDto();
        day.setDayLabel(label);
        day.setFocus(focus);
        day.setExercises(List.of(sampleWorkoutExercise("Bodyweight Squat", ExerciseLogMeasurementType.SETS_REPS), sampleWorkoutExercise("Walking", ExerciseLogMeasurementType.DURATION)));
        return day;
    }

    private AiWorkoutPlanExerciseDto sampleWorkoutExercise(String name, ExerciseLogMeasurementType measurementType) {
        AiWorkoutPlanExerciseDto exercise = new AiWorkoutPlanExerciseDto();
        exercise.setName(name);
        exercise.setMeasurementType(measurementType);
        exercise.setSetCount(measurementType == ExerciseLogMeasurementType.SETS_REPS ? 3 : null);
        exercise.setReps(measurementType == ExerciseLogMeasurementType.SETS_REPS ? 10 : null);
        exercise.setDurationMinutes(measurementType == ExerciseLogMeasurementType.DURATION ? 20 : null);
        exercise.setRest("60 sec");
        exercise.setRationale("Low-risk foundation movement for consistency.");
        exercise.setSafetyNote("Keep the movement controlled and stop if pain appears.");
        return exercise;
    }

    private AiMealDraftResponseDto baseResponse(AiRequestType type, String mealType, LocalDateTime logDate) {
        AiMealDraftResponseDto response = new AiMealDraftResponseDto();
        response.setRequestType(type);
        response.setProvider(AiProvider.LOG);
        response.setModel(properties.getModel());
        response.setStatus(AiRequestStatus.DRAFT_CREATED);
        response.setSuggestedMealType(mealType == null || mealType.isBlank() ? "SNACK" : mealType.trim().toUpperCase());
        response.setSuggestedLogDate(logDate == null ? LocalDateTime.now() : logDate);
        return response;
    }

    private AiMealDraftItemDto sampleItem(String sourceText) {
        AiMealDraftItemDto item = new AiMealDraftItemDto();
        item.setName(resolveSampleName(sourceText));
        item.setQuantity(100.0);
        item.setUnit("g");
        item.setEstimatedCalories(150.0);
        item.setEstimatedProtein(10.0);
        item.setEstimatedCarbs(15.0);
        item.setEstimatedFat(5.0);
        item.setConfidence(0.3);
        return item;
    }

    private String resolveSampleName(String sourceText) {
        if (sourceText == null || sourceText.isBlank()) {
            return "Unverified meal item";
        }
        String normalized = sourceText.trim().replaceAll("\\s+", " ");
        return normalized.length() > 60 ? normalized.substring(0, 60) : normalized;
    }

    private RecipeRequestDto sampleRecipe(AiRecipeDraftRequestDto request) {
        RecipeRequestDto recipe = new RecipeRequestDto();
        recipe.setName(resolveRecipeName(request));
        recipe.setDescription("AI-generated recipe draft. Review ingredients and portions before saving.");
        recipe.setMealType(request.getMealType() == null || request.getMealType().isBlank()
                ? "DINNER"
                : request.getMealType().trim().toUpperCase());
        recipe.setMarketRegion(request.getMarketRegion());
        recipe.setLanguage(request.getLanguage());
        recipe.setServingCount(request.getServingCount() == null ? 1 : request.getServingCount());
        recipe.setTotalYieldGrams(100.0);
        recipe.setDefaultServingGrams(100.0);
        recipe.setIngredients(List.of());
        return recipe;
    }

    private List<AiRecipeIngredientSuggestionDto> sampleIngredients(AiRecipeDraftRequestDto request) {
        List<String> names = request.getAvailableIngredients() == null || request.getAvailableIngredients().isEmpty()
                ? List.of("Chicken breast")
                : request.getAvailableIngredients().stream().limit(5).toList();
        return names.stream().map(name -> {
            AiRecipeIngredientSuggestionDto item = new AiRecipeIngredientSuggestionDto();
            item.setName(name);
            item.setPortionSize(100.0);
            item.setPortionUnit(FoodPortionUnit.GRAM);
            item.setReviewRequired(true);
            item.setMatchReason("LOG_PROVIDER_SAMPLE");
            item.setConfidence(0.3);
            return item;
        }).toList();
    }

    private String resolveRecipeName(AiRecipeDraftRequestDto request) {
        if (request.getPrompt() == null || request.getPrompt().isBlank()) {
            return "AI recipe draft";
        }
        String normalized = request.getPrompt().trim().replaceAll("\\s+", " ");
        return normalized.length() > 120 ? normalized.substring(0, 120) : normalized;
    }
}
