import { lazy, Suspense, useMemo, useState } from "react";
import { PageResponse } from "../api";
import { EmptyState, Panel, SectionToolbar } from "../AdminPrimitives";
import { useAdminLocale } from "../admin/locale";
import { SectionKey, canViewSection } from "../admin/navigation";
import { combineStates, formatValue, percent, useEndpoint } from "../admin/shared";
import { AdminAccessProfile, DashboardGrowth, DashboardSummary, GrowthFunnelStep, Notification, RevenueCatMonitoringCharts, SystemReliabilityAnalytics } from "../types";

export const GrowthTrendChart = lazy(() => import("../GrowthTrendChart").then((module) => ({ default: module.GrowthTrendChart })));
const SubscriptionMixChart = lazy(() => import("../DashboardInsightCharts").then((module) => ({ default: module.SubscriptionMixChart })));
const AiOutcomeChart = lazy(() => import("../DashboardInsightCharts").then((module) => ({ default: module.AiOutcomeChart })));
const CatalogPipelineChart = lazy(() => import("../DashboardInsightCharts").then((module) => ({ default: module.CatalogPipelineChart })));
const WorkloadChart = lazy(() => import("../DashboardInsightCharts").then((module) => ({ default: module.WorkloadChart })));
const RevenuePulseChart = lazy(() => import("../DashboardInsightCharts").then((module) => ({ default: module.RevenuePulseChart })));
const RetentionPulseChart = lazy(() => import("../DashboardInsightCharts").then((module) => ({ default: module.RetentionPulseChart })));
const ReliabilityPulseChart = lazy(() => import("../DashboardInsightCharts").then((module) => ({ default: module.ReliabilityPulseChart })));

const pulseCopy={
  tr:{revenue:"Gelir eğilimi",revenueHelp:"RevenueCat tarafından döndürülen son 28 günlük gelir veya MRR hareketi.",retention:"Kullanıcı devamlılığı",retentionHelp:"30 günlük aktif kapsam ve uzun süre pasif kalan hesapların oranı.",reliability:"API güvenilirliği",reliabilityHelp:"Son 24 saatte 5xx hata oranı ve p95 yanıt süresi.",emptyRevenue:"RevenueCat henüz çizilebilir gelir verisi döndürmedi.",emptyReliability:"Son 24 saat için güvenilirlik eğrisi bulunmuyor."},
  en:{revenue:"Revenue trend",revenueHelp:"Revenue or MRR movement returned by RevenueCat for the last 28 days.",retention:"User continuity",retentionHelp:"30-day active coverage and the share of long-inactive accounts.",reliability:"API reliability",reliabilityHelp:"5xx error rate and p95 response time over the last 24 hours.",emptyRevenue:"RevenueCat has not returned drawable revenue data yet.",emptyReliability:"No reliability trend is available for the last 24 hours."}
} as const;

const copy = {
  tr: { title:"Genel bakış", description:"Büyüme, gelir, katalog, AI ve operasyonların tek ekrandaki yönetim özeti.", range:"Raporlama aralığı", days:"gün", users:"Toplam kullanıcı", usersHint:"Kayıtlı hesaplar", subscriptions:"Aktif abonelik", subscriptionsHint:(n:number)=>`Kullanıcıların %${n}'i ücretli planda`, catalog:"Katalog hazır olma", catalogHint:(a:string,b:string)=>`${a} / ${b} ürün doğrulandı`, work:"Bekleyen işler", workHint:"İnceleme ve owner kararı bekleyen kayıtlar", trend:"Kullanıcı büyümesi", trendHelp:"Yeni kayıtlar ve aktif kullanıcılar aynı tarih aralığında.", noTrend:"Bu tarih aralığında grafik verisi bulunmuyor.", health:"Operasyon durumu", healthHelp:"Kritik bildirim, sağlayıcı olayı ve ürün kuyruğu kontrolleri.", stable:"Tüm kontroller sağlıklı", attention:"İnceleme gerekli", healthScore:"kontrol sağlıklı", failedEvents:"Başarısız sağlayıcı olayı", priorities:"Öncelikli işler", prioritiesHelp:"Bugün karar verilmesi gereken kuyruklar.", open:"Aç", details:"Detayları aç", productReview:"Ürün inceleme", recipeReview:"Tarif onayları", aiRefunds:"AI kota iadeleri", alerts:"Kritik bildirimler", noWork:"Bekleyen kritik iş yok.", activation:"Aktivasyon hunisi", activationHelp:"Kayıttan temel ürün kullanımına ilerleme.", noFunnel:"Aktivasyon verisi bulunmuyor.", subscriptionMix:"Abonelik yapısı", subscriptionMixHelp:"Aktif planlar ve iptal hacminin dağılımı.", catalogFlow:"Katalog işleme hattı", catalogFlowHelp:"Ürünlerin doğrulama ve inceleme aşamalarındaki dağılımı.", aiOutcomes:"AI sonuçları", aiOutcomesHelp:"Son 7 gündeki isteklerin sonuç dağılımı.", workload:"Operasyon iş yükü", workloadHelp:"Ekip kararını bekleyen açık kayıtların alanlara göre dağılımı.", partial:"Kısmi veri", coverage:"kayıt geçmişi kapsamı", connector:"–" },
  en: { title:"Overview", description:"A single management view of growth, revenue, catalog, AI and operations.", range:"Reporting range", days:"days", users:"Total users", usersHint:"Registered accounts", subscriptions:"Active subscriptions", subscriptionsHint:(n:number)=>`${n}% of users are on a paid plan`, catalog:"Catalog readiness", catalogHint:(a:string,b:string)=>`${a} of ${b} products verified`, work:"Pending work", workHint:"Items awaiting review or an owner decision", trend:"User growth", trendHelp:"Registrations and active users across the same reporting period.", noTrend:"No chart data is available for this period.", health:"Operational status", healthHelp:"Critical alert, provider event and product queue checks.", stable:"All checks healthy", attention:"Review required", healthScore:"checks healthy", failedEvents:"Failed provider events", priorities:"Priority work", prioritiesHelp:"Queues requiring a decision today.", open:"Open", details:"Open details", productReview:"Product review", recipeReview:"Recipe approvals", aiRefunds:"AI quota refunds", alerts:"Critical alerts", noWork:"No critical work is waiting.", activation:"Activation funnel", activationHelp:"Progress from registration to core product use.", noFunnel:"No activation data is available.", subscriptionMix:"Subscription mix", subscriptionMixHelp:"Distribution of active plans and cancellation volume.", catalogFlow:"Catalog pipeline", catalogFlowHelp:"Products across verification and review stages.", aiOutcomes:"AI outcomes", aiOutcomesHelp:"Result distribution for requests in the last 7 days.", workload:"Operational workload", workloadHelp:"Open records awaiting a team decision by area.", partial:"Partial data", coverage:"registration history coverage", connector:"to" }
} as const;

export function dublinDateRange(days:number) {
  const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Dublin",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());
  const values=Object.fromEntries(parts.map(part=>[part.type,part.value])); const to=`${values.year}-${values.month}-${values.day}`;
  const fromDate=new Date(`${to}T00:00:00Z`); fromDate.setUTCDate(fromDate.getUTCDate()-(days-1)); return {from:fromDate.toISOString().slice(0,10),to};
}

function SummaryMetric({label,value,hint,tone="default"}:{label:string;value:string;hint:string;tone?:"default"|"good"|"warn"}) {
  return <article className={`dashboard-summary-card ${tone}`}><span>{label}</span><strong>{value}</strong><small>{hint}</small></article>;
}
function precisePercent(value?:number,total?:number) {
  if(!value||!total) return "0";
  const result=(value/total)*100;
  return result<1?result.toFixed(1):Math.round(result).toString();
}
function funnelLabel(step:GrowthFunnelStep,locale:"tr"|"en") {
  if(locale==="en") return step.label;
  const labels:Record<string,string>={REGISTERED:"Kayıt olan",EMAIL_VERIFIED:"E-postasını doğrulayan",ONBOARDING_COMPLETED:"Kurulumu tamamlayan",FIRST_FOOD_LOG:"İlk öğününü kaydeden",PAYWALL_VIEWED:"Paketleri görüntüleyen",SUBSCRIPTION_STARTED:"Abonelik başlatan"};
  return labels[step.key]??step.label;
}
function ActivationFunnel({steps,locale,onNavigate}:{steps:GrowthFunnelStep[];locale:"tr"|"en";onNavigate:(key:SectionKey)=>void}) {
  const t=copy[locale]; return <div className="dashboard-funnel">{steps.slice(0,5).map(step=><button key={step.key} type="button" disabled={!step.targetSection} onClick={()=>step.targetSection&&onNavigate(step.targetSection as SectionKey)}><div><span>{funnelLabel(step,locale)}</span><strong>{formatValue(step.users)}</strong></div><div className="dashboard-funnel-track"><i style={{width:`${Math.min(100,Math.max(0,step.conversionFromRegistrationPercent))}%`}} /></div><small>%{step.conversionFromRegistrationPercent.toFixed(1)}{step.dataStatus==="PARTIAL"?` · ${t.partial}`:""}</small></button>)}</div>;
}

export function DashboardView({accessProfile,onError,onNavigate}:{accessProfile:AdminAccessProfile|null;onError:(message:string|null)=>void;onNavigate:(section:SectionKey)=>void}) {
  const {locale}=useAdminLocale(); const t=copy[locale], pulse=pulseCopy[locale];
  const canUsers=Boolean(accessProfile?.permissions?.includes("USERS_READ")), canCatalog=Boolean(accessProfile?.permissions?.includes("CATALOG_READ")), canGrowth=Boolean(accessProfile?.permissions?.includes("GROWTH_READ")), canFinance=Boolean(accessProfile?.permissions?.includes("FINANCE_READ")), canSystem=Boolean(accessProfile?.permissions?.includes("TECHNICAL_READ"));
  const [growthRange,setGrowthRange]=useState<7|30|90>(30); const dates=useMemo(()=>dublinDateRange(growthRange),[growthRange]);
  const {data,state,reload}=useEndpoint<DashboardSummary>("/api/v1/admin/dashboard/summary",onError);
  const {data:growth,state:growthState,reload:reloadGrowth}=useEndpoint<DashboardGrowth>(`/api/v1/admin/dashboard/growth?from=${dates.from}&to=${dates.to}&timeZone=Europe%2FDublin`,onError,canGrowth);
  const {data:notifications,state:notificationState,reload:reloadNotifications}=useEndpoint<PageResponse<Notification>>("/api/v1/notifications?unreadOnly=true&severity=CRITICAL&page=0&size=5",onError,canGrowth);
  const {data:revenue,state:revenueState,reload:reloadRevenue}=useEndpoint<RevenueCatMonitoringCharts>("/api/v1/admin/revenuecat/monitoring/charts?environment=production&range=28d",onError,canFinance);
  const {data:reliability,state:reliabilityState,reload:reloadReliability}=useEndpoint<SystemReliabilityAnalytics>("/api/v1/admin/system/operations/reliability-analytics?windowHours=24",onError,canSystem);
  const totalUsers=data?.totalUsers??0, activeSubscriptions=(data?.activePlusSubscriptions??0)+(data?.activeProSubscriptions??0), paidRatio=percent(activeSubscriptions,totalUsers), catalogReady=precisePercent(data?.verifiedProducts,data?.totalProducts), catalogReadyNumber=Number(catalogReady);
  const productQueue=data?.reviewQueueProducts??0, recipeQueue=(data?.pendingRecipeApprovals??0)+(data?.pendingRecipeImportCandidates??0), aiRefundQueue=data?.refundableAiRequests??0, criticalAlerts=notifications?.totalElements??notifications?.content?.length??0, failedEvents=data?.failedSubscriptionProviderEvents??0;
  const pendingWork=(canCatalog?productQueue+recipeQueue:0)+(canFinance?aiRefundQueue:0)+(canGrowth?criticalAlerts:0);
  const operationalChecks=[canGrowth&&criticalAlerts===0,canFinance&&failedEvents===0,canCatalog&&productQueue<=20].filter((check):check is boolean=>typeof check==="boolean");
  const healthyChecks=operationalChecks.filter(Boolean).length, healthScore=operationalChecks.length?Math.round((healthyChecks/operationalChecks.length)*100):100, healthGood=healthyChecks===operationalChecks.length;
  const growthKpi=(key:string)=>growth?.kpis?.find(item=>item.key===key)?.value??0, mau=growthKpi("MAU"), inactiveUsers=growthKpi("INACTIVE_USERS"), activeCoverage=totalUsers?Math.min(100,(mau/totalUsers)*100):0, inactiveRate=totalUsers?Math.min(100,(inactiveUsers/totalUsers)*100):0;
  const revenueChart=revenue?.charts?.find(chart=>chart.chartName==="revenue"&&chart.points?.length)||revenue?.charts?.find(chart=>chart.chartName==="mrr"&&chart.points?.length);
  const priorities=[canGrowth&&{label:t.alerts,value:criticalAlerts,target:"notifications" as SectionKey,danger:criticalAlerts>0},canFinance&&{label:t.failedEvents,value:failedEvents,target:"subscriptionEvents" as SectionKey,danger:failedEvents>0},canCatalog&&{label:t.productReview,value:productQueue,target:"products" as SectionKey,danger:productQueue>20},canCatalog&&{label:t.recipeReview,value:recipeQueue,target:"recipes" as SectionKey,danger:false},canFinance&&{label:t.aiRefunds,value:aiRefundQueue,target:"ai" as SectionKey,danger:false}].filter(Boolean).filter(item=>item&&item.value>0).slice(0,4) as Array<{label:string;value:number;target:SectionKey;danger:boolean}>;
  return <div className="stack dashboard-overview">
    <SectionToolbar title={t.title} description={t.description} state={combineStates([state,growthState,notificationState,revenueState,reliabilityState])} onReload={()=>{void reload();void reloadGrowth();void reloadNotifications();void reloadRevenue();void reloadReliability();}}>{canGrowth&&<div className="segmented-control dashboard-range" aria-label={t.range}>{([7, 30, 90] as const).map(days=><button className={growthRange===days?"active":""} key={days} onClick={()=>setGrowthRange(days)} type="button">{days} {t.days}</button>)}</div>}</SectionToolbar>
    <section className="dashboard-summary-grid" aria-label={t.title}>{canUsers&&<SummaryMetric label={t.users} value={formatValue(totalUsers)} hint={t.usersHint}/>} {canFinance&&<SummaryMetric label={t.subscriptions} value={formatValue(activeSubscriptions)} hint={t.subscriptionsHint(paidRatio)} tone="good"/>} {canCatalog&&<SummaryMetric label={t.catalog} value={`${catalogReady}%`} hint={t.catalogHint(formatValue(data?.verifiedProducts),formatValue(data?.totalProducts))} tone={catalogReadyNumber>=80?"good":"warn"}/>} <SummaryMetric label={t.work} value={formatValue(pendingWork)} hint={t.workHint} tone={pendingWork>0?"warn":"good"}/></section>
    {canGrowth&&<div className="dashboard-main-grid"><Panel title={t.trend} description={t.trendHelp} actions={<button className="dashboard-panel-link" type="button" onClick={()=>onNavigate("users")}>{t.details} →</button>} className="dashboard-trend-panel"><div className="dashboard-chart-meta"><span>{growth?.from??dates.from} {t.connector} {growth?.to??dates.to}</span><span>{growth?.registrationCoveragePercent.toFixed(1)??"0.0"}% {t.coverage}</span></div>{growth?.daily?.length?<Suspense fallback={<div className="admin-chart-loading">…</div>}><GrowthTrendChart points={growth.daily} locale={locale}/></Suspense>:<EmptyState message={t.noTrend}/>}</Panel><Panel title={t.health} description={t.healthHelp} actions={<button className="dashboard-panel-link" type="button" onClick={()=>onNavigate("system")}>{t.details} →</button>} className="dashboard-health-panel"><div className="dashboard-health-content"><div className="dashboard-health-ring" style={{"--health-score":`${healthScore*3.6}deg`} as React.CSSProperties}><div><strong>{healthyChecks}/{operationalChecks.length}</strong><span>{t.healthScore}</span></div></div><strong className={healthGood?"dashboard-health-label good":"dashboard-health-label warn"}>{healthGood?t.stable:t.attention}</strong></div></Panel></div>}
    <Suspense fallback={<div className="admin-chart-loading dashboard-chart-loading">…</div>}><section className="dashboard-insight-grid">
      {canFinance&&<Panel title={t.subscriptionMix} description={t.subscriptionMixHelp} actions={<button className="dashboard-panel-link" type="button" onClick={()=>onNavigate("subscriptions")}>{t.details} →</button>}><SubscriptionMixChart plus={data?.activePlusSubscriptions??0} pro={data?.activeProSubscriptions??0} canceled={data?.canceledSubscriptions??0} locale={locale}/></Panel>}
      {canCatalog&&<Panel title={t.catalogFlow} description={t.catalogFlowHelp} actions={<button className="dashboard-panel-link" type="button" onClick={()=>onNavigate("foodOps")}>{t.details} →</button>}><CatalogPipelineChart verified={data?.verifiedProducts??0} raw={data?.rawImportedProducts??0} review={data?.needsReviewProducts??0} rejected={data?.rejectedProducts??0} locale={locale}/></Panel>}
      {canGrowth&&<Panel title={t.aiOutcomes} description={t.aiOutcomesHelp} actions={<button className="dashboard-panel-link" type="button" onClick={()=>onNavigate("ai")}>{t.details} →</button>}><AiOutcomeChart confirmed={data?.aiConfirmedLast7Days??0} rejected={data?.aiRejectedLast7Days??0} failed={data?.aiFailedLast7Days??0} total={data?.aiRequestsLast7Days??0} locale={locale}/></Panel>}
      <Panel title={t.workload} description={t.workloadHelp} actions={<button className="dashboard-panel-link" type="button" onClick={()=>onNavigate("notifications")}>{t.details} →</button>}><WorkloadChart product={canCatalog?productQueue:0} recipe={canCatalog?recipeQueue:0} ai={canFinance?aiRefundQueue:0} alerts={canGrowth?criticalAlerts:0} locale={locale}/></Panel>
    </section></Suspense>
    <Suspense fallback={<div className="admin-chart-loading dashboard-chart-loading">…</div>}><section className="dashboard-pulse-grid">
      {canFinance&&<Panel title={pulse.revenue} description={pulse.revenueHelp} actions={<button className="dashboard-panel-link" type="button" onClick={()=>onNavigate("revenueCatProduction")}>{t.details} →</button>}>{revenueChart?.points?.length?<RevenuePulseChart points={revenueChart.points} locale={locale}/>:<EmptyState message={pulse.emptyRevenue}/>}</Panel>}
      {canGrowth&&<Panel title={pulse.retention} description={pulse.retentionHelp} actions={<button className="dashboard-panel-link" type="button" onClick={()=>onNavigate("engagement")}>{t.details} →</button>}><RetentionPulseChart activeRate={activeCoverage} inactiveRate={inactiveRate} locale={locale}/></Panel>}
      {canSystem&&<Panel title={pulse.reliability} description={pulse.reliabilityHelp} actions={<button className="dashboard-panel-link" type="button" onClick={()=>onNavigate("systemProduction")}>{t.details} →</button>}>{reliability?.apiTrend?.length?<ReliabilityPulseChart points={reliability.apiTrend} locale={locale}/>:<EmptyState message={pulse.emptyReliability}/>}</Panel>}
    </section></Suspense>
    <div className="dashboard-secondary-grid"><Panel title={t.priorities} description={t.prioritiesHelp}>{priorities.length?<div className="dashboard-priority-list">{priorities.filter(item=>canViewSection(accessProfile,item.target)).map(item=><button key={item.target} type="button" onClick={()=>onNavigate(item.target)}><span className={item.danger?"danger":"neutral"}>{item.value}</span><strong>{item.label}</strong><small>{t.open} →</small></button>)}</div>:<EmptyState message={t.noWork}/>}</Panel>{canGrowth&&<Panel title={t.activation} description={t.activationHelp}>{growth?.funnel?.length?<ActivationFunnel steps={growth.funnel} locale={locale} onNavigate={onNavigate}/>:<EmptyState message={t.noFunnel}/>}</Panel>}</div>
  </div>;
}
