import { lazy, Suspense, useMemo, useState } from "react";
import { AdminEngagementAnalytics } from "../types";
import { CollapsiblePanel, DataTable, EmptyState, MetricCard, Panel, SectionToolbar } from "../AdminPrimitives";
import { useAdminLocale } from "../admin/locale";
import { MARKET_REGIONS, PLAN_ORDER, PREFERRED_LANGUAGES, formatDurationMs, formatValue, humanizeFeature, useEndpoint } from "./../admin/shared";

export const OnboardingFunnelChart = lazy(() => import("../EngagementCharts").then(m => ({ default: m.OnboardingFunnelChart })));
export const FeatureAdoptionChart = lazy(() => import("../EngagementCharts").then(m => ({ default: m.FeatureAdoptionChart })));
export const CoreFlowComparisonChart = lazy(() => import("../EngagementCharts").then(m => ({ default: m.CoreFlowComparisonChart })));

export function EngagementAnalyticsView({ onError }: { onError: (message: string | null) => void }) {
  const { locale } = useAdminLocale(); const tr=locale==="tr";
  const [hours,setHours]=useState(168), [region,setRegion]=useState(""), [language,setLanguage]=useState(""), [plan,setPlan]=useState(""), [filtersOpen,setFiltersOpen]=useState(false);
  const path=useMemo(()=>{const p=new URLSearchParams({hours:String(hours)});if(region)p.set("region",region);if(language)p.set("language",language);if(plan)p.set("plan",plan);return `/api/v1/admin/engagement/analytics?${p}`;},[hours,region,language,plan]);
  const {data,state,reload}=useEndpoint<AdminEngagementAnalytics>(path,onError); const onboarding=data?.onboarding, search=data?.search, food=data?.foodLogging, barcode=data?.barcode;
  const onboardingFunnelItems=[{label:tr?"Başladı":"Started",value:onboarding?.started??0},{label:tr?"Önizledi":"Previewed",value:onboarding?.previewed??0},{label:tr?"Tamamladı":"Completed",value:onboarding?.completed??0}];
  const featureAdoptionItems=(data?.featureAdoption??[]).map(x=>({events:x.events??0,label:humanizeFeature(x.feature),users:x.uniqueUsers??0}));
  const coreFlowItems=[{label:tr?"Yemek kaydı":"Food log",started:food?.started??0,completed:food?.completed??0,failed:food?.failed??0},{label:tr?"Barkod":"Barcode",started:barcode?.started??0,completed:barcode?.completed??0,failed:barcode?.failed??0}];
  const scope=[region,language,plan].filter(Boolean).join(" · ")||(tr?"Tüm segmentler":"All segments");
  return <div className="stack engagement-analytics">
    <SectionToolbar title={tr?"Ürün etkileşimi":"Product engagement"} description={tr?"İlk kurulumdan düzenli kullanıma uzanan davranış akışını izleyin.":"Follow behavior from first setup to repeat product value."} state={state} onReload={reload}><span className="status-pill">Contract v{formatValue(data?.eventContractVersion??1)}</span></SectionToolbar>
    <CollapsiblePanel className="engagement-filter-panel" title={tr?"Etkileşim filtreleri":"Engagement filters"} description={tr?"Dönem ve kullanıcı segmentine göre tüm analizi güncelleyin.":"Update the full analysis by period and user segment."} open={filtersOpen} onToggle={()=>setFiltersOpen(v=>!v)}>
      <div className="engagement-filter-summary"><span>{tr?"Aktif kapsam":"Active scope"}</span><strong>{hours/24} {tr?"gün":"days"} · {scope}</strong></div>
      <div className="engagement-filter-grid"><label>{tr?"Dönem":"Window"}<select value={hours} onChange={e=>setHours(Number(e.target.value))}><option value={24}>24 {tr?"saat":"hours"}</option><option value={168}>7 {tr?"gün":"days"}</option><option value={720}>30 {tr?"gün":"days"}</option><option value={2160}>90 {tr?"gün":"days"}</option></select></label><label>{tr?"Bölge":"Region"}<select value={region} onChange={e=>setRegion(e.target.value)}><option value="">{tr?"Tüm bölgeler":"All regions"}</option>{MARKET_REGIONS.map(x=><option key={x}>{x}</option>)}</select></label><label>{tr?"Dil":"Language"}<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="">{tr?"Tüm diller":"All languages"}</option>{PREFERRED_LANGUAGES.map(x=><option key={x}>{x}</option>)}</select></label><label>{tr?"Mevcut plan":"Current plan"}<select value={plan} onChange={e=>setPlan(e.target.value)}><option value="">{tr?"Tüm planlar":"All plans"}</option>{PLAN_ORDER.map(x=><option key={x}>{x}</option>)}</select></label></div>
      <div className="engagement-filter-footer"><p>{tr?"Filtreler backend üzerinde uygulanır; anonim arama telemetrisi plan filtresinden etkilenmez.":"Filters run on the backend; anonymous search telemetry is unaffected by plan."}</p><button type="button" className="ghost-button" onClick={()=>{setHours(168);setRegion("");setLanguage("");setPlan("");}}>{tr?"Filtreleri temizle":"Clear filters"}</button></div>
    </CollapsiblePanel>
    <div className="review-workspace-summary engagement-kpi-grid"><MetricCard label={tr?"Onboarding tamamlama":"Onboarding completion"} value={`${formatValue(onboarding?.completionRate)}%`} hint={`${formatValue(onboarding?.completed)} / ${formatValue(onboarding?.started)}`} /><MetricCard label={tr?"Arama seçimi":"Search selection"} value={`${formatValue(search?.selectionRate?search.selectionRate*100:0)}%`} hint={`${formatValue(search?.selectedSearches)} ${tr?"seçilen arama":"selected searches"}`} /><MetricCard label={tr?"Sonuçsız arama":"Zero-result rate"} value={`${formatValue(search?.zeroResultRate?search.zeroResultRate*100:0)}%`} hint={`${formatValue(search?.zeroResultSearches)} ${tr?"arama ilgi bekliyor":"searches need attention"}`} /><MetricCard label={tr?"Barkod tamamlama":"Barcode completion"} value={`${formatValue(barcode?.completionRate)}%`} hint={`${formatValue(barcode?.completed)} / ${formatValue(barcode?.failed)}`} /></div>
    <div className="ops-grid engagement-flow-grid"><Panel title={tr?"Onboarding hunisi":"Onboarding funnel"} description={tr?"Kurulum yolculuğundaki ilerleme.":"Progress through the setup journey."}>{onboardingFunnelItems.some(x=>x.value>0)?<Suspense fallback={<div className="admin-chart-loading">Loading…</div>}><OnboardingFunnelChart items={onboardingFunnelItems}/></Suspense>:<EmptyState title={tr?"Onboarding etkinliği yok":"No onboarding activity"} message={tr?"Bu kapsamda yolculuk olayı yok.":"No journey event was recorded."}/>}<div className="engagement-inline-metrics"><span>{tr?"Adım görüntüleme":"Step views"}<strong>{formatValue(onboarding?.stepViewed)}</strong></span><span>{tr?"Adım hatası":"Step failures"}<strong>{formatValue(onboarding?.stepFailed)}</strong></span><span>{tr?"Devam eden":"Resumed"}<strong>{formatValue(onboarding?.resumed)}</strong></span><span>{tr?"Ort. süre":"Avg. duration"}<strong>{formatDurationMs(onboarding?.averageCompletionDurationMs)}</strong></span></div></Panel>
      <Panel title={tr?"Temel kayıt akışları":"Core logging flows"} description={tr?"Başlangıç, tamamlama ve hatayı karşılaştırın.":"Compare starts, completions and failures."}><Suspense fallback={<div className="admin-chart-loading">Loading…</div>}><CoreFlowComparisonChart items={coreFlowItems} tr={tr}/></Suspense><div className="engagement-flow-cards"><span><strong>{tr?"Yemek kaydı":"Food log"}</strong>{formatValue(food?.completionRate)}% · {formatDurationMs(food?.averageDurationMs)}</span><span><strong>{tr?"Barkod":"Barcode"}</strong>{formatValue(barcode?.completionRate)}% · {formatDurationMs(barcode?.averageDurationMs)}</span></div></Panel></div>
    <Panel title={tr?"Özellik benimseme":"Feature adoption"} description={tr?"Kullanıcı ve tekrar kullanım üreten özellikler.":"Capabilities that create users and repeat usage."}>{featureAdoptionItems.some(x=>x.events>0||x.users>0)?<Suspense fallback={<div className="admin-chart-loading">Loading…</div>}><FeatureAdoptionChart items={featureAdoptionItems}/></Suspense>:<EmptyState title={tr?"Kullanım etkinliği yok":"No adoption activity"} message={tr?"Bu kapsamda özellik kullanımı yok.":"No feature usage was recorded."}/>}<details className="engagement-detail-table"><summary>{tr?"Kesin değerleri göster":"Show exact values"}</summary><DataTable columns={tr?["Özellik","Olay","Kullanıcı","Tekrar","Ort. süre"]:["Feature","Events","Users","Repeat events","Avg. duration"]} rows={(data?.featureAdoption??[]).map(x=>[humanizeFeature(x.feature),formatValue(x.events),formatValue(x.uniqueUsers),formatValue(x.repeatEvents),formatDurationMs(x.averageDurationMs)])} empty={tr?"Özellik olayı bulunamadı.":"No feature adoption events returned."}/></details></Panel>
    <div className="ops-grid engagement-lower-grid"><Panel title={tr?"Sonuçsız aramalar":"Zero-result searches"}><DataTable columns={tr?["Gizlilik güvenli sorgu","Arama"]:["Privacy-safe query","Searches"]} rows={(search?.topZeroResultQueries??[]).map(x=>[x.query||"-",formatValue(x.searches)])} empty={tr?"Sonuçsız sorgu yok.":"No zero-result query in this window."}/></Panel><Panel title={tr?"Segment karşılaştırması":"Segment comparison"}><DataTable columns={tr?["Boyut","Segment","Olay","Kullanıcı"]:["Dimension","Segment","Events","Users"]} rows={[...(data?.regionComparison??[]).map(x=>[tr?"Bölge":"Region",x.segment||"-",formatValue(x.events),formatValue(x.uniqueUsers)]),...(data?.languageComparison??[]).map(x=>[tr?"Dil":"Language",x.segment||"-",formatValue(x.events),formatValue(x.uniqueUsers)]),...(data?.planComparison??[]).map(x=>[tr?"Plan":"Current plan",x.segment||"-",formatValue(x.events),formatValue(x.uniqueUsers)])]} empty={tr?"Segment verisi yok.":"No segment analytics returned."}/></Panel></div>
  </div>;
}
