import { FormEvent, useEffect, useRef, useState } from "react";
import { request, formatRequestError } from "../api";
import { useAdminLocale } from "../admin/locale";
import { AdminTargetContext, DatePickerButton } from "../admin/shared";
import { useDialogAccessibility } from "../AdminPrimitives";

type Event = { id: number; occurredAt: string; status?: number; source: "BACKEND"|"PROXY"|"ADMIN_WEB"|"MOBILE"; clientPlatform?: string; appVersion?: string; method: string; route: string; correlationId?: string; errorCode?: string; exceptionType?: string; technicalLocation?: string; durationMs: number };
type EventPage = { content: Event[]; totalElements: number; totalPages: number; page: number; size: number };
type Health = { queued: number; saved: number; dropped: number; writeFailures: number; lastSaved?: string; lastFailure?: string; retentionDays: number; maxRows: number };
type ErrorGroup = { fingerprint: string; source: Event["source"]; status?: number; method: string; route: string; errorCode?: string; occurrenceCount: number; firstOccurredAt: string; lastOccurredAt: string; maxDurationMs: number; affectedVersions: number; lifecycleStatus: "NEW"|"INVESTIGATING"|"RESOLVED"|"REOPENED"; reason?: string; updatedBy?: string; updatedAt?: string };
const initialFilters = () => ({ from: "", to: "", status: "", statusClass: "", source: "", method: "", route: "", correlationId: new URLSearchParams(window.location.search).get("correlationId")?.slice(0,128) ?? "", errorCode: "" });
const statusDescriptions: Record<number, [string, string]> = {
  400: ["İstek kabul edilmedi.", "The request was rejected."],
  401: ["Kimlik doğrulama gerekli.", "Authentication is required."],
  403: ["Bu işleme erişim reddedildi.", "Access to this operation was denied."],
  404: ["İstenen kaynak bulunamadı.", "The requested resource was not found."],
  409: ["İşlem mevcut durumla çakışıyor.", "The operation conflicts with the current state."],
  422: ["İstek işlenemedi; doğrulama veya iş kuralları kontrol edilmeli.", "The request could not be processed; check validation or business rules."],
  429: ["İstek sınırı aşıldı.", "The request limit was exceeded."],
  500: ["Sunucu isteği tamamlayamadı.", "The server could not complete the request."],
  502: ["Backend bir ağ geçidi hatası döndürdü.", "The backend returned a gateway error."],
  503: ["Backend hizmetin kullanılamadığını bildirdi.", "The backend reported the service as unavailable."],
  504: ["Backend bir ağ geçidi zaman aşımı bildirdi.", "The backend reported a gateway timeout."]
};
const words = {
  tr: { title: "İstek hata geçmişi", scope: "Backend yanıtları, doğrulanmış proxy 502/503/504 olayları ve yanıtsız admin istemci istekleri kaynakları ayrılarak gösterilir. Mobil istemci gönderim sözleşmesi hazırdır; mobil uygulama bağlantısı ayrıca tamamlanacaktır.", privacy: "Ham mesaj, istek/yanıt gövdesi, kimlik bilgisi ve kullanıcı değerleri saklanmaz. Query değerleri atılır; dinamik rota parçaları istemcide maskelenir. Teknik konum yalnız backend olaylarında bulunur.", from: "Başlangıç", to: "Bitiş", status: "HTTP kodu", statusClass: "Hata grubu", source: "Kaynak", method: "Yöntem", route: "Rota şablonu (tam eşleşme)", correlationId: "Correlation ID", errorCode: "Hata kodu", apply: "Filtrele", reset: "Temizle", refresh: "Yenile", all: "Tümü", loading: "Yükleniyor…", empty: "Bu filtrelerle kayıt bulunamadı.", total: "Eşleşen kayıt", queued: "Kuyrukta", dropped: "Kaydedilemeyen", failures: "Yazma/temizlik hatası", healthNote: "Kuyruk ve sayaçlar bu uygulama sürecine aittir; yeniden başlatmada sıfırlanır. Kuyruk kalıcı değildir. Kaydedilmiş olaylar veritabanında tutulur.", retention: "Saklama", days: "gün", limit: "satır hedefi (kademeli temizlik)", pending: "Toplama durumu alınamadı", time: "Zaman", duration: "Süre", detail: "Detay", previous: "Önceki", next: "Sonraki", close: "Detayı kapat", location: "Teknik konum", exception: "Hata türü", missing: "Kaydedilmedi", summary: "Bu sayfadaki dağılım", groups: "Tekrarlanan hata grupları", occurrences: "Tekrar", firstSeen: "İlk görülme", lastSeen: "Son görülme", versions: "Sürüm", range: "Tarih seçilmezse son 7 gün gösterilir. Tarihler yerel saat dilimindedir.", invalidDate: "Başlangıç tarihi bitişten sonra olamaz.", loss: "Kayıt hattında kayıp veya yazma hatası var. Bu geçmişin eksiksiz olduğunu varsaymayın.", client: "İstemci / 4xx", server: "Backend / proxy 5xx", lastSaved: "Son kayıt", lastFailure: "Son yazma hatası", rowsPerPage: "Sayfa başına", workflow: "İş akışı", actionReason: "İşlem gerekçesi", cancel: "Vazgeç", applyMfa: "MFA ile uygula" },
  en: { title: "Request error history", scope: "Backend responses, authenticated proxy 502/503/504 events and unanswered admin-client requests are shown as separate sources. The mobile ingestion contract is ready; mobile application wiring remains separate.", privacy: "Raw messages, request/response bodies, credentials and user values are not stored. Query values are discarded and dynamic route segments are masked by the client. Technical locations exist only for backend events.", from: "From", to: "To", status: "HTTP status", statusClass: "Status group", source: "Source", method: "Method", route: "Route template (exact match)", correlationId: "Correlation ID", errorCode: "Error code", apply: "Apply filters", reset: "Clear", refresh: "Refresh", all: "All", loading: "Loading…", empty: "No records match these filters.", total: "Matching records", queued: "Queued", dropped: "Not recorded", failures: "Write/cleanup failures", healthNote: "Queue and counters belong to this process and reset on restart. The queue is not durable. Written events are stored in the database.", retention: "Retention", days: "days", limit: "row target (incremental cleanup)", pending: "Collection status unavailable", time: "Time", duration: "Duration", detail: "Details", previous: "Previous", next: "Next", close: "Close details", location: "Technical location", exception: "Error type", missing: "Not recorded", summary: "Distribution on this page", groups: "Recurring error groups", occurrences: "Occurrences", firstSeen: "First seen", lastSeen: "Last seen", versions: "Versions", range: "Defaults to the last 7 days. Date inputs use your local time zone.", invalidDate: "From must not be later than To.", loss: "The collection pipeline has dropped records or reported write failures. Do not assume this history is complete.", client: "Client / 4xx", server: "Backend / proxy 5xx", lastSaved: "Last saved", lastFailure: "Last write failure", rowsPerPage: "Rows per page", workflow: "Workflow", actionReason: "Action reason", cancel: "Cancel", applyMfa: "Apply with MFA" }
};
const filterCopy={
  tr:{subtitle:"Yalnızca Owner erişimli istek hatası izleme ve inceleme alanı.",privacySafe:"Yalnızca güvenli teknik meta veri",dateRange:"Tarih aralığı",quickRange:"Hızlı aralık",last24h:"Son 24 saat",last7d:"Son 7 gün",last30d:"Son 30 gün",requestFilters:"İstek filtreleri",advanced:"Gelişmiş filtreler",advancedHint:"Rota, correlation ID veya hata koduyla kesin kayıt arayın.",collector:"Toplayıcı durumu",healthy:"Kayıt hattı sağlıklı"},
  en:{subtitle:"Owner-only request failure monitoring and investigation.",privacySafe:"Privacy-safe technical metadata only",dateRange:"Date range",quickRange:"Quick range",last24h:"Last 24 hours",last7d:"Last 7 days",last30d:"Last 30 days",requestFilters:"Request filters",advanced:"Advanced filters",advancedHint:"Find an exact record by route, correlation ID or error code.",collector:"Collector status",healthy:"Recording pipeline healthy"}
} as const;
const detailCopy={tr:{platform:"İstemci platformu",appVersion:"Uygulama sürümü"},en:{platform:"Client platform",appVersion:"App version"}} as const;
const workflowCopy={
  tr:{INVESTIGATING:"İncelemeye al",RESOLVED:"Çözüldü olarak işaretle",REOPENED:"Yeniden aç"},
  en:{INVESTIGATING:"Start investigation",RESOLVED:"Mark as resolved",REOPENED:"Reopen"}
} as const;

function localDateTimeInput(date:Date){
  const offset=date.getTimezoneOffset()*60_000;
  return new Date(date.getTime()-offset).toISOString().slice(0,16);
}

export function OwnerErrorView({ targetContext, onClearTarget }: { targetContext?: AdminTargetContext | null; onClearTarget?: () => void } = {}) {
  const { locale } = useAdminLocale(); const t = words[locale], fc=filterCopy[locale], dc=detailCopy[locale];
  const [draft, setDraft] = useState(initialFilters);
  const [filters, setFilters] = useState(initialFilters);
  const [page, setPage] = useState(0), [pageSize, setPageSize] = useState(10), [version, setVersion] = useState(0);
  const [data, setData] = useState<EventPage | null>(null), [health, setHealth] = useState<Health | null>(null);
  const [groups, setGroups] = useState<ErrorGroup[]>([]);
  const [groupAction,setGroupAction]=useState<ErrorGroup|null>(null),[groupReason,setGroupReason]=useState(""),[groupBusy,setGroupBusy]=useState(false);
  const [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<number | null>(null), [detail, setDetail] = useState<Event | null>(null), [detailError, setDetailError] = useState<string | null>(null);
  const paginationScrollRef=useRef<number|null>(null);
  const detailDialogRef = useDialogAccessibility<HTMLDivElement>(()=>setSelected(null), selected!==null);
  const workflowDialogRef = useDialogAccessibility<HTMLFormElement>(()=>{if(!groupBusy)setGroupAction(null);}, groupAction!==null);
  const date = (value?: string) => value ? new Intl.DateTimeFormat(locale === "tr" ? "tr-TR" : "en-GB", { dateStyle: "short", timeStyle: "medium" }).format(new Date(value)) : t.missing;
  useEffect(()=>{if(targetContext?.targetType!=="ERROR_GROUP"||!targetContext.targetId)return;const match=groups.find(group=>group.fingerprint===targetContext.targetId);if(match&&groupAction?.fingerprint!==match.fingerprint){setGroupAction(match);setGroupReason("");}},[groups,groupAction?.fingerprint,targetContext?.targetId,targetContext?.targetType]);
  useEffect(() => {
    let cancelled = false;
    const params = new URLSearchParams({ page: String(page), size: String(pageSize) });
    Object.entries(filters).forEach(([key,value]) => { if (value.trim()) params.set(key, key === "from" || key === "to" ? new Date(value).toISOString() : value.trim()); });
    setBusy(true); setError(null); setSelected(null);
    request<EventPage>(`/api/v1/admin/errors?${params}`).then(value => { if(!cancelled)setData(value); }).catch(failure => { if(!cancelled) setError(formatRequestError(failure)); }).finally(() => { if(!cancelled) setBusy(false); });
    return () => { cancelled=true; };
  }, [filters,page,pageSize,version]);
  useEffect(()=>{const scrollTop=paginationScrollRef.current;if(scrollTop===null||!data)return;requestAnimationFrame(()=>requestAnimationFrame(()=>window.scrollTo({top:scrollTop,behavior:"auto"})));paginationScrollRef.current=null;},[data]);
  useEffect(() => {
    let cancelled = false;
    request<Health>("/api/v1/admin/errors/health").then(value => { if(!cancelled) setHealth(value); }).catch(() => { /* Display status unavailable independently from list failures. */ });
    const groupParams=new URLSearchParams({limit:"10"});
    if(filters.from)groupParams.set("from",new Date(filters.from).toISOString()); if(filters.to)groupParams.set("to",new Date(filters.to).toISOString()); if(filters.source)groupParams.set("source",filters.source);
    request<ErrorGroup[]>(`/api/v1/admin/errors/groups?${groupParams}`).then(value=>{if(!cancelled)setGroups(value);}).catch(()=>{if(!cancelled)setGroups([]);});
    return () => { cancelled=true; };
  }, [filters,version]);
  useEffect(() => {
    let cancelled=false; setDetail(null); setDetailError(null);
    if(selected!==null) request<Event>(`/api/v1/admin/errors/${selected}`).then(value => { if(!cancelled) setDetail(value); }).catch(failure => { if(!cancelled) setDetailError(formatRequestError(failure)); });
    return () => { cancelled=true; };
  }, [selected]);
  function apply(event: FormEvent) {
    event.preventDefault();
    if (draft.from && draft.to && new Date(draft.from)>new Date(draft.to)) { setError(t.invalidDate); return; }
    setPage(0); setFilters({...draft});
  }
  function setQuickRange(hours:number){
    const to=new Date(),from=new Date(to.getTime()-hours*60*60*1000);
    const next={...draft,from:localDateTimeInput(from),to:localDateTimeInput(to)};
    setDraft(next); setFilters(next); setPage(0);
  }
  function setDatePart(key:"from"|"to",value:string){setDraft(current=>({...current,[key]:value?`${value}T${current[key].slice(11,16)||(key==="from"?"00:00":"23:59")}`:""}));}
  function setTimePart(key:"from"|"to",value:string){const datePart=draft[key].slice(0,10)||localDateTimeInput(new Date()).slice(0,10);setDraft(current=>({...current,[key]:value?`${datePart}T${value}`:""}));}
  const nextState=(group:ErrorGroup):"INVESTIGATING"|"RESOLVED"|"REOPENED"=>group.lifecycleStatus==="NEW"?"INVESTIGATING":group.lifecycleStatus==="RESOLVED"?"REOPENED":"RESOLVED";
  const workflowAction=(group:ErrorGroup)=>workflowCopy[locale][nextState(group)];
  const changePage=(nextPage:number)=>{paginationScrollRef.current=window.scrollY;setPage(nextPage);};
  const changePageSize=(nextSize:number)=>{paginationScrollRef.current=window.scrollY;setPageSize(nextSize);setPage(0);};
  async function updateGroup(event:FormEvent){event.preventDefault();if(!groupAction||groupReason.trim().length<8)return;setGroupBusy(true);setError(null);try{await request(`/api/v1/admin/errors/groups/${groupAction.fingerprint}/state`,{method:"POST",body:{lifecycleStatus:nextState(groupAction),reason:groupReason.trim(),source:groupAction.source,status:groupAction.status,method:groupAction.method,route:groupAction.route,errorCode:groupAction.errorCode}});setGroupAction(null);setGroupReason("");setVersion(value=>value+1);}catch(failure){setError(formatRequestError(failure));}finally{setGroupBusy(false);}}
  const rows = data?.content ?? [], clientCount = rows.filter(row => row.status==null || row.status<500).length;
  return <div className="stack owner-error-center">
    <header className="section-toolbar error-center-header"><div><div className="section-toolbar-title"><h2>{t.title}</h2><span className="status-pill" title={t.privacy}>{fc.privacySafe}</span></div><p>{fc.subtitle}</p></div><button className="ghost-button" disabled={busy} onClick={() => setVersion(value=>value+1)}>{t.refresh}</button></header>
    <form className="panel error-filter-panel" onSubmit={apply}>
      <section className="error-filter-section error-date-section"><div className="error-filter-heading"><div><strong>{fc.dateRange}</strong><small>{t.range}</small></div><div className="error-quick-ranges" aria-label={fc.quickRange}><button type="button" onClick={()=>setQuickRange(24)}>{fc.last24h}</button><button type="button" onClick={()=>setQuickRange(168)}>{fc.last7d}</button><button type="button" onClick={()=>setQuickRange(720)}>{fc.last30d}</button></div></div><div className="error-date-grid">{(["from","to"] as const).map(key => <div className="error-date-field" key={key}><div className="error-date-control"><span>{t[key]}</span><DatePickerButton label={t[key]} max={key==="from"?draft.to.slice(0,10)||undefined:undefined} min={key==="to"?draft.from.slice(0,10)||undefined:undefined} value={draft[key].slice(0,10)} onChange={value=>setDatePart(key,value)}/></div><label><span>{t.time}</span><input type="time" value={draft[key].slice(11,16)} onChange={event=>setTimePart(key,event.target.value)}/></label></div>)}</div></section>
      <section className="error-filter-section"><div className="error-filter-heading"><strong>{fc.requestFilters}</strong></div><div className="error-core-filters"><label>{t.statusClass}<select value={draft.statusClass} onChange={event=>setDraft({...draft,statusClass:event.target.value})}><option value="">{t.all}</option><option value="4">4xx</option><option value="5">5xx</option></select></label><label>{t.status}<input type="number" min="400" max="599" placeholder="400–599" value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value})} /></label><label>{t.source}<select value={draft.source} onChange={event=>setDraft({...draft,source:event.target.value})}><option value="">{t.all}</option>{["BACKEND","PROXY","ADMIN_WEB","MOBILE"].map(source=><option key={source}>{source}</option>)}</select></label><label>{t.method}<select value={draft.method} onChange={event=>setDraft({...draft,method:event.target.value})}><option value="">{t.all}</option>{["GET","POST","PUT","PATCH","DELETE","HEAD","OPTIONS","OTHER"].map(method=><option key={method}>{method}</option>)}</select></label></div></section>
      <details className="error-advanced-filters"><summary><span><strong>{fc.advanced}</strong><small>{fc.advancedHint}</small></span></summary><div className="error-advanced-grid">{(["route","correlationId","errorCode"] as const).map(key=><label key={key}>{t[key]}<input maxLength={key==="route"?300:key==="correlationId"?128:80} value={draft[key]} onChange={event=>setDraft({...draft,[key]:event.target.value})} /></label>)}</div></details>
      <div className="error-filter-actions"><button className="primary-button" type="submit" disabled={busy}>{t.apply}</button><button className="ghost-button" type="button" onClick={()=>{setDraft(initialFilters());setFilters(initialFilters());setPage(0);}}>{t.reset}</button></div>
    </form>
    {health ? <section className="panel error-health-panel"><div className="error-center-metrics">{([[t.total,data?.totalElements ?? "—"],[t.queued,health.queued],[t.dropped,health.dropped],[t.failures,health.writeFailures]] as const).map(([label,value],index)=><div className={index>1&&Number(value)>0?"warn":""} key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="error-health-meta"><span><small>{t.retention}</small><strong>{health.retentionDays} {t.days} · {health.maxRows.toLocaleString(locale)} {t.limit}</strong></span><span><small>{t.lastSaved}</small><strong>{date(health.lastSaved)}</strong></span><span><small>{fc.collector}</small><strong>{health.dropped>0||health.writeFailures>0?t.loss:fc.healthy}</strong></span></div>{(health.dropped>0 || health.writeFailures>0) && <p className="error-banner" role="alert">{t.loss}</p>}</section> : <p role="status">{t.pending}</p>}
    {error && <p className="error-banner" role="alert">{error}</p>}
    {busy && !data ? <p role="status">{t.loading}</p> : data && <>
      <section className="panel"><h3>{t.summary}</h3><div className="error-center-distribution">{([[t.client,clientCount],[t.server,rows.length-clientCount]] as const).map(([label,count])=><label key={label}>{label}: {count}<meter min={0} max={Math.max(1,rows.length)} value={count} /></label>)}</div></section>
      {groups.length>0&&<section className="panel"><h3>{t.groups}</h3><div className="table-wrap"><table><thead><tr>{[t.source,t.status,t.method,t.route,t.errorCode,t.occurrences,t.firstSeen,t.lastSeen,t.versions,t.workflow].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{groups.map(group=><tr key={group.fingerprint}><td data-label={t.source}>{group.source}</td><td data-label={t.status}>{group.status??"—"}</td><td data-label={t.method}>{group.method}</td><td data-label={t.route}>{group.route}</td><td data-label={t.errorCode}>{group.errorCode??"—"}</td><td data-label={t.occurrences}>{group.occurrenceCount}</td><td data-label={t.firstSeen}>{date(group.firstOccurredAt)}</td><td data-label={t.lastSeen}>{date(group.lastOccurredAt)}</td><td data-label={t.versions}>{group.affectedVersions||"—"}</td><td data-label={t.workflow}><div className="error-workflow-cell"><span className={`status-pill status-${group.lifecycleStatus.toLowerCase()}`}>{group.lifecycleStatus}</span><button className="ghost-button" type="button" onClick={()=>{setGroupAction(group);setGroupReason("");}}>{workflowAction(group)}</button></div></td></tr>)}</tbody></table></div></section>}
      <div className={`table-wrap error-event-list${busy?" is-loading":""}`} aria-busy={busy}><table><thead><tr>{[t.time,t.source,t.status,t.method,t.route,t.errorCode,t.duration,t.detail].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td data-label={t.time}>{date(row.occurredAt)}</td><td data-label={t.source}>{row.source}</td><td data-label={t.status}>{row.status??"—"}</td><td data-label={t.method}>{row.method}</td><td data-label={t.route}>{row.route}</td><td data-label={t.errorCode}>{row.errorCode ?? "—"}</td><td data-label={t.duration}>{row.durationMs} ms</td><td data-label={t.detail}><button className="ghost-button" onClick={()=>setSelected(row.id)} aria-label={`${t.detail} #${row.id}`}>{t.detail}</button></td></tr>)}</tbody></table>{busy&&<span className="error-list-loading" role="status">{t.loading}</span>}{rows.length===0&&!busy && <p role="status">{t.empty}</p>}</div>
      <nav className="error-pagination" aria-label={locale==="tr"?"Hata sayfaları":"Error pages"}><label>{t.rowsPerPage}<select disabled={busy} value={pageSize} onChange={event=>changePageSize(Number(event.target.value))}>{[10,25,50].map(size=><option key={size} value={size}>{size}</option>)}</select></label><div><button className="ghost-button" disabled={busy||page===0} onClick={()=>changePage(page-1)}>{t.previous}</button><span>{page+1} / {Math.max(1,data.totalPages)}</span><button className="ghost-button" disabled={busy||page+1>=data.totalPages} onClick={()=>changePage(page+1)}>{t.next}</button></div></nav>
    </>}
    {groupAction&&<div className="modal-backdrop" role="presentation" onClick={()=>{if(!groupBusy)setGroupAction(null);}}><form ref={workflowDialogRef} tabIndex={-1} role="dialog" aria-modal="true" aria-label={workflowAction(groupAction)} onClick={event=>event.stopPropagation()} onSubmit={updateGroup} className="modal-card compact error-workflow-modal"><header className="modal-header"><div><span>{groupAction.lifecycleStatus}</span><h2>{workflowAction(groupAction)}</h2></div><button className="modal-icon-close" type="button" disabled={groupBusy} onClick={()=>setGroupAction(null)} aria-label={t.cancel}>×</button></header><div className="modal-body"><p className="error-modal-route">{groupAction.route}</p><label>{t.actionReason}<textarea autoFocus required minLength={8} maxLength={500} value={groupReason} onChange={event=>setGroupReason(event.target.value)} /></label></div><div className="modal-actions"><button className="ghost-button" type="button" disabled={groupBusy} onClick={()=>setGroupAction(null)}>{t.cancel}</button><button className="primary-button" disabled={groupBusy||groupReason.trim().length<8}>{groupBusy?t.loading:workflowAction(groupAction)}</button></div></form></div>}
    {selected!==null && <div className="modal-backdrop" role="presentation" onClick={()=>setSelected(null)}><div ref={detailDialogRef} tabIndex={-1} className="modal-card error-detail-modal" role="dialog" aria-modal="true" aria-labelledby="error-detail-title" onClick={event=>event.stopPropagation()}><header className="modal-header"><div><span>{t.detail}</span><h2 id="error-detail-title">#{selected}</h2></div><button className="modal-icon-close" type="button" onClick={()=>setSelected(null)} aria-label={t.close}>×</button></header><div className="modal-body error-center-detail">{detailError ? <p className="error-banner" role="alert">{detailError}</p> : !detail ? <p role="status">{t.loading}</p> : <><p className="error-detail-summary">{detail.status?statusDescriptions[detail.status]?.[locale==="tr"?0:1]:(locale==="tr"?"İstemci HTTP yanıtı alamadı.":"The client did not receive an HTTP response.")}</p><dl>{[[t.time,date(detail.occurredAt)],[t.source,detail.source],[t.status,detail.status?String(detail.status):t.missing],[t.method,detail.method],[t.route,detail.route],[t.duration,`${detail.durationMs} ms`],[t.correlationId,detail.correlationId],[t.errorCode,detail.errorCode],[t.exception,detail.exceptionType],[t.location,detail.technicalLocation],[dc.platform,detail.clientPlatform],[dc.appVersion,detail.appVersion]].map(([label,value],index)=><div className={index===4||index===9?"wide":""} key={label}><dt>{label}</dt><dd>{value || t.missing}</dd></div>)}</dl></>}</div><div className="modal-actions"><button className="primary-button" type="button" onClick={()=>setSelected(null)}>{t.close}</button></div></div></div>}
  </div>;
}
