import { FormEvent, lazy, Suspense, useEffect, useState } from "react";
import { formatRequestError, request } from "../api";
import { CollapsiblePanel, DataTable, EmptyState, MetricCard, PaginationControls, Panel, SectionToolbar } from "../AdminPrimitives";
import { useAdminLocale } from "../admin/locale";
import { AdminTargetContext, Badge, DatePickerButton, DetailItem, formatDate } from "../admin/shared";

type Alert = { id: number; category: string; severity: string; status: string; titleEn: string; titleTr: string; messageEn: string; messageTr: string; targetPath: string; occurrenceCount: number; firstOccurredAt: string; lastOccurredAt: string; attemptCount: number; nextAttemptAt?: string; sentAt?: string; lastErrorType?: string };
type AlertPage = { content: Alert[]; page: number; size: number; totalElements: number; totalPages: number; first: boolean; last: boolean };
type DailySummary = { date: string; generatedAt: string; backendErrorGroups: number; backendErrorOccurrences: number; financialApprovalRequests: number; operationalApprovalRequests: number; pendingApprovals: number; approvedToday: number; rejectedToday: number; sentAlerts: number; failedAlerts: number; newErrorGroups: number; investigatingErrorGroups: number; resolvedErrorGroups: number; reopenedErrorGroups: number };
type ReportPeriod = "day" | "week" | "month";
const STATUSES = ["PENDING", "RETRY", "SENT", "FAILED", "ACKNOWLEDGED"];
const OwnerOperationsLoadChart = lazy(() => import("../OwnerAlertCharts").then(module => ({ default: module.OwnerOperationsLoadChart })));
const OwnerWorkflowChart = lazy(() => import("../OwnerAlertCharts").then(module => ({ default: module.OwnerWorkflowChart })));

function initialRoute() {
  const query = new URLSearchParams(window.location.search); const rawPage = Number(query.get("page")); const rawSize = Number(query.get("size")); const status = query.get("status") ?? ""; const period=query.get("period");
  return { status: STATUSES.includes(status) ? status : "", category: (query.get("category") ?? "").slice(0, 60), reportDate: (query.get("reportDate") ?? new Date().toISOString().slice(0,10)), reportPeriod: (period==="week"||period==="month"?period:"day") as ReportPeriod, page: Number.isSafeInteger(rawPage) && rawPage >= 0 ? rawPage : 0, size: [10,25,50,100].includes(rawSize) ? rawSize : 25 };
}

function reportDates(endValue:string,period:ReportPeriod){const count=period==="month"?30:period==="week"?7:1;const end=new Date(`${endValue}T12:00:00`);return Array.from({length:count},(_,index)=>{const date=new Date(end);date.setDate(end.getDate()-(count-1-index));return date.toISOString().slice(0,10);});}
function mergeSummaries(items:DailySummary[],date:string):DailySummary {const numeric:(keyof DailySummary)[]=["backendErrorGroups","backendErrorOccurrences","financialApprovalRequests","operationalApprovalRequests","approvedToday","rejectedToday","sentAlerts","failedAlerts","newErrorGroups","investigatingErrorGroups","resolvedErrorGroups","reopenedErrorGroups"];const result={date,generatedAt:new Date().toISOString(),pendingApprovals:items.at(-1)?.pendingApprovals??0} as DailySummary;numeric.forEach(key=>{(result[key] as number)=items.reduce((sum,item)=>sum+(Number(item[key])||0),0);});return result;}

export function OwnerAlertsView({ onError, targetContext, onClearTarget }: { onError: (message: string | null) => void; targetContext?: AdminTargetContext | null; onClearTarget?: () => void }) {
  const { locale } = useAdminLocale(); const [route] = useState(initialRoute);
  const [draft, setDraft] = useState({ status: route.status, category: route.category }); const [filters, setFilters] = useState(draft);
  const [page, setPage] = useState(route.page); const [size, setSize] = useState(route.size); const [data, setData] = useState<AlertPage | null>(null); const [loading, setLoading] = useState(true); const [reload, setReload] = useState(0);
  const [reportDate,setReportDate]=useState(route.reportDate); const [serverToday,setServerToday]=useState(route.reportDate); const [reportPeriod,setReportPeriod]=useState<ReportPeriod>(route.reportPeriod); const [summary,setSummary]=useState<DailySummary|null>(null); const [coverageDays,setCoverageDays]=useState(0);
  const [action,setAction]=useState<{item:Alert;type:"retry"|"acknowledge"}|null>(null); const [reason,setReason]=useState(""); const [mfaCode,setMfaCode]=useState(""); const [actionBusy,setActionBusy]=useState(false);
  const [focusedAlert,setFocusedAlert]=useState<Alert|null>(null);
  const [filtersOpen,setFiltersOpen]=useState(false);
  const rows = data?.content ?? []; const pending = rows.filter(item => item.status === "PENDING" || item.status === "RETRY").length; const failed = rows.filter(item => item.status === "FAILED").length;
  useEffect(() => {
    const query = new URLSearchParams(window.location.search); if(filters.status) query.set("status",filters.status); else query.delete("status"); if(filters.category) query.set("category",filters.category); else query.delete("category"); if(page>0) query.set("page",String(page)); else query.delete("page"); if(size!==25) query.set("size",String(size)); else query.delete("size"); window.history.replaceState(null,"",`/admin/reports/owner-alerts${query.size?`?${query}`:""}`);
    setLoading(true); onError(null); const api = new URLSearchParams({page:String(page),size:String(size)}); if(filters.status) api.set("status",filters.status); if(filters.category) api.set("category",filters.category);
    request<AlertPage>(`/api/v1/admin/owner-alerts?${api}`).then(setData).catch(error=>onError(formatRequestError(error))).finally(()=>setLoading(false));
  },[filters,page,size,reload]);
  useEffect(()=>{const query=new URLSearchParams(window.location.search);if(reportDate!==new Date().toISOString().slice(0,10))query.set("reportDate",reportDate);else query.delete("reportDate");if(reportPeriod!=="day")query.set("period",reportPeriod);else query.delete("period");window.history.replaceState(null,"",`/admin/reports/owner-alerts${query.size?`?${query}`:""}`);},[reportDate,reportPeriod]);
  useEffect(()=>{let active=true;const explicitDate=new URLSearchParams(window.location.search).has("reportDate");request<DailySummary>("/api/v1/admin/owner-alerts/daily-summary").then(value=>{if(!active)return;setServerToday(value.date);if(!explicitDate)setReportDate(value.date);}).catch(error=>onError(formatRequestError(error)));return()=>{active=false;};},[]);
  useEffect(()=>{let active=true;setSummary(null);const dates=reportDates(reportDate,reportPeriod);Promise.all(dates.map(date=>request<DailySummary>(`/api/v1/admin/owner-alerts/daily-summary?date=${encodeURIComponent(date)}`))).then(items=>{if(!active)return;setSummary(mergeSummaries(items,reportDate));setCoverageDays(items.filter(item=>item.backendErrorOccurrences+item.financialApprovalRequests+item.operationalApprovalRequests+item.approvedToday+item.rejectedToday+item.sentAlerts+item.failedAlerts>0).length);}).catch(error=>onError(formatRequestError(error)));return()=>{active=false;};},[reportDate,reportPeriod,reload]);
  useEffect(()=>{if(targetContext?.targetType!=="OWNER_ALERT"||!targetContext.targetId)return;const id=Number(targetContext.targetId);const match=rows.find(item=>item.id===id);if(match)setFocusedAlert(match);},[rows,targetContext?.targetId,targetContext?.targetType]);
  function apply(event: FormEvent){event.preventDefault();setPage(0);setFilters({...draft,category:draft.category.trim().toUpperCase()});}
  async function applyAction(event:FormEvent){event.preventDefault();if(!action||!reason.trim()||!mfaCode.trim())return;setActionBusy(true);onError(null);try{const proof=await request<{token?:string}>("/api/v1/admin/security/mfa/reauthenticate",{method:"POST",body:{code:mfaCode.trim(),purpose:"OWNER_ALERT_ACTION"}});if(!proof.token)throw new Error("MFA re-authentication token was not returned.");await request(`/api/v1/admin/owner-alerts/${action.item.id}/${action.type}`,{method:"POST",headers:{"X-Admin-Reauth-Token":proof.token},body:{reason:reason.trim()}});setAction(null);setReason("");setMfaCode("");setReload(value=>value+1);}catch(error){onError(formatRequestError(error));}finally{setActionBusy(false);}}
  return <div className="stack owner-alerts-view">
    <SectionToolbar title={locale==="tr"?"Owner kritik uyarıları":"Owner critical alerts"} description={locale==="tr"?"Gruplanmış kritik olayların e-posta kuyruğunu ve teslimat sonucunu izleyin.":"Inspect the email queue and delivery outcome for grouped critical events."} state={loading?"loading":"ready"} onReload={()=>setReload(value=>value+1)} />
    <div className="owner-alert-topline">
      <div className="owner-alert-list-metrics"><MetricCard label={locale==="tr"?"Eşleşen":"Matching"} value={String(data?.totalElements??0)} hint={locale==="tr"?"Filtreye uyan toplam":"Total matching the filters"} /><MetricCard label={locale==="tr"?"Bekleyen / tekrar":"Pending / retry"} value={String(pending)} hint={locale==="tr"?"Bu sayfadaki aktif teslimatlar":"Active deliveries on this page"} /><MetricCard label={locale==="tr"?"Başarısız":"Failed"} value={String(failed)} hint={locale==="tr"?"Bu sayfadaki kalıcı hatalar":"Permanent failures on this page"} /></div>
      <div className="owner-alert-date"><div className="owner-alert-periods" aria-label={locale==="tr"?"Rapor dönemi":"Report period"}><button className={reportPeriod==="week"?"active":""} type="button" onClick={()=>setReportPeriod("week")}>1W</button><button className={reportPeriod==="month"?"active":""} type="button" onClick={()=>setReportPeriod("month")}>1M</button></div><DatePickerButton label={locale==="tr"?"Özel gün":"Specific day"} value={reportDate} max={serverToday} today={serverToday} onChange={value=>{setReportDate(value);setReportPeriod("day");}} /><small>{reportPeriod==="day"?(locale==="tr"?"Grafikler seçilen özel günü gösterir.":"Charts reflect the selected specific day."):(()=>{const dates=reportDates(reportDate,reportPeriod);return `${new Intl.DateTimeFormat(locale==="tr"?"tr-TR":"en-GB").format(new Date(`${dates[0]}T12:00:00`))} → ${new Intl.DateTimeFormat(locale==="tr"?"tr-TR":"en-GB").format(new Date(`${dates.at(-1)}T12:00:00`))} · ${coverageDays} ${locale==="tr"?"aktif gün":"active days"}`;})()}</small></div>
    </div>
    {summary ? <div className="owner-alert-chart-grid">
      <Panel title={locale==="tr"?"Operasyon yükü":"Operations load"} description={locale==="tr"?"Hata, onay ve bekleyen işlerin karşılaştırması.":"Compare errors, approvals and pending work."}><Suspense fallback={<div className="admin-chart-loading">{locale==="tr"?"Grafik yükleniyor…":"Loading chart…"}</div>}><OwnerOperationsLoadChart summary={summary} tr={locale==="tr"} /></Suspense></Panel>
      <Panel title={locale==="tr"?"İş akışı sonuçları":"Workflow outcomes"} description={locale==="tr"?"Hata grupları, onaylar ve teslimatların durum dağılımı.":"Status distribution across error groups, approvals and delivery."}><Suspense fallback={<div className="admin-chart-loading">{locale==="tr"?"Grafik yükleniyor…":"Loading chart…"}</div>}><OwnerWorkflowChart summary={summary} tr={locale==="tr"} /></Suspense></Panel>
    </div> : <EmptyState title={locale==="tr"?"Günlük özet bulunamadı":"No daily summary"} message={locale==="tr"?"Seçilen gün için operasyon verisi yok.":"No operational data is available for the selected day."} />}
    <CollapsiblePanel className="owner-alert-filter-panel" title={locale==="tr"?"Teslimat filtreleri":"Delivery filters"} description={locale==="tr"?"Durum ve kategoriye göre uyarı listesini daraltın.":"Narrow the alert list by status and category."} open={filtersOpen} onToggle={()=>setFiltersOpen(value=>!value)}>
      <div className="owner-alert-filter-summary"><span>{locale==="tr"?"Aktif görünüm":"Active view"}</span><strong>{[filters.status,filters.category].filter(Boolean).join(" · ") || (locale==="tr"?"Tüm owner uyarıları":"All owner alerts")}</strong></div>
      <form className="owner-alert-filter-form" onSubmit={apply}><label>{locale==="tr"?"Durum":"Status"}<select value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value})}><option value="">{locale==="tr"?"Tümü":"All"}</option>{STATUSES.map(value=><option key={value}>{value}</option>)}</select></label><label>{locale==="tr"?"Kategori":"Category"}<input maxLength={60} value={draft.category} onChange={event=>setDraft({...draft,category:event.target.value})} placeholder="BACKEND_ERROR" /></label><div className="owner-alert-filter-actions"><button className="ghost-button" type="button" onClick={()=>{setDraft({status:"",category:""});setFilters({status:"",category:""});setPage(0);}}>{locale==="tr"?"Temizle":"Clear"}</button><button className="primary-button" type="submit">{locale==="tr"?"Uygula":"Apply"}</button></div></form>
    </CollapsiblePanel>
    <DataTable columns={[locale==="tr"?"Olay":"Event",locale==="tr"?"Durum":"Status",locale==="tr"?"Tekrar":"Occurrences",locale==="tr"?"Zaman":"Timing",locale==="tr"?"Teslimat":"Delivery",locale==="tr"?"Hedef":"Target"]} rows={rows.map(item=>[
      <div className="table-stack"><strong>{locale==="tr"?item.titleTr:item.titleEn}</strong><small>{item.category} · {item.severity}</small><span>{locale==="tr"?item.messageTr:item.messageEn}</span></div>,
      <Badge value={item.status} tone={item.status==="SENT"?"good":item.status==="FAILED"?"danger":"warn"} />, item.occurrenceCount,
      <div className="table-stack"><span>{formatDate(item.lastOccurredAt)}</span><small>{locale==="tr"?"İlk":"First"}: {formatDate(item.firstOccurredAt)}</small></div>,
      <div className="table-stack"><span>{locale==="tr"?"Deneme":"Attempts"}: {item.attemptCount}</span><small>{item.sentAt?`${locale==="tr"?"Gönderildi":"Sent"}: ${formatDate(item.sentAt)}`:item.nextAttemptAt?`${locale==="tr"?"Sıradaki":"Next"}: ${formatDate(item.nextAttemptAt)}`:"-"}</small>{item.lastErrorType&&<small>{item.lastErrorType}</small>}<div className="toolbar-actions">{item.status==="FAILED"&&<button className="ghost-button" type="button" onClick={()=>setAction({item,type:"retry"})}>{locale==="tr"?"Tekrar kuyruğa al":"Queue again"}</button>}{(item.status==="FAILED"||item.status==="SENT")&&<button className="ghost-button" type="button" onClick={()=>setAction({item,type:"acknowledge"})}>{locale==="tr"?"Kapat":"Acknowledge"}</button>}</div></div>,
      <a className="owner-alert-target-button" href={item.targetPath} aria-label={`${locale==="tr"?"Kaydı aç":"Open record"}: ${locale==="tr"?item.titleTr:item.titleEn}`}><span>{locale==="tr"?"Kaydı aç":"Open record"}</span><span aria-hidden="true">→</span></a>
    ])} empty={locale==="tr"?"Bu filtrelerle owner uyarısı bulunamadı.":"No owner alerts match these filters."} />
    <PaginationControls page={data?.page??page} pageSize={data?.size??size} totalElements={data?.totalElements??0} totalPages={data?.totalPages??1} first={data?.first??true} last={data?.last??true} onPageChange={setPage} onPageSizeChange={value=>{setSize(value);setPage(0);}} />
    {focusedAlert&&<div className="modal-backdrop" role="presentation" onClick={()=>{setFocusedAlert(null);onClearTarget?.();}}><section className="modal-card" role="dialog" aria-modal="true" aria-label={locale==="tr"?"Owner uyarı ayrıntısı":"Owner alert detail"} onClick={event=>event.stopPropagation()}><header className="modal-header"><div><span>{focusedAlert.category}</span><h2>{locale==="tr"?focusedAlert.titleTr:focusedAlert.titleEn}</h2><p>{locale==="tr"?focusedAlert.messageTr:focusedAlert.messageEn}</p></div><button className="modal-icon-close" type="button" onClick={()=>{setFocusedAlert(null);onClearTarget?.();}} aria-label={locale==="tr"?"Uyarı ayrıntısını kapat":"Close alert detail"}>×</button></header><div className="modal-body detail-grid"><DetailItem label={locale==="tr"?"Durum":"Status"} value={focusedAlert.status}/><DetailItem label={locale==="tr"?"Önem":"Severity"} value={focusedAlert.severity}/><DetailItem label={locale==="tr"?"Tekrar":"Occurrences"} value={focusedAlert.occurrenceCount}/><DetailItem label={locale==="tr"?"Deneme":"Attempts"} value={focusedAlert.attemptCount}/><DetailItem label={locale==="tr"?"İlk olay":"First occurred"} value={formatDate(focusedAlert.firstOccurredAt)}/><DetailItem label={locale==="tr"?"Son olay":"Last occurred"} value={formatDate(focusedAlert.lastOccurredAt)}/></div><footer className="modal-actions"><button className="ghost-button" type="button" onClick={()=>{setFocusedAlert(null);onClearTarget?.();}}>{locale==="tr"?"Kapat":"Close"}</button>{focusedAlert.status==="FAILED"&&<button className="primary-button" type="button" onClick={()=>{setFocusedAlert(null);setAction({item:focusedAlert,type:"retry"});}}>{locale==="tr"?"Tekrar kuyruğa al":"Queue again"}</button>}</footer></section></div>}
    {action&&<div className="modal-backdrop confirm-backdrop" role="presentation"><form className="confirm-dialog reauth-dialog" role="dialog" aria-modal="true" aria-label={locale==="tr"?"Owner uyarı işlemi":"Owner alert action"} onSubmit={applyAction}><div className="confirm-dialog-content"><div className="confirm-dialog-copy"><p className="eyebrow">{action.type==="retry"?(locale==="tr"?"Yeniden kuyruğa alma":"Queue again"):(locale==="tr"?"Kaydı kapatma":"Acknowledge")}</p><h2>#{action.item.id} · {action.item.category}</h2><label>{locale==="tr"?"İşlem gerekçesi":"Action reason"}<textarea maxLength={500} value={reason} onChange={event=>setReason(event.target.value)} /></label><label>{locale==="tr"?"Authenticator veya kurtarma kodu":"Authenticator or recovery code"}<input autoFocus maxLength={32} autoComplete="one-time-code" value={mfaCode} onChange={event=>setMfaCode(event.target.value)} /></label></div></div><div className="modal-actions"><button className="ghost-button" type="button" disabled={actionBusy} onClick={()=>{setAction(null);setReason("");setMfaCode("");}}>{locale==="tr"?"Vazgeç":"Cancel"}</button><button className="primary-button" disabled={actionBusy||!reason.trim()||!mfaCode.trim()}>{actionBusy?(locale==="tr"?"Doğrulanıyor…":"Verifying…"):(locale==="tr"?"Doğrula ve uygula":"Verify and apply")}</button></div></form></div>}
  </div>;
}
