import { lazy, Suspense, useMemo, useState } from "react";
import { AdminTrackingModuleSummary, AdminTrackingSummary, AdminTrackingTrendPoint } from "../types";
import { MetricCard, SectionToolbar } from "../AdminPrimitives";
import { useAdminLocale } from "../admin/locale";
import { Badge, formatDate, formatValue, useEndpoint } from "../admin/shared";

const TrackingActivityChart = lazy(() => import("../TrackingAnalyticsCharts").then(module => ({ default: module.TrackingActivityChart })));
const TrackingAdoptionChart = lazy(() => import("../TrackingAnalyticsCharts").then(module => ({ default: module.TrackingAdoptionChart })));
const TrackingModuleChart = lazy(() => import("../TrackingAnalyticsCharts").then(module => ({ default: module.TrackingModuleChart })));
export type TrackingMode = "overview" | "water" | "fasting" | "steps";

export function TrackingMonitoringView({ onError }: { mode?: TrackingMode; onError: (message: string | null) => void }) {
  const { locale } = useAdminLocale(); const tr = locale === "tr"; const [days, setDays] = useState(30);
  const { data, state, reload } = useEndpoint<AdminTrackingSummary>(`/api/v1/admin/tracking/summary?days=${days}`, onError); const trends = data?.trends ?? [];
  const modules = useMemo(() => [
    { key: "water", data: data?.water, eyebrow: tr ? "SU" : "WATER", title: tr ? "Su takibi" : "Water tracking", description: tr ? "Hidrasyon hacmi, günlük kayıtlar ve etkin kullanıcılar." : "Hydration volume, daily logs and active users.", valueLabel: tr ? "Mililitre" : "Millilitres", activityLabel: tr ? "Kayıt" : "Logs", valueKey: "waterMl" as const, activityKey: "waterLogs" as const, color: "primary" as const },
    { key: "fasting", data: data?.fasting, eyebrow: tr ? "ORUÇ" : "FASTING", title: tr ? "Oruç takibi" : "Fasting tracking", description: tr ? "Tamamlanan süre, oturum hacmi ve devam eden oturumlar." : "Completed minutes, session volume and sessions in progress.", valueLabel: tr ? "Dakika" : "Minutes", activityLabel: tr ? "Oturum" : "Sessions", valueKey: "fastingMinutes" as const, activityKey: "fastingSessions" as const, color: "accent" as const },
    { key: "steps", data: data?.steps, eyebrow: tr ? "ADIM" : "STEPS", title: tr ? "Adım takibi" : "Step tracking", description: tr ? "Toplam adım, cihaz kayıtları ve hedef yapılandırması." : "Total steps, device records and goal configuration.", valueLabel: tr ? "Adım" : "Steps", activityLabel: tr ? "Kayıt" : "Records", valueKey: "steps" as const, activityKey: "stepRecords" as const, color: "warning" as const }
  ], [data, tr]);
  const totalRecords = modules.reduce((sum, item) => sum + (item.data?.recordsLastRange ?? 0), 0);
  const peakUsers = trends.reduce((peak, point) => Math.max(peak, (point.waterUsers ?? 0) + (point.fastingUsers ?? 0) + (point.stepUsers ?? 0)), 0);
  const configured = modules.reduce((sum, item) => sum + (item.data?.configuredUsers ?? 0), 0);
  const reminders = modules.reduce((sum, item) => sum + (item.data?.reminderEnabledUsers ?? 0), 0);
  return <div className="stack tracking-command-center">
    <SectionToolbar title={tr ? "Takip analitiği" : "Tracking analytics"} description={tr ? "Su, oruç ve adım kullanımını tek bir toplulaştırılmış çalışma alanında karşılaştırın." : "Compare water, fasting and step usage in one aggregate workspace."} state={state} onReload={reload}>
      <div className="tracking-range" aria-label={tr ? "Analiz dönemi" : "Analysis range"}>{[7, 30, 90].map(value => <button className={days === value ? "active" : ""} key={value} type="button" onClick={() => setDays(value)}>{value}{tr ? "G" : "D"}</button>)}</div>
    </SectionToolbar>
    <section className="tracking-hero"><div><p className="eyebrow">{tr ? "TOPLULAŞTIRILMIŞ TAKİP" : "AGGREGATE TRACKING"}</p><h2>{tr ? "Üç kullanıcı alışkanlığını aynı operasyonel ritimde okuyun." : "Read three user habits in one operational rhythm."}</h2><p>{tr ? "Tekil kullanıcı ve kayıt verisi gösterilmez. Grafikler yalnızca seçilen dönemin toplu eğilimlerini kullanır." : "No user-level or individual record data is shown. Charts use aggregate trends for the selected period only."}</p></div><div className="tracking-window"><Badge value={`${formatTrackingDay(data?.startDate, locale)} → ${formatTrackingDay(data?.endDate, locale)}`} /><span>{tr ? "Son güncelleme" : "Generated"} · {formatDate(data?.generatedAt)}</span></div></section>
    <div className="tracking-summary-grid"><MetricCard label={tr ? "Toplam etkinlik" : "Total activity"} value={formatValue(totalRecords)} hint={tr ? "Su kaydı + oruç oturumu + adım kaydı" : "Water logs + fasting sessions + step records"} /><MetricCard label={tr ? "Günlük en yüksek erişim" : "Peak daily reach"} value={formatValue(peakUsers)} hint={tr ? "Modüllerdeki günlük kullanıcı toplamı" : "Daily users summed across modules"} /><MetricCard label={tr ? "Yapılandırılmış takip" : "Configured tracking"} value={formatValue(configured)} hint={tr ? "Hedef, plan veya hatırlatıcı ayarı" : "Goal, plan or reminder configuration"} /><MetricCard label={tr ? "Etkin hatırlatıcı" : "Enabled reminders"} value={formatValue(reminders)} hint={tr ? "Modüllerdeki etkin hatırlatıcı ayarları" : "Enabled reminder settings across modules"} /></div>
    <div className="tracking-overview-grid"><article className="tracking-chart-card tracking-chart-card-wide"><header><div><span>{tr ? "ORTAK EĞİLİM" : "COMBINED TREND"}</span><h3>{tr ? "Günlük takip etkinliği" : "Daily tracking activity"}</h3><p>{tr ? "Karşılaştırılabilir kayıt adetlerini aynı zaman ekseninde görün." : "Compare activity counts on one shared timeline."}</p></div></header><Suspense fallback={<ChartLoading tr={tr} />}><TrackingActivityChart trends={trends} tr={tr} /></Suspense></article><article className="tracking-chart-card"><header><div><span>{tr ? "BENİMSENME" : "ADOPTION"}</span><h3>{tr ? "Günlük aktif kullanıcılar" : "Daily active users"}</h3><p>{tr ? "Modül bazında günlük erişim dağılımı." : "Daily reach split by tracking module."}</p></div></header><Suspense fallback={<ChartLoading tr={tr} />}><TrackingAdoptionChart trends={trends} tr={tr} /></Suspense></article></div>
    <section className="tracking-module-section"><header><div><p className="eyebrow">{tr ? "MODÜL ANALİZLERİ" : "MODULE ANALYSIS"}</p><h2>{tr ? "Her takip alanının kendi ölçüsü" : "Each tracker in its native measure"}</h2></div><span>{tr ? "Bireysel kayıtlar hariç" : "Individual records excluded"}</span></header><div className="tracking-module-grid">{modules.map(module => <TrackingModuleCard key={module.key} module={module} trends={trends} tr={tr} />)}</div></section>
  </div>;
}

function TrackingModuleCard({ module, trends, tr }: { module: { key: string; data?: AdminTrackingModuleSummary; eyebrow: string; title: string; description: string; valueLabel: string; activityLabel: string; valueKey: "waterMl" | "fastingMinutes" | "steps"; activityKey: "waterLogs" | "fastingSessions" | "stepRecords"; color: "primary" | "accent" | "warning" }; trends: AdminTrackingTrendPoint[]; tr: boolean }) {
  return <article className={`tracking-module-card ${module.key}`}><header><div><span>{module.eyebrow}</span><h3>{module.title}</h3><p>{module.description}</p></div><strong>{formatModuleTotal(module.data, tr)}</strong></header><div className="tracking-module-metrics"><div><span>{tr ? "Etkin kullanıcı" : "Active users"}</span><strong>{formatValue(module.data?.activeUsersLastRange)}</strong></div><div><span>{tr ? "Etkinlik" : "Activity"}</span><strong>{formatValue(module.data?.recordsLastRange)}</strong></div><div><span>{tr ? "Yapılandırılmış" : "Configured"}</span><strong>{formatValue(module.data?.configuredUsers)}</strong></div></div><Suspense fallback={<ChartLoading tr={tr} />}><TrackingModuleChart trends={trends} tr={tr} valueKey={module.valueKey} activityKey={module.activityKey} valueLabel={module.valueLabel} activityLabel={module.activityLabel} color={module.color} /></Suspense></article>;
}
function ChartLoading({ tr }: { tr: boolean }) { return <div className="admin-chart-loading">{tr ? "Grafik yükleniyor…" : "Loading chart…"}</div>; }
export function formatModuleTotal(module?: AdminTrackingModuleSummary, tr = false): string { if (!module) return "-"; const value = formatValue(module.totalValueLastRange); if (module.totalValueUnit === "ml") return `${value} ml`; if (module.totalValueUnit === "minutes") return `${value} ${tr ? "dk" : "min"}`; if (module.totalValueUnit === "steps") return `${value} ${tr ? "adım" : "steps"}`; return value; }
function formatTrackingDay(value: string | undefined, locale: string): string { if (!value) return "-"; const date = new Date(`${value.slice(0, 10)}T12:00:00`); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat(locale === "tr" ? "tr-TR" : "en-GB").format(date); }
