package com.grun.calorietracker.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

import java.time.LocalDateTime;

@Data
@Schema(description = "Voice transcript AI draft request. Speech-to-text remains a mobile/client concern; backend receives the transcript.")
public class AiVoiceFoodDraftRequestDto {
    @NotBlank(message = "Transcript is required")
    @Size(max = 4000, message = "Transcript must not exceed 4000 characters")
    @Schema(description = "Voice transcript generated by the mobile app.", example = "I ate 150 grams chicken breast and 100 grams rice for lunch")
    private String transcript;

    @Schema(description = "Suggested meal type from the client.", example = "LUNCH")
    private String mealType;

    @Schema(description = "Diary timestamp to use for the draft.", example = "2026-06-01T13:30:00")
    private LocalDateTime logDate;

    @Schema(description = "Transcript language hint.", example = "en")
    private String locale;
}
