package com.grun.calorietracker.enums;

public enum AdminAuditTargetType {
    USER_SUBSCRIPTION,
    AI_REQUEST,
    AI_OPERATIONS_POLICY,
    AI_CREDIT_PRICING,
    SUBSCRIPTION_FEATURE,
    RETENTION_POLICY,
    RECIPE,
    USER_ACCOUNT,
    PRODUCT_QUALITY_AI_SETTINGS,
    NOTIFICATION_CAMPAIGN,
    PROMOTION,
    ADMIN_ACCOUNT,
    ADMIN_INVITATION,
    ADMIN_SESSION,
    EXERCISE_ITEM,
    CATALOG_REVIEW_ITEM,
    RUNTIME_OPERATIONS,
    ADMIN_APPROVAL,
    GDPR_REQUEST,
    PRODUCTION_VERIFICATION,
    FASTING_GOVERNANCE
}
