package com.grun.calorietracker.enums;

public enum EnergyBalanceInsightCode {
    ENERGY_BALANCE_DEFICIT,
    ENERGY_BALANCE_SURPLUS,
    ENERGY_BALANCE_STABLE,
    MODELED_WEIGHT_CHANGE_AVAILABLE,
    OBSERVED_CHANGE_CLOSE_TO_MODEL,
    OBSERVED_CHANGE_DIFFERS_FROM_MODEL,
    ENERGY_DATA_INCOMPLETE,
    WEIGHT_DATA_INCOMPLETE
}
