package com.grun.calorietracker.enums;

public enum EnergyExpenditureSource {
    HEALTH_TOTAL_ENERGY,
    HEALTH_RESTING_PLUS_ACTIVE,
    HEALTH_ACTIVE_PLUS_PROFILE_RESTING,
    HEALTH_TOTAL_PLUS_LOGGED_ACTIVITY,
    HEALTH_ACTIVE_PLUS_PROFILE_RESTING_AND_LOGGED_ACTIVITY,
    PROFILE_TDEE_PLUS_LOGGED_ACTIVITY,
    PROFILE_TDEE_ESTIMATE,
    UNAVAILABLE
}
