package com.grun.calorietracker.enums;

public enum FoodProductQualityIssue {
    LOW_QUALITY,
    MISSING_IMAGE,
    MISSING_CALORIES,
    MISSING_MACROS,
    MISSING_SERVING_SIZE,
    MISSING_REGION,
    UNSUPPORTED_REGION,
    MISSING_BARCODE,
    INVALID_BARCODE_FORMAT,
    SUSPICIOUS_CALORIES,
    SUSPICIOUS_MACROS,
    MISSING_MICRONUTRIENTS,
    MISSING_NUTRIENT_QUALITY_FIELDS,
    SUSPICIOUS_NUTRIENT_QUALITY
}
