package com.grun.calorietracker.enums;

public enum ProductAnalyticsEventType {
    LOG_FLOW_STARTED,
    LOG_FLOW_COMPLETED,
    SEARCH_STARTED,
    SEARCH_RESULT_SELECTED,
    BARCODE_SCAN_STARTED,
    BARCODE_SCAN_COMPLETED,
    QUICK_LOG_SUGGESTION_VIEWED,
    QUICK_LOG_SUGGESTION_APPLIED,
    AI_DRAFT_VIEWED,
    AI_DRAFT_CONFIRMED,
    AI_DRAFT_REJECTED,
    PAYWALL_VIEWED,
    SUBSCRIPTION_STARTED
}
