package com.grun.calorietracker.enums;

public enum SubscriptionFeature {
    BARCODE_SCANNER,
    MANUAL_FOOD_LOGGING,
    FOOD_DIARY,
    WEIGHT_PROGRESS,
    WATER_TRACKING,
    WORKOUT_LOGGING,
    SAVED_MEAL_TEMPLATES,
    RECIPE_BUILDER,
    PUBLIC_RECIPE_LIBRARY,
    ADVANCED_MACRO_TARGETS,
    MICRONUTRIENT_DETAILS,
    DATA_EXPORT,
    FASTING_BASIC,
    FASTING_ADVANCED,
    AI_MEAL_DRAFTS,
    AI_WORKOUT_PLANNER,
    AI_RECIPE_GENERATION,
    AI_MEAL_PREPARATION_GUIDE,
    AI_NUTRITION_PLAN,
    AI_INSIGHTS,
    HEALTH_INTEGRATION,
    ADVANCED_ANALYTICS,
    AD_FREE,
    CUSTOM_FOOD_LIBRARY
}