package com.grun.calorietracker.enums;

public enum SubscriptionFeature {
    AI_MEAL_DRAFTS,
    AI_WORKOUT_PLANNER,
    AI_RECIPE_GENERATION,
    AI_MEAL_PREPARATION_GUIDE,
    AI_NUTRITION_PLAN,
    AI_INSIGHTS,
    HEALTH_INTEGRATION,
    ADVANCED_ANALYTICS,
    AD_FREE,
    CUSTOM_FOOD_LIBRARY
}