#!/usr/bin/env python3
"""Generate the deterministic V245 localization backfill from the approved TR catalog."""

import csv
import re
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "outputs/product-catalog-aug21/tr-augmentation-v2/import-chunks/tr-generic-catalog-v2-part-001.csv"
BACKFILL_TARGET = ROOT / "src/main/resources/db/migration/V245__backfill_generic_food_localizations.sql"
NAMING_TARGET = ROOT / "src/main/resources/db/migration/V246__refine_generic_food_turkish_raw_names.sql"

# "Çiğ" is user-relevant for animal proteins and products commonly distinguished
# from roasted versions. For produce, grains and legumes the uncooked item is the
# ordinary Turkish catalog name; cooked variants already carry an explicit prefix.
RAW_PREFIX_REQUIRED_SOURCE_KEYS = {
    "USDA_FOODDATA:fdc:2646170", "USDA_FOODDATA:fdc:173627",
    "USDA_FOODDATA:fdc:171098", "USDA_FOODDATA:fdc:2514744",
    "USDA_FOODDATA:fdc:2646175", "USDA_FOODDATA:fdc:174315",
    "USDA_FOODDATA:fdc:167822", "USDA_FOODDATA:fdc:2646169",
    "USDA_FOODDATA:fdc:2684441", "USDA_FOODDATA:fdc:173706",
    "USDA_FOODDATA:fdc:2684444", "USDA_FOODDATA:fdc:333374",
    "USDA_FOODDATA:fdc:175119", "USDA_FOODDATA:fdc:2684443",
    "USDA_FOODDATA:fdc:175142", "USDA_FOODDATA:fdc:323604",
    "USDA_FOODDATA:fdc:2346393", "USDA_FOODDATA:fdc:2346394",
    "USDA_FOODDATA:fdc:2515374", "USDA_FOODDATA:fdc:2515375",
    "USDA_FOODDATA:fdc:2515379", "USDA_FOODDATA:fdc:2710819",
    "USDA_FOODDATA:fdc:2515381",
}


def sql(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def normalize_alias(value: str) -> str:
    value = value.lower().translate(str.maketrans("çğıöşü", "cgiosu"))
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]+", " ", value).strip()


def turkish_catalog_name(row: dict, column: str) -> str:
    value = (row[column] or row["display_name_tr"]).strip()
    if row["preparation_state"] == "RAW" and row["source_key"] not in RAW_PREFIX_REQUIRED_SOURCE_KEYS:
        return re.sub(r"^Çiğ\s+", "", value, count=1)
    return value


def main() -> None:
    with SOURCE.open(encoding="utf-8-sig", newline="") as handle:
        rows = list(csv.DictReader(handle))

    selected = []
    seen = set()
    for row in rows:
        source_key = row["source_key"].strip()
        display_tr = row["display_name_tr"].strip()
        short_tr = (row["short_display_name_tr"] or display_tr).strip()
        alias_tr = row["alias_tr"].strip()
        if not source_key or not display_tr:
            raise ValueError(f"Missing localization identity: {row}")
        if source_key in seen:
            raise ValueError(f"Duplicate source_key: {source_key}")
        seen.add(source_key)
        selected.append((source_key, display_tr, short_tr, alias_tr))

    corrected = []
    rows_by_source_key = {row["source_key"].strip(): row for row in rows}
    for source_key, display_tr, short_tr, alias_tr in selected:
        row = rows_by_source_key[source_key]
        corrected.append((
            source_key,
            display_tr,
            short_tr,
            turkish_catalog_name(row, "display_name_tr"),
            turkish_catalog_name(row, "short_display_name_tr"),
            alias_tr,
        ))

    names = [new_display for _, _, _, new_display, _, _ in corrected]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise ValueError(f"Duplicate Turkish display names after normalization: {duplicates}")
    optional_raw_prefixes = [
        source_key for source_key, _, _, new_display, _, _ in corrected
        if source_key not in RAW_PREFIX_REQUIRED_SOURCE_KEYS and new_display.startswith("Çiğ ")
    ]
    if optional_raw_prefixes:
        raise ValueError(f"Unnecessary raw prefixes remain: {optional_raw_prefixes}")

    values = ",\n".join(
        f"    ({sql(source_key)}, {sql(display)}, {sql(short)}, {sql(alias)})"
        for source_key, display, short, alias in selected
    )
    aliases = []
    for source_key, _, _, raw_aliases in selected:
        for alias in (part.strip() for part in raw_aliases.split(";")):
            if alias:
                aliases.append((source_key, alias, normalize_alias(alias)))

    content = f"""-- Generated by scripts/generate-generic-food-localization-backfill.py.
-- Existing TR localizations are intentionally preserved; this only fills gaps.
WITH approved(source_key, display_name, short_display_name, alias_tr) AS (VALUES
{values}
), matched AS (
    SELECT f.id AS food_item_id, a.display_name, a.short_display_name, a.alias_tr
    FROM approved a
    JOIN food_items f ON f.source_key = a.source_key
    WHERE f.catalog_type = 'GENERIC_INGREDIENT'
)
INSERT INTO food_item_localizations(food_item_id, language, display_name, short_display_name, source)
SELECT food_item_id, 'TR', display_name, short_display_name, 'generic_catalog_backfill_v245'
FROM matched
ON CONFLICT (food_item_id, language) DO NOTHING;

WITH approved(source_key, alias_tr, normalized_alias) AS (VALUES
{",\n".join(f"    ({sql(source_key)}, {sql(alias)}, {sql(normalized)})" for source_key, alias, normalized in aliases)}
)
INSERT INTO food_item_search_aliases(food_item_id, alias, normalized_alias, language, alias_type, source)
SELECT f.id, a.alias_tr, a.normalized_alias, 'TR', 'TRANSLATION', 'generic_catalog_backfill_v245'
FROM approved a
JOIN food_items f ON f.source_key = a.source_key
WHERE f.catalog_type = 'GENERIC_INGREDIENT'
ON CONFLICT (food_item_id, normalized_alias, language) DO NOTHING;
"""
    BACKFILL_TARGET.write_text(content, encoding="utf-8", newline="\n")

    changed = [row for row in corrected if row[1] != row[3] or row[2] != row[4]]
    naming_values = ",\n".join(
        f"    ({sql(source_key)}, {sql(old_display)}, {sql(old_short)}, {sql(new_display)}, {sql(new_short)})"
        for source_key, old_display, old_short, new_display, new_short, _ in changed
    )
    naming_content = f"""-- Refines Turkish user-facing names without changing preparation state or nutrition.
-- Existing curator changes are preserved unless they still equal the old generated name.
WITH approved(source_key, old_display_name, old_short_display_name, display_name, short_display_name) AS (VALUES
{naming_values}
), matched AS (
    SELECT f.id AS food_item_id, a.*
    FROM approved a
    JOIN food_items f ON f.source_key = a.source_key
    WHERE f.catalog_type = 'GENERIC_INGREDIENT'
)
INSERT INTO food_item_localizations(food_item_id, language, display_name, short_display_name, source)
SELECT food_item_id, 'TR', display_name, short_display_name, 'generic_catalog_naming_v246'
FROM matched
ON CONFLICT (food_item_id, language) DO UPDATE
SET display_name = EXCLUDED.display_name,
    short_display_name = EXCLUDED.short_display_name,
    source = EXCLUDED.source,
    updated_at = CURRENT_TIMESTAMP
WHERE food_item_localizations.display_name = (
          SELECT old_display_name FROM matched WHERE matched.food_item_id = food_item_localizations.food_item_id
      )
  AND coalesce(food_item_localizations.short_display_name, food_item_localizations.display_name) = (
          SELECT old_short_display_name FROM matched WHERE matched.food_item_id = food_item_localizations.food_item_id
      );
"""
    NAMING_TARGET.write_text(naming_content, encoding="utf-8", newline="\n")
    retained_raw = sum(new_display.startswith("Çiğ ") for _, _, _, new_display, _, _ in corrected)
    print(f"generated_backfill={BACKFILL_TARGET} rows={len(selected)}")
    print(f"generated_naming={NAMING_TARGET} changed_rows={len(changed)} retained_required_raw_prefixes={retained_raw}")


if __name__ == "__main__":
    main()
