DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM federated_identities
        GROUP BY user_id, provider
        HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION 'Duplicate federated identities exist for the same user and provider. Reconcile them before applying V161.';
    END IF;
END $$;

ALTER TABLE federated_identities
    ADD CONSTRAINT uq_federated_identity_user_provider UNIQUE (user_id, provider);

CREATE TABLE account_link_authorizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    purpose VARCHAR(32) NOT NULL,
    target_provider VARCHAR(32) NOT NULL,
    reauthentication_method VARCHAR(32) NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_account_link_authorization_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_account_link_authorization_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_account_link_authorization_purpose CHECK (purpose IN ('ACCOUNT_LINK', 'ACCOUNT_UNLINK')),
    CONSTRAINT chk_account_link_authorization_provider CHECK (target_provider IN ('GOOGLE', 'APPLE')),
    CONSTRAINT chk_account_link_authorization_method CHECK (reauthentication_method IN ('PASSWORD', 'GOOGLE', 'APPLE'))
);

CREATE INDEX idx_account_link_authorization_user_created
    ON account_link_authorizations (user_id, created_at DESC);
CREATE INDEX idx_account_link_authorization_expiry
    ON account_link_authorizations (expires_at);

CREATE TABLE account_security_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    provider VARCHAR(32),
    result_code VARCHAR(64),
    correlation_id VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_account_security_audit_event_type CHECK (event_type IN (
        'ACCOUNT_LINK_AUTHORIZATION_CREATED',
        'ACCOUNT_LINK_SUCCEEDED',
        'ACCOUNT_LINK_REJECTED',
        'ACCOUNT_PROVIDER_UNLINKED'
    )),
    CONSTRAINT chk_account_security_audit_provider CHECK (provider IS NULL OR provider IN ('GOOGLE', 'APPLE'))
);

CREATE INDEX idx_account_security_audit_user_created
    ON account_security_audit_events (user_id, created_at DESC);
