ALTER TABLE users
    ADD COLUMN IF NOT EXISTS admin_mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS admin_role_updated_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_users_admin_roles
    ON users(role, account_enabled)
    WHERE role LIKE 'ADMIN%';

ALTER TABLE admin_action_audits DROP CONSTRAINT IF EXISTS chk_admin_action_audits_action_type;
ALTER TABLE admin_action_audits ADD CONSTRAINT chk_admin_action_audits_action_type CHECK (action_type IN (
    'SUBSCRIPTION_UPDATE','AI_QUOTA_RESET','AI_QUOTA_ADDON_GRANT','AI_QUOTA_REFUND',
    'AI_REQUEST_INSPECT','AI_CREDIT_PRICING_UPDATE','SUBSCRIPTION_FEATURE_UPDATE',
    'SUBSCRIPTION_ENTITLEMENT_MATRIX_APPLY','RETENTION_POLICY_UPDATE','RECIPE_CREATE',
    'RECIPE_REVIEW_UPDATE','USER_STATUS_UPDATE','USER_SUPPORT_NOTE_CREATE','USER_SESSION_REVOKE',
    'PRODUCT_QUALITY_AI_SETTINGS_UPDATE','NOTIFICATION_CAMPAIGN_CREATE','NOTIFICATION_CAMPAIGN_UPDATE',
    'NOTIFICATION_CAMPAIGN_SCHEDULE','NOTIFICATION_CAMPAIGN_CANCEL','PROMO_CREATE','PROMO_UPDATE',
    'PROMO_ACTIVATE','PROMO_DEACTIVATE','PROMO_RECONCILE','PROMO_REDEMPTION_RECORD',
    'ADMIN_ROLE_UPDATE','ADMIN_STATUS_UPDATE','ADMIN_MFA_STATUS_UPDATE'
));
ALTER TABLE admin_action_audits DROP CONSTRAINT IF EXISTS chk_admin_action_audits_target_type;
ALTER TABLE admin_action_audits ADD CONSTRAINT chk_admin_action_audits_target_type CHECK (target_type IN (
    'USER_SUBSCRIPTION','AI_REQUEST','AI_CREDIT_PRICING','SUBSCRIPTION_FEATURE','RETENTION_POLICY',
    'RECIPE','USER_ACCOUNT','PRODUCT_QUALITY_AI_SETTINGS','NOTIFICATION_CAMPAIGN','PROMOTION','ADMIN_ACCOUNT'
));

CREATE OR REPLACE FUNCTION prevent_admin_audit_mutation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'admin action audit rows are immutable';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_admin_action_audits_immutable ON admin_action_audits;
CREATE TRIGGER trg_admin_action_audits_immutable
    BEFORE UPDATE OR DELETE ON admin_action_audits
    FOR EACH ROW EXECUTE FUNCTION prevent_admin_audit_mutation();