CREATE TABLE federated_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    provider_email VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_federated_identities_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uq_federated_identity_provider_subject UNIQUE (provider, provider_subject)
);

CREATE INDEX idx_federated_identities_user ON federated_identities (user_id);
