ALTER TABLE users
    ADD COLUMN IF NOT EXISTS admin_mfa_secret_encrypted TEXT,
    ADD COLUMN IF NOT EXISTS admin_mfa_enrollment_started_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS admin_mfa_verified_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS admin_mfa_recovery_codes (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code_hash VARCHAR(100) NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_mfa_recovery_codes_user_unused
    ON admin_mfa_recovery_codes(user_id, used_at);
ALTER TABLE admin_action_audits DROP CONSTRAINT IF EXISTS chk_admin_action_audits_action_type;
ALTER TABLE admin_action_audits ADD CONSTRAINT chk_admin_action_audits_action_type CHECK (action_type IN (
    'SUBSCRIPTION_UPDATE','AI_QUOTA_RESET','AI_QUOTA_ADDON_GRANT','AI_QUOTA_REFUND','AI_REQUEST_INSPECT',
    'AI_OPERATIONS_POLICY_UPDATE','AI_OPERATIONS_DEPLOYMENT_ROLLBACK','AI_CREDIT_PRICING_UPDATE',
    'SUBSCRIPTION_FEATURE_UPDATE','SUBSCRIPTION_ENTITLEMENT_MATRIX_APPLY','RETENTION_POLICY_UPDATE',
    'RECIPE_CREATE','RECIPE_REVIEW_UPDATE','USER_STATUS_UPDATE','USER_SUPPORT_NOTE_CREATE','USER_SESSION_REVOKE',
    'PRODUCT_QUALITY_AI_SETTINGS_UPDATE','NOTIFICATION_CAMPAIGN_CREATE','NOTIFICATION_CAMPAIGN_UPDATE',
    'NOTIFICATION_CAMPAIGN_SCHEDULE','NOTIFICATION_CAMPAIGN_CANCEL','PROMO_CREATE','PROMO_UPDATE','PROMO_ACTIVATE',
    'PROMO_DEACTIVATE','PROMO_RECONCILE','PROMO_REDEMPTION_RECORD','ADMIN_ROLE_UPDATE','ADMIN_STATUS_UPDATE',
    'ADMIN_MFA_STATUS_UPDATE','ADMIN_MFA_ENROLL','ADMIN_MFA_DISABLE','ADMIN_MFA_REAUTHENTICATE',
    'CATALOG_EXERCISE_CREATE','CATALOG_EXERCISE_UPDATE','CATALOG_EXERCISE_REVIEW','CATALOG_REVIEW_ASSIGNMENT',
    'RUNTIME_POLICY_UPDATE','RUNTIME_POLICY_ROLLBACK','RUNTIME_RECORD_CREATE','RUNTIME_JOB_RETRY'
));