CREATE TABLE IF NOT EXISTS admin_approval_requests (
    id BIGSERIAL PRIMARY KEY,
    action_type VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    maker_email VARCHAR(320) NOT NULL,
    checker_email VARCHAR(320),
    target_key VARCHAR(128) NOT NULL,
    payload_json TEXT NOT NULL,
    request_reason VARCHAR(500) NOT NULL,
    decision_reason VARCHAR(500),
    correlation_id VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    decided_at TIMESTAMPTZ,
    CONSTRAINT chk_admin_approval_status CHECK (status IN ('PENDING','APPROVED','REJECTED','EXPIRED','EXECUTION_FAILED')),
    CONSTRAINT chk_admin_approval_action CHECK (action_type IN ('SUBSCRIPTION_UPDATE','AI_QUOTA_RESET','AI_ADDON_QUOTA_GRANT','ENTITLEMENT_MATRIX_APPLY','PLAN_FEATURE_UPDATE','AI_QUOTA_REFUND','NOTIFICATION_CAMPAIGN_SCHEDULE','RUNTIME_POLICY_UPDATE'))
);
CREATE INDEX IF NOT EXISTS idx_admin_approval_queue ON admin_approval_requests(status, created_at DESC);

ALTER TABLE admin_action_audits DROP CONSTRAINT IF EXISTS chk_admin_action_audits_action_type;
ALTER TABLE admin_action_audits ADD CONSTRAINT chk_admin_action_audits_action_type CHECK (action_type IN (
    'SUBSCRIPTION_UPDATE','AI_QUOTA_RESET','AI_QUOTA_ADDON_GRANT','AI_QUOTA_REFUND','AI_REQUEST_INSPECT',
    'AI_OPERATIONS_POLICY_UPDATE','AI_OPERATIONS_DEPLOYMENT_ROLLBACK','AI_CREDIT_PRICING_UPDATE',
    'SUBSCRIPTION_FEATURE_UPDATE','SUBSCRIPTION_ENTITLEMENT_MATRIX_APPLY','RETENTION_POLICY_UPDATE',
    'RECIPE_CREATE','RECIPE_REVIEW_UPDATE','USER_STATUS_UPDATE','USER_SUPPORT_NOTE_CREATE','USER_SESSION_REVOKE',
    'PRODUCT_QUALITY_AI_SETTINGS_UPDATE','NOTIFICATION_CAMPAIGN_CREATE','NOTIFICATION_CAMPAIGN_UPDATE',
    'NOTIFICATION_CAMPAIGN_SCHEDULE','NOTIFICATION_CAMPAIGN_CANCEL','PROMO_CREATE','PROMO_UPDATE','PROMO_ACTIVATE',
    'PROMO_DEACTIVATE','PROMO_RECONCILE','PROMO_REDEMPTION_RECORD','ADMIN_ROLE_UPDATE','ADMIN_STATUS_UPDATE',
    'ADMIN_MFA_STATUS_UPDATE','ADMIN_MFA_ENROLL','ADMIN_MFA_DISABLE','ADMIN_MFA_REAUTHENTICATE',
    'ADMIN_APPROVAL_REQUEST','ADMIN_APPROVAL_APPROVE','ADMIN_APPROVAL_REJECT','ADMIN_APPROVAL_EXECUTION_FAILED',
    'CATALOG_EXERCISE_CREATE','CATALOG_EXERCISE_UPDATE','CATALOG_EXERCISE_REVIEW','CATALOG_REVIEW_ASSIGNMENT',
    'RUNTIME_POLICY_UPDATE','RUNTIME_POLICY_ROLLBACK','RUNTIME_RECORD_CREATE','RUNTIME_JOB_RETRY'
));