CREATE TABLE gdpr_admin_requests (
    id BIGSERIAL PRIMARY KEY,
    request_type VARCHAR(16) NOT NULL,
    status VARCHAR(20) NOT NULL,
    subject_reference VARCHAR(64) NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    assigned_to VARCHAR(320),
    result_code VARCHAR(64),
    evidence_reference VARCHAR(128),
    failure_summary VARCHAR(300),
    escalated_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_gdpr_admin_request_type CHECK (request_type IN ('EXPORT', 'DELETE')),
    CONSTRAINT chk_gdpr_admin_request_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED', 'ESCALATED'))
);
CREATE INDEX idx_gdpr_admin_requests_status_due ON gdpr_admin_requests(status, due_at);
CREATE INDEX idx_gdpr_admin_requests_requested ON gdpr_admin_requests(requested_at DESC);

ALTER TABLE admin_action_audits DROP CONSTRAINT IF EXISTS chk_admin_action_audits_action_type;
ALTER TABLE admin_action_audits ADD CONSTRAINT chk_admin_action_audits_action_type CHECK (action_type IN (
'USER_STATUS_UPDATE','USER_ROLE_UPDATE','PRODUCT_REVIEW_DECISION','PRODUCT_REVIEW_UPDATE','PRODUCT_REVIEW_CREATE','PRODUCT_REVIEW_DELETE','PRODUCT_REVIEW_AI_ANALYZE','PRODUCT_REVIEW_AI_DECISION','SUBSCRIPTION_UPDATE','SUBSCRIPTION_AI_QUOTA_RESET','SUBSCRIPTION_AI_ADDON_GRANT','SUBSCRIPTION_FEATURE_MATRIX_UPDATE','SUBSCRIPTION_ENTITLEMENT_MATRIX_APPLY','AI_QUOTA_REFUND','AI_QUOTA_REFUND_REJECT','NOTIFICATION_CAMPAIGN_CREATE','NOTIFICATION_CAMPAIGN_UPDATE','NOTIFICATION_CAMPAIGN_SCHEDULE','NOTIFICATION_CAMPAIGN_PAUSE','NOTIFICATION_CAMPAIGN_CANCEL','NOTIFICATION_CAMPAIGN_DELETE','PROMO_CREATE','PROMO_UPDATE','PROMO_STATUS_CHANGE','PROMO_REDEMPTION_ADJUST','RETENTION_POLICY_UPDATE','ADMIN_ACCESS_GRANT','ADMIN_ROLE_UPDATE','ADMIN_STATUS_UPDATE','ADMIN_MFA_STATUS_UPDATE','ADMIN_MFA_ENROLL','ADMIN_MFA_DISABLE','ADMIN_MFA_REAUTHENTICATE','ADMIN_APPROVAL_REQUEST','ADMIN_APPROVAL_APPROVE','ADMIN_APPROVAL_REJECT','ADMIN_APPROVAL_EXECUTION_FAILED','GDPR_REQUEST_UPDATE','CATALOG_EXERCISE_CREATE','CATALOG_EXERCISE_UPDATE','CATALOG_EXERCISE_REVIEW','CATALOG_REVIEW_ASSIGN','RUNTIME_OPERATIONS_POLICY_UPDATE','RUNTIME_OPERATION_RECORD_CREATE'
));
