CREATE TABLE production_verification_runs (
    id BIGSERIAL PRIMARY KEY,
    provider VARCHAR(32) NOT NULL,
    environment VARCHAR(24) NOT NULL,
    scenario VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    evidence_reference VARCHAR(240) NOT NULL,
    summary VARCHAR(500) NOT NULL,
    executed_by VARCHAR(320) NOT NULL,
    executed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_until TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_production_verification_provider CHECK (provider IN ('REVENUECAT','BREVO','PUSH','DATABASE','CLOUD')),
    CONSTRAINT chk_production_verification_environment CHECK (environment IN ('SANDBOX','STAGING','PRODUCTION')),
    CONSTRAINT chk_production_verification_status CHECK (status IN ('PASSED','FAILED','BLOCKED'))
);
CREATE INDEX idx_production_verification_provider_time ON production_verification_runs(provider, executed_at DESC);

ALTER TABLE admin_action_audits DROP CONSTRAINT IF EXISTS chk_admin_action_audits_action_type;
ALTER TABLE admin_action_audits ADD CONSTRAINT chk_admin_action_audits_action_type CHECK (action_type IN (
'SUBSCRIPTION_UPDATE','AI_QUOTA_RESET','AI_QUOTA_ADDON_GRANT','AI_QUOTA_REFUND','AI_REQUEST_INSPECT',
'AI_OPERATIONS_POLICY_UPDATE','AI_OPERATIONS_DEPLOYMENT_ROLLBACK','AI_CREDIT_PRICING_UPDATE',
'SUBSCRIPTION_FEATURE_UPDATE','SUBSCRIPTION_ENTITLEMENT_MATRIX_APPLY','RETENTION_POLICY_UPDATE',
'RECIPE_CREATE','RECIPE_REVIEW_UPDATE','USER_STATUS_UPDATE','USER_SUPPORT_NOTE_CREATE','USER_SESSION_REVOKE',
'PRODUCT_QUALITY_AI_SETTINGS_UPDATE','NOTIFICATION_CAMPAIGN_CREATE','NOTIFICATION_CAMPAIGN_UPDATE',
'NOTIFICATION_CAMPAIGN_SCHEDULE','NOTIFICATION_CAMPAIGN_CANCEL','PROMO_CREATE','PROMO_UPDATE','PROMO_ACTIVATE',
'PROMO_DEACTIVATE','PROMO_RECONCILE','PROMO_REDEMPTION_RECORD','ADMIN_ROLE_UPDATE','ADMIN_STATUS_UPDATE',
'ADMIN_MFA_STATUS_UPDATE','ADMIN_MFA_ENROLL','ADMIN_MFA_DISABLE','ADMIN_MFA_REAUTHENTICATE',
'ADMIN_APPROVAL_REQUEST','ADMIN_APPROVAL_APPROVE','ADMIN_APPROVAL_REJECT','ADMIN_APPROVAL_EXECUTION_FAILED',
'GDPR_REQUEST_UPDATE','PRODUCTION_VERIFICATION_RECORD','CATALOG_EXERCISE_CREATE','CATALOG_EXERCISE_UPDATE',
'CATALOG_EXERCISE_REVIEW','CATALOG_REVIEW_ASSIGNMENT','RUNTIME_POLICY_UPDATE','RUNTIME_POLICY_ROLLBACK',
'RUNTIME_RECORD_CREATE','RUNTIME_JOB_RETRY'
));