CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    age INTEGER,
    gender VARCHAR(255),
    height DOUBLE PRECISION,
    weight DOUBLE PRECISION,
    body_fat_percentage DOUBLE PRECISION,
    bmi DOUBLE PRECISION,
    role VARCHAR(255)
);

CREATE TABLE food_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    barcode VARCHAR(255),
    image_url VARCHAR(255),
    external_image_url VARCHAR(255),
    display_image_url VARCHAR(255),
    allergens VARCHAR(255),
    nutri_score VARCHAR(255),
    data_source VARCHAR(255),
    verification_status VARCHAR(255),
    image_source VARCHAR(255),
    image_status VARCHAR(255),
    usage_count BIGINT,
    quality_score INTEGER,
    review_priority INTEGER,
    last_external_sync_at TIMESTAMP,
    last_reviewed_at TIMESTAMP,
    reviewed_by VARCHAR(255),
    calories DOUBLE PRECISION,
    protein DOUBLE PRECISION,
    fat DOUBLE PRECISION,
    carbs DOUBLE PRECISION,
    fiber DOUBLE PRECISION,
    sugar DOUBLE PRECISION,
    sodium DOUBLE PRECISION,
    potassium DOUBLE PRECISION,
    cholesterol DOUBLE PRECISION,
    calcium DOUBLE PRECISION,
    iron DOUBLE PRECISION,
    magnesium DOUBLE PRECISION,
    zinc DOUBLE PRECISION,
    vitamin_a DOUBLE PRECISION,
    vitamin_c DOUBLE PRECISION,
    vitamin_d DOUBLE PRECISION,
    vitamin_e DOUBLE PRECISION,
    vitamin_b12 DOUBLE PRECISION,
    saturated_fat DOUBLE PRECISION,
    trans_fat DOUBLE PRECISION,
    sugar_alcohol DOUBLE PRECISION,
    is_custom BOOLEAN
);

CREATE TABLE exercise_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    met_code VARCHAR(255),
    calories_per_minute DOUBLE PRECISION,
    description VARCHAR(255),
    icon_url VARCHAR(255),
    primary_muscle_group VARCHAR(255),
    secondary_muscle_groups VARCHAR(255),
    equipment VARCHAR(255),
    difficulty VARCHAR(255),
    instructions VARCHAR(2000),
    safety_notes VARCHAR(1000),
    thumbnail_url VARCHAR(255),
    video_url VARCHAR(255),
    animation_url VARCHAR(255),
    ai_eligible BOOLEAN,
    active BOOLEAN
);

CREATE TABLE food_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    food_id BIGINT,
    portion_size DOUBLE PRECISION,
    meal_type VARCHAR(255),
    log_date TIMESTAMP,
    CONSTRAINT fk_food_logs_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_food_logs_food_item FOREIGN KEY (food_id) REFERENCES food_items(id)
);

CREATE TABLE exercise_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    exercise_item_id BIGINT,
    duration_minutes INTEGER,
    calories_burned DOUBLE PRECISION,
    log_date TIMESTAMP,
    source VARCHAR(255),
    external_id VARCHAR(255),
    extra_data VARCHAR(255),
    CONSTRAINT fk_exercise_logs_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_exercise_logs_exercise_item FOREIGN KEY (exercise_item_id) REFERENCES exercise_items(id),
    CONSTRAINT uk_exercise_logs_user_source_external UNIQUE (user_id, source, external_id)
);

CREATE INDEX idx_exercise_logs_user_source ON exercise_logs (user_id, source);

CREATE TABLE goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    target_weight DOUBLE PRECISION,
    daily_calorie_goal INTEGER,
    daily_protein_goal DOUBLE PRECISION,
    daily_fat_goal DOUBLE PRECISION,
    daily_carb_goal DOUBLE PRECISION,
    weekly_weight_change_target_kg DOUBLE PRECISION,
    goal_type VARCHAR(255),
    activity_level VARCHAR(255),
    created_at TIMESTAMP,
    CONSTRAINT fk_goals_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE progress_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    log_date TIMESTAMP,
    weight DOUBLE PRECISION,
    calorie_intake INTEGER,
    protein_intake DOUBLE PRECISION,
    fat_intake DOUBLE PRECISION,
    carb_intake DOUBLE PRECISION,
    note VARCHAR(255),
    CONSTRAINT fk_progress_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    message VARCHAR(255),
    type VARCHAR(255),
    is_read BOOLEAN,
    created_at TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE device_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    steps INTEGER,
    heart_rate INTEGER,
    sleep_hours DOUBLE PRECISION,
    recorded_at TIMESTAMP,
    source VARCHAR(255),
    CONSTRAINT fk_device_data_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    plan_type VARCHAR(255),
    start_date DATE,
    end_date DATE,
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) UNIQUE,
    discount_percent DOUBLE PRECISION,
    max_usage_count INTEGER,
    used_count INTEGER,
    expiration_date DATE
);

CREATE TABLE applied_promos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    promo_code_id BIGINT,
    applied_at TIMESTAMP,
    CONSTRAINT fk_applied_promos_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_applied_promos_promo_code FOREIGN KEY (promo_code_id) REFERENCES promo_codes(id)
);

CREATE TABLE user_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    food_item_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_favorites_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_favorites_food_item FOREIGN KEY (food_item_id) REFERENCES food_items(id),
    CONSTRAINT uq_user_food_item UNIQUE (user_id, food_item_id)
);
