ALTER TABLE admin_action_audits DROP CONSTRAINT IF EXISTS chk_admin_action_audits_action_type;
ALTER TABLE admin_action_audits ADD CONSTRAINT chk_admin_action_audits_action_type CHECK (action_type IN (
'SUBSCRIPTION_UPDATE','AI_QUOTA_RESET','AI_QUOTA_ADDON_GRANT','AI_QUOTA_REFUND','AI_REQUEST_INSPECT',
'AI_OPERATIONS_POLICY_UPDATE','AI_OPERATIONS_DEPLOYMENT_ROLLBACK','AI_CREDIT_PRICING_UPDATE',
'SUBSCRIPTION_FEATURE_UPDATE','SUBSCRIPTION_ENTITLEMENT_MATRIX_APPLY','RETENTION_POLICY_UPDATE',
'RECIPE_CREATE','RECIPE_REVIEW_UPDATE','USER_STATUS_UPDATE','USER_SUPPORT_NOTE_CREATE','USER_SESSION_REVOKE',
'PRODUCT_QUALITY_AI_SETTINGS_UPDATE','NOTIFICATION_CAMPAIGN_CREATE','NOTIFICATION_CAMPAIGN_UPDATE',
'NOTIFICATION_CAMPAIGN_SCHEDULE','NOTIFICATION_CAMPAIGN_CANCEL','PROMO_CREATE','PROMO_UPDATE','PROMO_ACTIVATE',
'PROMO_DEACTIVATE','PROMO_RECONCILE','PROMO_REDEMPTION_RECORD','ADMIN_ROLE_UPDATE','ADMIN_STATUS_UPDATE',
'ADMIN_INVITATION_CREATE','ADMIN_INVITATION_RESEND','ADMIN_INVITATION_REVOKE','ADMIN_INVITATION_ACCEPT',
'ADMIN_MFA_STATUS_UPDATE','ADMIN_MFA_ENROLL','ADMIN_MFA_DISABLE','ADMIN_MFA_REAUTHENTICATE',
'ADMIN_MFA_FAILURE','ADMIN_MFA_RECOVERY_CODE_USE','ADMIN_SESSION_CREATE','RECOVERY_OWNER_LOGIN',
'ADMIN_SESSION_REVOKE','ADMIN_OTHER_SESSIONS_REVOKE','ADMIN_APPROVAL_REQUEST','ADMIN_APPROVAL_APPROVE',
'ADMIN_APPROVAL_REJECT','ADMIN_APPROVAL_EXECUTION_FAILED','GDPR_REQUEST_UPDATE','PRODUCTION_VERIFICATION_RECORD',
'CATALOG_EXERCISE_CREATE','CATALOG_EXERCISE_UPDATE','CATALOG_EXERCISE_REVIEW','CATALOG_REVIEW_ASSIGNMENT',
'RUNTIME_POLICY_UPDATE','RUNTIME_POLICY_ROLLBACK','RUNTIME_RECORD_CREATE','RUNTIME_JOB_RETRY','FASTING_OPERATIONS_CONFIG_UPDATE'
));

ALTER TABLE admin_action_audits DROP CONSTRAINT IF EXISTS chk_admin_action_audits_target_type;
ALTER TABLE admin_action_audits ADD CONSTRAINT chk_admin_action_audits_target_type CHECK (target_type IN (
'USER_SUBSCRIPTION','AI_REQUEST','AI_OPERATIONS_POLICY','AI_CREDIT_PRICING','SUBSCRIPTION_FEATURE','RETENTION_POLICY',
'RECIPE','USER_ACCOUNT','PRODUCT_QUALITY_AI_SETTINGS','NOTIFICATION_CAMPAIGN','PROMOTION','ADMIN_ACCOUNT',
'ADMIN_INVITATION','ADMIN_SESSION','EXERCISE_ITEM','CATALOG_REVIEW_ITEM','RUNTIME_OPERATIONS','ADMIN_APPROVAL',
'GDPR_REQUEST','PRODUCTION_VERIFICATION','FASTING_GOVERNANCE'
));
