CREATE TABLE IF NOT EXISTS exercise_item_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_item_id BIGINT NOT NULL REFERENCES exercise_items(id),
    alias VARCHAR(160) NOT NULL,
    normalized_alias VARCHAR(160) NOT NULL,
    language VARCHAR(12) NOT NULL DEFAULT 'und',
    alias_type VARCHAR(24) NOT NULL DEFAULT 'SYNONYM',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_exercise_alias_language UNIQUE (normalized_alias, language)
);
CREATE INDEX IF NOT EXISTS idx_exercise_alias_lookup ON exercise_item_aliases(normalized_alias, active);

CREATE TABLE IF NOT EXISTS unmatched_ai_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalized_name VARCHAR(160) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    language VARCHAR(12),
    equipment VARCHAR(120),
    target_muscle_group VARCHAR(120),
    occurrence_count BIGINT NOT NULL DEFAULT 1,
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
    resolved_exercise_item_id BIGINT REFERENCES exercise_items(id),
    CONSTRAINT uk_unmatched_ai_exercise_status UNIQUE (normalized_name, status)
);
CREATE INDEX IF NOT EXISTS idx_unmatched_ai_exercise_queue
    ON unmatched_ai_exercises(status, occurrence_count DESC, last_seen_at DESC);
