INSERT INTO exercise_items
(name, met_code, calories_per_minute, description, primary_muscle_group, secondary_muscle_groups,
 equipment, difficulty, instructions, safety_notes, default_measurement_type, allowed_measurement_types,
 ai_eligible, active, technique_review_status, source_name, source_url, license_name, source_last_refreshed_at)
SELECT v.name, v.code, v.calories, v.description, v.primary_muscle, v.secondary_muscles,
       v.equipment, v.difficulty, v.instructions, v.safety, v.default_measurement, v.allowed_measurements,
       TRUE, TRUE, 'APPROVED', 'GRUN curated exercise catalog', 'https://gruncalorietracker.com/exercise-methodology',
       'GRUN editorial', CURRENT_TIMESTAMP
FROM (VALUES
 ('Goblet Squat','GOBLET_SQUAT',6.0,'Dumbbell or kettlebell front-loaded squat.','Quadriceps','Glutes, Hamstrings, Core','Dumbbell or Kettlebell','BEGINNER','Hold the weight at chest height, brace, squat with knees tracking over toes, then stand.','Use a load that allows a neutral spine.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Barbell Back Squat','BARBELL_BACK_SQUAT',7.0,'Barbell squat performed with the bar across the upper back.','Quadriceps','Glutes, Hamstrings, Core','Barbell','INTERMEDIATE','Brace before descending, keep the whole foot grounded, and drive up under control.','Use safety pins or a spotter and stop if spinal position cannot be maintained.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Bulgarian Split Squat','BULGARIAN_SPLIT_SQUAT',6.0,'Rear-foot elevated unilateral squat.','Quadriceps','Glutes, Hamstrings, Core','Bench, Dumbbells optional','INTERMEDIATE','Set the rear foot on a bench, descend through the front hip and knee, then drive through the front foot.','Start bodyweight and keep the front knee tracking steadily.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Romanian Deadlift','ROMANIAN_DEADLIFT',6.5,'Hip hinge emphasizing hamstrings and glutes.','Hamstrings','Glutes, Back, Core','Barbell or Dumbbells','INTERMEDIATE','Push hips back with soft knees, keep the load close, then extend the hips to stand.','Reduce range if the back rounds.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Conventional Deadlift','CONVENTIONAL_DEADLIFT',7.5,'Barbell pull from the floor.','Glutes','Hamstrings, Back, Core, Quadriceps','Barbell','ADVANCED','Brace with the bar over mid-foot, push the floor away, and stand with the bar close.','Technique review and conservative loading are recommended.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Hip Thrust','HIP_THRUST',6.0,'Loaded hip extension with upper back supported.','Glutes','Hamstrings, Core','Bench, Barbell or Dumbbell','INTERMEDIATE','Brace against the bench, drive through the feet, and finish with controlled hip extension.','Avoid excessive lower-back extension.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Glute Bridge','GLUTE_BRIDGE',4.5,'Floor-based hip extension.','Glutes','Hamstrings, Core','Mat','BEGINNER','Press through the feet and lift the hips while keeping ribs controlled.','Stop if the lower back becomes painful.','SETS_REPS','SETS_REPS,REPS,DURATION'),
 ('Step-Up','STEP_UP',5.5,'Single-leg step onto a stable platform.','Quadriceps','Glutes, Hamstrings, Calves','Box or Bench','BEGINNER','Place the full foot on the platform and stand using the lead leg.','Use a stable platform and control the descent.','SETS_REPS','SETS_REPS,REPS,WEIGHT_REPS'),
 ('Leg Extension','LEG_EXTENSION',4.5,'Machine knee-extension exercise.','Quadriceps','None','Leg Extension Machine','BEGINNER','Align the machine pivot with the knee and extend under control.','Avoid forceful lockout and painful ranges.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Leg Curl','LEG_CURL',4.5,'Machine knee-flexion exercise.','Hamstrings','Calves','Leg Curl Machine','BEGINNER','Keep hips supported and curl the pad smoothly.','Use a controlled range without lifting the hips.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Standing Calf Raise','STANDING_CALF_RAISE',4.0,'Standing ankle plantar-flexion exercise.','Calves','Feet, Ankles','Machine or Dumbbells','BEGINNER','Rise through the balls of the feet, pause, then lower under control.','Use support for balance and avoid bouncing.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS,REPS'),
 ('Dumbbell Bench Press','DUMBBELL_BENCH_PRESS',5.5,'Horizontal chest press using dumbbells.','Chest','Triceps, Shoulders','Dumbbells, Bench','BEGINNER','Set shoulders against the bench, lower dumbbells with control, and press upward.','Keep wrists stacked and use a safe setup.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Incline Dumbbell Press','INCLINE_DUMBBELL_PRESS',5.5,'Incline chest press using dumbbells.','Chest','Shoulders, Triceps','Dumbbells, Incline Bench','INTERMEDIATE','Set a moderate incline, lower with forearms vertical, and press smoothly.','Avoid an excessive bench angle or shoulder discomfort.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Cable Chest Fly','CABLE_CHEST_FLY',4.5,'Cable chest adduction exercise.','Chest','Shoulders','Cable Machine','INTERMEDIATE','Keep a soft elbow bend and bring the hands together in a controlled arc.','Do not overstretch the shoulders.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Incline Push-Up','INCLINE_PUSH_UP',4.0,'Push-up with hands elevated.','Chest','Triceps, Shoulders, Core','Bench or Box','BEGINNER','Maintain a straight body line, lower the chest to the support, and press away.','Choose an elevation that preserves form.','SETS_REPS','SETS_REPS,REPS'),
 ('Diamond Push-Up','DIAMOND_PUSH_UP',6.0,'Close-hand push-up variation.','Triceps','Chest, Shoulders, Core','None','INTERMEDIATE','Keep hands close, body braced, and elbows controlled while lowering.','Use an incline if wrists or elbows are uncomfortable.','SETS_REPS','SETS_REPS,REPS'),
 ('Assisted Pull-Up','ASSISTED_PULL_UP',5.5,'Pull-up using band or machine assistance.','Back','Biceps, Shoulders, Core','Assisted Pull-Up Machine or Band','BEGINNER','Start with active shoulders, pull without swinging, and lower slowly.','Use enough assistance to maintain control.','SETS_REPS','SETS_REPS,REPS'),
 ('Chin-Up','CHIN_UP',7.0,'Supinated-grip vertical pull.','Back','Biceps, Core','Pull-Up Bar','INTERMEDIATE','Pull from an active hang and lower under control.','Scale with assistance if shoulder position or control is lost.','SETS_REPS','SETS_REPS,REPS'),
 ('Barbell Row','BARBELL_ROW',6.0,'Bent-over horizontal barbell pull.','Back','Biceps, Rear Shoulders, Core','Barbell','INTERMEDIATE','Hinge and brace, pull the bar toward the torso, then lower without changing posture.','Reduce load if the lower back cannot remain stable.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('One-Arm Dumbbell Row','ONE_ARM_DUMBBELL_ROW',5.0,'Supported unilateral dumbbell row.','Back','Biceps, Rear Shoulders','Dumbbell, Bench','BEGINNER','Support the torso, pull the dumbbell toward the hip, and lower fully.','Avoid rotating the trunk excessively.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Seated Cable Row','SEATED_CABLE_ROW',5.0,'Cable horizontal pulling exercise.','Back','Biceps, Rear Shoulders','Cable Machine','BEGINNER','Sit tall, pull toward the ribs, and return with control.','Avoid leaning back to create momentum.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Face Pull','FACE_PULL',4.0,'Cable pull toward the face for upper-back control.','Rear Shoulders','Upper Back, Rotator Cuff','Cable Machine','BEGINNER','Pull the rope toward eye level while rotating the hands apart.','Use a light load and avoid neck tension.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Barbell Overhead Press','BARBELL_OVERHEAD_PRESS',6.0,'Standing overhead barbell press.','Shoulders','Triceps, Core','Barbell','INTERMEDIATE','Brace, press the bar overhead in a close path, and lower under control.','Avoid excessive back extension.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Arnold Press','ARNOLD_PRESS',5.0,'Rotating dumbbell shoulder press.','Shoulders','Triceps','Dumbbells','INTERMEDIATE','Rotate and press smoothly without forcing the shoulder range.','Use light weight if rotation causes discomfort.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Dumbbell Lateral Raise','DUMBBELL_LATERAL_RAISE',4.0,'Dumbbell shoulder abduction exercise.','Shoulders','Upper Back','Dumbbells','BEGINNER','Raise with soft elbows to a comfortable height, then lower slowly.','Avoid swinging or shrugging.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Rear Delt Fly','REAR_DELT_FLY',4.0,'Horizontal shoulder abduction for rear deltoids.','Rear Shoulders','Upper Back','Dumbbells or Machine','BEGINNER','Keep the torso stable and open the arms under control.','Use a light load and avoid neck tension.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Hammer Curl','HAMMER_CURL',4.0,'Neutral-grip dumbbell curl.','Biceps','Forearms','Dumbbells','BEGINNER','Keep elbows close and curl without swinging.','Reduce load if the torso moves.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Triceps Pushdown','TRICEPS_PUSHDOWN',4.0,'Cable elbow-extension exercise.','Triceps','Forearms','Cable Machine','BEGINNER','Keep elbows fixed and extend the cable under control.','Avoid using shoulder or torso momentum.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Dead Bug','DEAD_BUG',3.5,'Supine contralateral core stability exercise.','Core','Hip Flexors','Mat','BEGINNER','Brace the trunk and slowly extend opposite arm and leg without arching.','Shorten the range if the lower back lifts.','REPS','REPS,SETS_REPS,DURATION'),
 ('Bird Dog','BIRD_DOG',3.5,'Quadruped contralateral stability exercise.','Core','Glutes, Back, Shoulders','Mat','BEGINNER','Extend opposite arm and leg while keeping hips and ribs square.','Use a smaller range if balance is difficult.','REPS','REPS,SETS_REPS,DURATION'),
 ('Side Plank','SIDE_PLANK',4.0,'Lateral trunk isometric hold.','Core','Shoulders, Glutes','Mat','INTERMEDIATE','Stack the body and hold the hips lifted with steady breathing.','Use a bent-knee variation if shoulder or trunk control is limited.','DURATION','DURATION'),
 ('Bicycle Crunch','BICYCLE_CRUNCH',5.0,'Alternating trunk flexion and rotation.','Core','Hip Flexors','Mat','BEGINNER','Rotate the ribs toward the opposite knee while extending the other leg slowly.','Avoid pulling the neck.','REPS','REPS,SETS_REPS,DURATION'),
 ('Hanging Knee Raise','HANGING_KNEE_RAISE',6.0,'Hanging hip-flexion and core exercise.','Core','Hip Flexors, Grip','Pull-Up Bar','INTERMEDIATE','Start from a controlled hang and raise the knees without swinging.','Use captain chair support if grip or shoulder tolerance is limited.','SETS_REPS','SETS_REPS,REPS'),
 ('Pallof Press','PALLOF_PRESS',3.5,'Anti-rotation cable or band core exercise.','Core','Shoulders, Glutes','Cable or Resistance Band','BEGINNER','Stand stable and press the handle away without rotating.','Choose resistance that allows square hips and ribs.','SETS_REPS','SETS_REPS,REPS,DURATION'),
 ('Farmer Carry','FARMER_CARRY',6.0,'Loaded carry with weights at the sides.','Full Body','Grip, Core, Shoulders, Legs','Dumbbells or Kettlebells','BEGINNER','Stand tall and walk with controlled short steps while holding the loads steady.','Use a clear path and manageable loads.','DISTANCE','DISTANCE,DURATION,MIXED'),
 ('Box Jump','BOX_JUMP',9.0,'Explosive jump onto a stable platform.','Lower Body','Glutes, Calves, Core','Plyometric Box','ADVANCED','Jump and land softly with the whole foot on the box, then step down.','Use a low stable box and stop when landings become noisy or unstable.','SETS_REPS','SETS_REPS,REPS'),
 ('Battle Rope','BATTLE_ROPE',10.0,'Rope-based upper-body conditioning intervals.','Full Body','Shoulders, Core, Legs','Battle Ropes','INTERMEDIATE','Keep a stable stance and create controlled rope waves.','Keep intervals short enough to preserve posture.','DURATION','DURATION'),
 ('Medicine Ball Slam','MEDICINE_BALL_SLAM',8.0,'Full-body medicine-ball power drill.','Full Body','Core, Shoulders, Legs','Medicine Ball','INTERMEDIATE','Reach tall, brace, slam the ball, and retrieve it with a squat or hinge.','Use a non-bouncing ball and clear space.','SETS_REPS','SETS_REPS,REPS,DURATION'),
 ('Turkish Get-Up','TURKISH_GET_UP',6.0,'Multi-step floor-to-standing kettlebell movement.','Full Body','Shoulders, Core, Hips','Kettlebell','ADVANCED','Move through each supported position slowly while keeping the load stacked.','Learn unloaded first and use professional instruction for technique.','WEIGHT_REPS','WEIGHT_REPS,SETS_REPS'),
 ('Jumping Jack','JUMPING_JACK',8.0,'Rhythmic full-body cardio movement.','Full Body','Calves, Shoulders, Hips','None','BEGINNER','Land softly and coordinate arm and leg motion at a sustainable pace.','Use step jacks for lower impact.','DURATION','DURATION,REPS,SETS_REPS'),
 ('High Knees','HIGH_KNEES',9.0,'Running-in-place conditioning drill.','Lower Body','Core, Calves, Hip Flexors','None','INTERMEDIATE','Stay tall and alternate quick knee drives with light landings.','Reduce speed or march if impact is uncomfortable.','DURATION','DURATION,REPS'),
 ('Treadmill Running','TREADMILL_RUNNING',9.5,'Running performed on a treadmill.','Lower Body','Glutes, Hamstrings, Calves, Core','Treadmill','BEGINNER','Use a controlled pace, stay centered, and increase speed gradually.','Attach the safety clip and avoid abrupt speed changes.','DISTANCE','DURATION,DISTANCE,MIXED'),
 ('Stationary Cycling','STATIONARY_CYCLING',7.0,'Indoor stationary bicycle cardio.','Lower Body','Quadriceps, Glutes, Calves','Stationary Bike','BEGINNER','Set a comfortable saddle height and pedal with steady cadence.','Reduce resistance if knees or hips hurt.','DURATION','DURATION,DISTANCE,MIXED'),
 ('Foam Rolling','FOAM_ROLLING',2.5,'Self-myofascial recovery session.','Full Body','Mobility','Foam Roller','BEGINNER','Roll slowly over muscle tissue and pause gently on sensitive areas.','Avoid rolling directly over joints, acute injuries, or severe pain.','DURATION','DURATION'),
 ('Hip Mobility','HIP_MOBILITY',2.5,'Controlled hip mobility routine.','Hips','Glutes, Adductors, Core','Mat','BEGINNER','Move slowly through comfortable hip ranges with steady breathing.','Do not force pinching or painful positions.','DURATION','DURATION'),
 ('Shoulder Mobility','SHOULDER_MOBILITY',2.5,'Controlled shoulder mobility routine.','Shoulders','Upper Back, Chest','Band optional','BEGINNER','Use slow pain-free circles and controlled reach patterns.','Avoid forced overhead range or sharp pain.','DURATION','DURATION'),
 ('Padel','PADEL_GENERAL',6.5,'Padel match or practice session.','Full Body','Legs, Core, Shoulders','Padel Racket','BEGINNER','Use balanced footwork and controlled strokes throughout play.','Warm up shoulders, knees, and ankles before fast rallies.','DURATION','DURATION')
) AS v(name,code,calories,description,primary_muscle,secondary_muscles,equipment,difficulty,instructions,safety,default_measurement,allowed_measurements)
WHERE NOT EXISTS (SELECT 1 FROM exercise_items e WHERE e.met_code = v.code);

WITH aliases(code, alias, normalized_alias, language, alias_type) AS (VALUES
 ('PUSH_UP','Şınav','sinav','tr','LOCALIZED'), ('PULL_UP','Barfiks','barfiks','tr','LOCALIZED'),
 ('BODYWEIGHT_SQUAT','Çömelme','comelme','tr','LOCALIZED'), ('BENCH_PRESS','Göğüs presi','gogus presi','tr','LOCALIZED'),
 ('ROMANIAN_DEADLIFT','RDL','rdl','und','ABBREVIATION'), ('ROMANIAN_DEADLIFT','Dumbbell RDL','dumbbell rdl','en','VARIATION'),
 ('BULGARIAN_SPLIT_SQUAT','Rear Foot Elevated Split Squat','rear foot elevated split squat','en','SYNONYM'),
 ('ONE_ARM_DUMBBELL_ROW','One Arm Row','one arm row','en','SYNONYM'),
 ('LAT_PULLDOWN','Cable Pulldown','cable pulldown','en','SYNONYM'),
 ('TRICEPS_PUSHDOWN','Cable Pushdown','cable pushdown','en','SYNONYM'),
 ('STATIONARY_CYCLING','Spinning','spinning','und','SYNONYM'),
 ('TREADMILL_RUNNING','Koşu Bandı','kosu bandi','tr','LOCALIZED'),
 ('DUMBBELL_SHOULDER_PRESS','Omuz Presi','omuz presi','tr','LOCALIZED'),
 ('SIT_UP','Mekik','mekik','tr','LOCALIZED'), ('JUMP_ROPE','İp Atlama','ip atlama','tr','LOCALIZED')
)
INSERT INTO exercise_item_aliases(exercise_item_id, alias, normalized_alias, language, alias_type, active)
SELECT e.id, a.alias, a.normalized_alias, a.language, a.alias_type, TRUE
FROM aliases a JOIN exercise_items e ON e.met_code = a.code
ON CONFLICT (normalized_alias, language) DO NOTHING;
