ALTER TABLE goals ADD COLUMN IF NOT EXISTS calculation_mode VARCHAR(32) NOT NULL DEFAULT 'AUTO';
ALTER TABLE goals ADD COLUMN IF NOT EXISTS controlled_strategy VARCHAR(32);
ALTER TABLE goals ADD COLUMN IF NOT EXISTS locked_macros VARCHAR(128);
ALTER TABLE goals ADD COLUMN IF NOT EXISTS macro_calculated_calories INTEGER;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS automatic_reference_calories INTEGER;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS automatic_reference_protein DOUBLE PRECISION;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS automatic_reference_carbs DOUBLE PRECISION;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS automatic_reference_fat DOUBLE PRECISION;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS effective_from TIMESTAMP;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS effective_until TIMESTAMP;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS effective_local_date DATE;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS effective_time_zone VARCHAR(100);
ALTER TABLE goals ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

UPDATE goals SET
    effective_from = COALESCE(effective_from, created_at, CURRENT_TIMESTAMP),
    effective_local_date = COALESCE(effective_local_date, CAST(COALESCE(created_at, CURRENT_TIMESTAMP) AS DATE)),
    effective_time_zone = COALESCE(effective_time_zone, 'UTC'),
    macro_calculated_calories = COALESCE(macro_calculated_calories,
        ROUND(COALESCE(daily_protein_goal, 0) * 4 + COALESCE(daily_carb_goal, 0) * 4 + COALESCE(daily_fat_goal, 0) * 9));

ALTER TABLE goals ALTER COLUMN effective_from SET NOT NULL;
ALTER TABLE goals ALTER COLUMN effective_local_date SET NOT NULL;
ALTER TABLE goals ALTER COLUMN effective_time_zone SET NOT NULL;
ALTER TABLE goals ADD CONSTRAINT chk_goals_calculation_mode CHECK (calculation_mode IN ('AUTO','CONTROLLED','MANUAL'));
ALTER TABLE goals ADD CONSTRAINT chk_goals_controlled_strategy CHECK (controlled_strategy IS NULL OR controlled_strategy IN ('CALORIES_FIXED','PRIORITY_MACRO_FIXED'));
ALTER TABLE goals ADD CONSTRAINT chk_goals_effective_range CHECK (effective_until IS NULL OR effective_until >= effective_from);

WITH ranked_active AS (
    SELECT id, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY effective_from DESC, id DESC) AS row_number
    FROM goals
    WHERE effective_until IS NULL
)
UPDATE goals
SET effective_until = CASE WHEN effective_from > CURRENT_TIMESTAMP THEN effective_from ELSE CURRENT_TIMESTAMP END
WHERE id IN (SELECT id FROM ranked_active WHERE row_number > 1);

CREATE UNIQUE INDEX uk_goals_one_active_per_user ON goals (user_id) WHERE effective_until IS NULL;
CREATE INDEX idx_goals_user_effective_from ON goals (user_id, effective_from DESC);

CREATE TABLE goal_target_acknowledgements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    warning_codes VARCHAR(1000) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    locale VARCHAR(16) NOT NULL,
    acknowledged_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_goal_target_ack_goal FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE,
    CONSTRAINT fk_goal_target_ack_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_goal_target_ack_goal ON goal_target_acknowledgements (goal_id);
