CREATE TABLE product_nutrition_ocr_shadow_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_case_id BIGINT NOT NULL,
    requester_user_id BIGINT NOT NULL,
    correlation_id VARCHAR(128),
    parser_version VARCHAR(80) NOT NULL,
    model VARCHAR(120),
    fallback_invoked BOOLEAN NOT NULL,
    v3_fields_json TEXT NOT NULL,
    v4_fields_json TEXT NOT NULL,
    gemini_fields_json TEXT NOT NULL,
    user_fields_json TEXT NOT NULL,
    v3_exact_match_rate DOUBLE PRECISION NOT NULL,
    v4_exact_match_rate DOUBLE PRECISION NOT NULL,
    gemini_exact_match_rate DOUBLE PRECISION NOT NULL,
    v3_basis_exact BOOLEAN NOT NULL,
    v4_basis_exact BOOLEAN NOT NULL,
    gemini_basis_exact BOOLEAN NOT NULL,
    latency_ms BIGINT NOT NULL,
    estimated_cost_usd DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_product_nutrition_ocr_shadow_case_created
    ON product_nutrition_ocr_shadow_runs(review_case_id, created_at);
