CREATE TABLE IF NOT EXISTS health_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    connected_at TIMESTAMP,
    disconnected_at TIMESTAMP,
    last_sync_at TIMESTAMP,
    provider_user_id VARCHAR(255),
    device_model VARCHAR(255),
    app_version VARCHAR(255),
    CONSTRAINT fk_health_connections_user
        FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT uq_health_connections_user_provider
        UNIQUE (user_id, provider),
    CONSTRAINT chk_health_connections_provider
        CHECK (provider IN ('APPLE_HEALTH', 'GOOGLE_FIT', 'HEALTH_CONNECT')),
    CONSTRAINT chk_health_connections_status
        CHECK (status IN ('CONNECTED', 'DISCONNECTED', 'REVOKED'))
);

ALTER TABLE device_data
    ADD COLUMN IF NOT EXISTS provider VARCHAR(32);

ALTER TABLE device_data
    ADD COLUMN IF NOT EXISTS external_id VARCHAR(255);

ALTER TABLE device_data
    ADD COLUMN IF NOT EXISTS calories_burned DOUBLE PRECISION;

ALTER TABLE device_data
    ADD COLUMN IF NOT EXISTS distance_meters DOUBLE PRECISION;

ALTER TABLE device_data
    DROP CONSTRAINT IF EXISTS chk_device_data_health_provider;

ALTER TABLE device_data
    ADD CONSTRAINT chk_device_data_health_provider
        CHECK (provider IS NULL OR provider IN ('APPLE_HEALTH', 'GOOGLE_FIT', 'HEALTH_CONNECT'));

CREATE INDEX IF NOT EXISTS idx_health_connections_user_status
    ON health_connections (user_id, status);

CREATE INDEX IF NOT EXISTS idx_device_data_user_provider_recorded_at
    ON device_data (user_id, provider, recorded_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_device_data_user_provider_external
    ON device_data (user_id, provider, external_id)
    WHERE provider IS NOT NULL AND external_id IS NOT NULL;
