CREATE TABLE IF NOT EXISTS meal_reminder_dry_run_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_ref VARCHAR(64) NOT NULL,
    policy_version VARCHAR(80) NOT NULL,
    evaluated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    local_date DATE,
    candidate VARCHAR(30),
    slot VARCHAR(20),
    should_send BOOLEAN NOT NULL,
    reason VARCHAR(40) NOT NULL,
    kcal_reason VARCHAR(40),
    message_variant VARCHAR(40)
);

CREATE INDEX IF NOT EXISTS idx_meal_reminder_dry_run_expires
    ON meal_reminder_dry_run_decisions(expires_at);

CREATE INDEX IF NOT EXISTS idx_meal_reminder_dry_run_subject_evaluated
    ON meal_reminder_dry_run_decisions(subject_ref, evaluated_at DESC);
