CREATE TABLE meal_reminder_schedules (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    next_evaluation_at TIMESTAMP WITH TIME ZONE NOT NULL,
    lease_owner VARCHAR(80),
    lease_until TIMESTAMP WITH TIME ZONE,
    last_duration_ms BIGINT,
    last_error_code VARCHAR(80),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_meal_reminder_schedule_due
    ON meal_reminder_schedules(next_evaluation_at, user_id);

CREATE TABLE meal_reminder_daily_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    local_date DATE NOT NULL,
    reserved_count INTEGER NOT NULL DEFAULT 0 CHECK (reserved_count BETWEEN 0 AND 3),
    catchup_count INTEGER NOT NULL DEFAULT 0 CHECK (catchup_count BETWEEN 0 AND 1),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_meal_reminder_budget_user_day UNIQUE (user_id, local_date)
);

CREATE TABLE meal_reminder_occurrences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    local_date DATE NOT NULL,
    slot VARCHAR(20) NOT NULL,
    candidate VARCHAR(30) NOT NULL,
    message_variant VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    policy_version VARCHAR(80) NOT NULL,
    eligible_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reservation_active BOOLEAN NOT NULL DEFAULT TRUE,
    notification_id BIGINT REFERENCES notifications(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_meal_reminder_occurrence_user_day_slot UNIQUE (user_id, local_date, slot),
    CONSTRAINT chk_meal_reminder_occurrence_expiry CHECK (expires_at > eligible_at)
);

CREATE INDEX idx_meal_reminder_occurrence_user_created
    ON meal_reminder_occurrences(user_id, created_at DESC);

CREATE TABLE meal_reminder_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id BIGINT NOT NULL REFERENCES meal_reminder_occurrences(id) ON DELETE CASCADE,
    notification_id BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    lease_owner VARCHAR(80),
    lease_until TIMESTAMP WITH TIME ZONE,
    dispatch_count INTEGER NOT NULL DEFAULT 0,
    last_error_code VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_meal_reminder_outbox_occurrence UNIQUE (occurrence_id)
);

CREATE INDEX idx_meal_reminder_outbox_due
    ON meal_reminder_outbox(status, available_at, expires_at);

CREATE TABLE meal_reminder_delivery_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_id BIGINT NOT NULL REFERENCES meal_reminder_outbox(id) ON DELETE CASCADE,
    push_token_id BIGINT NOT NULL REFERENCES user_push_tokens(id) ON DELETE CASCADE,
    provider VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE,
    provider_message_id VARCHAR(512),
    error_code VARCHAR(80),
    provider_accepted_at TIMESTAMP WITH TIME ZONE,
    receipt_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_meal_reminder_attempt_outbox_token UNIQUE (outbox_id, push_token_id)
);

CREATE INDEX idx_meal_reminder_attempt_due
    ON meal_reminder_delivery_attempts(status, next_attempt_at);

-- Existing users are seeded once; later users are added by the bounded bootstrap query.
INSERT INTO meal_reminder_schedules(user_id, next_evaluation_at, updated_at)
SELECT id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM users
ON CONFLICT (user_id) DO NOTHING;
