CREATE TABLE meal_reminder_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    policy_version VARCHAR(80) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    mode VARCHAR(20) NOT NULL,
    kcal_enabled BOOLEAN NOT NULL,
    breakfast_time TIME NOT NULL,
    lunch_time TIME NOT NULL,
    dinner_time TIME NOT NULL,
    slot_age_minutes INTEGER NOT NULL CHECK (slot_age_minutes BETWEEN 1 AND 60),
    max_daily INTEGER NOT NULL CHECK (max_daily BETWEEN 0 AND 3),
    max_rolling INTEGER NOT NULL CHECK (max_rolling BETWEEN 0 AND 3),
    max_catchups INTEGER NOT NULL CHECK (max_catchups BETWEEN 0 AND 1),
    minimum_gap_minutes INTEGER NOT NULL CHECK (minimum_gap_minutes >= 180),
    routine_gap_minutes INTEGER NOT NULL CHECK (routine_gap_minutes >= 60),
    quiet_start TIME NOT NULL,
    quiet_end TIME NOT NULL,
    pilot_user_ids VARCHAR(4000) NOT NULL DEFAULT '',
    emergency_stopped BOOLEAN NOT NULL DEFAULT FALSE,
    stop_reason VARCHAR(500),
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_meal_reminder_policy_status CHECK (status IN ('DRAFT','ACTIVE','ARCHIVED')),
    CONSTRAINT chk_meal_reminder_policy_mode CHECK (mode IN ('OFF','DRY_RUN','PILOT','LIVE'))
);

CREATE UNIQUE INDEX uq_meal_reminder_single_active_policy
    ON meal_reminder_policies ((status)) WHERE status = 'ACTIVE';

CREATE TABLE meal_reminder_admin_test_sends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    requested_by VARCHAR(255) NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_meal_reminder_test_send_limit
    ON meal_reminder_admin_test_sends(user_id, requested_at DESC);

INSERT INTO meal_reminder_policies
    (policy_version,status,mode,kcal_enabled,breakfast_time,lunch_time,dinner_time,
     slot_age_minutes,max_daily,max_rolling,max_catchups,minimum_gap_minutes,routine_gap_minutes,
     quiet_start,quiet_end,created_by,updated_by,created_at,updated_at,published_at)
VALUES
    ('meal-reminder-policy-v1','ACTIVE','OFF',TRUE,'08:30','13:00','19:00',60,3,3,1,180,60,
     '22:00','08:00','system','system',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO notification_definitions
    (notification_key,display_name,description,enabled,protected_definition,channel,severity,target_route,
     title_en,message_en,title_tr,message_tr,created_by,updated_by,created_at,updated_at)
VALUES
    ('meal_reminder_breakfast','Breakfast reminder','Managed meal reminder copy.',TRUE,TRUE,'IN_APP_AND_PUSH','INFO','diary','A gentle breakfast reminder','When you are ready, add your breakfast to keep today on track.','Kahvaltı için küçük bir hatırlatma','Hazır olduğunda kahvaltını ekleyerek bugünü birlikte takip edebiliriz.','system','system',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
    ('meal_reminder_lunch','Lunch reminder','Managed meal reminder copy.',TRUE,TRUE,'IN_APP_AND_PUSH','INFO','diary','Time to check in','When you are ready, add your lunch to keep your day up to date.','Küçük bir öğle hatırlatması','Hazır olduğunda öğle öğününü ekleyerek gününü güncel tutabilirsin.','system','system',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
    ('meal_reminder_dinner','Dinner reminder','Managed meal reminder copy.',TRUE,TRUE,'IN_APP_AND_PUSH','INFO','diary','A gentle dinner reminder','When you are ready, add your dinner to complete today.','Akşam için küçük bir hatırlatma','Hazır olduğunda akşam öğününü ekleyerek bugünü tamamlayabilirsin.','system','system',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
    ('meal_reminder_dinner_kcal','Dinner calorie reminder','Managed typed calorie copy.',TRUE,TRUE,'IN_APP_AND_PUSH','INFO','diary','Your day is nearly complete','You have about {remainingKcal} kcal remaining today. Add dinner when you are ready.','Günün tamamlanmak üzere','Bugün yaklaşık {remainingKcal} kcal hakkın kaldı. Hazır olduğunda akşam öğününü ekleyebilirsin.','system','system',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
    ('meal_reminder_daily_catchup','Daily meal catch-up','General reminder used when an earlier meal is missing.',TRUE,TRUE,'IN_APP_AND_PUSH','INFO','diary','A gentle daily check-in','An earlier meal is still missing. When you are ready, update today from your diary.','Günlük küçük bir hatırlatma','Önceki öğünlerinden biri eksik görünüyor. Hazır olduğunda günlüğünden bugünü güncelleyebilirsin.','system','system',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT (notification_key) DO UPDATE SET protected_definition=TRUE;

ALTER TABLE admin_action_audits DROP CONSTRAINT IF EXISTS chk_admin_action_audits_action_type;
ALTER TABLE admin_action_audits ADD CONSTRAINT chk_admin_action_audits_action_type CHECK (action_type IN (
'SUBSCRIPTION_UPDATE','AI_QUOTA_RESET','AI_QUOTA_ADDON_GRANT','AI_QUOTA_REFUND','AI_REQUEST_INSPECT','AI_OPERATIONS_POLICY_UPDATE','AI_OPERATIONS_DEPLOYMENT_ROLLBACK','AI_CREDIT_PRICING_UPDATE','SUBSCRIPTION_FEATURE_UPDATE','SUBSCRIPTION_ENTITLEMENT_MATRIX_APPLY','RETENTION_POLICY_UPDATE','RECIPE_CREATE','RECIPE_REVIEW_UPDATE','USER_STATUS_UPDATE','USER_SUPPORT_NOTE_CREATE','USER_SESSION_REVOKE','PRODUCT_QUALITY_AI_SETTINGS_UPDATE','NOTIFICATION_CAMPAIGN_CREATE','NOTIFICATION_CAMPAIGN_UPDATE','NOTIFICATION_CAMPAIGN_SCHEDULE','NOTIFICATION_CAMPAIGN_CANCEL','NOTIFICATION_DEFINITION_CREATE','NOTIFICATION_DEFINITION_UPDATE','PROMO_CREATE','PROMO_UPDATE','PROMO_ACTIVATE','PROMO_DEACTIVATE','PROMO_RECONCILE','PROMO_REDEMPTION_RECORD','ADMIN_ROLE_UPDATE','ADMIN_STATUS_UPDATE','ADMIN_INVITATION_CREATE','ADMIN_INVITATION_RESEND','ADMIN_INVITATION_REVOKE','ADMIN_INVITATION_ACCEPT','ADMIN_PASSWORD_RESET_REQUEST','ADMIN_PASSWORD_RESET_CONFIRM','ADMIN_MFA_STATUS_UPDATE','ADMIN_MFA_ENROLL','ADMIN_MFA_DISABLE','ADMIN_MFA_REAUTHENTICATE','ADMIN_MFA_FAILURE','ADMIN_MFA_RECOVERY_CODE_USE','ADMIN_SESSION_CREATE','RECOVERY_OWNER_LOGIN','ADMIN_SESSION_REVOKE','ADMIN_OTHER_SESSIONS_REVOKE','ADMIN_APPROVAL_REQUEST','ADMIN_APPROVAL_APPROVE','ADMIN_APPROVAL_REJECT','ADMIN_APPROVAL_EXECUTION_FAILED','GDPR_REQUEST_UPDATE','PRODUCTION_VERIFICATION_RECORD','CATALOG_EXERCISE_CREATE','CATALOG_EXERCISE_UPDATE','CATALOG_EXERCISE_REVIEW','CATALOG_REVIEW_ASSIGNMENT','RUNTIME_POLICY_UPDATE','RUNTIME_POLICY_ROLLBACK','RUNTIME_RECORD_CREATE','RUNTIME_JOB_RETRY','FASTING_OPERATIONS_CONFIG_UPDATE','AI_EXERCISE_RESOLVE','AI_EXERCISE_DISMISS','MEAL_REMINDER_POLICY_DRAFT','MEAL_REMINDER_POLICY_PUBLISH','MEAL_REMINDER_POLICY_ROLLBACK','MEAL_REMINDER_DEFINITION_PUBLISH','MEAL_REMINDER_EMERGENCY_STOP','MEAL_REMINDER_REOPEN','MEAL_REMINDER_TEST_SEND'
));

ALTER TABLE admin_action_audits DROP CONSTRAINT IF EXISTS chk_admin_action_audits_target_type;
ALTER TABLE admin_action_audits ADD CONSTRAINT chk_admin_action_audits_target_type CHECK (target_type IN (
'USER_SUBSCRIPTION','AI_REQUEST','AI_OPERATIONS_POLICY','AI_CREDIT_PRICING','SUBSCRIPTION_FEATURE','RETENTION_POLICY','RECIPE','USER_ACCOUNT','PRODUCT_QUALITY_AI_SETTINGS','NOTIFICATION_CAMPAIGN','NOTIFICATION_DEFINITION','PROMOTION','ADMIN_ACCOUNT','ADMIN_INVITATION','ADMIN_SESSION','EXERCISE_ITEM','CATALOG_REVIEW_ITEM','RUNTIME_OPERATIONS','ADMIN_APPROVAL','GDPR_REQUEST','PRODUCTION_VERIFICATION','FASTING_GOVERNANCE','AI_EXERCISE_RESOLUTION','MEAL_REMINDER_AUTOMATION'
));
