CREATE TABLE meal_reminder_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    occurrence_id BIGINT REFERENCES meal_reminder_occurrences(id) ON DELETE SET NULL,
    notification_id BIGINT REFERENCES notifications(id) ON DELETE SET NULL,
    event_type VARCHAR(30) NOT NULL,
    event_key VARCHAR(180) NOT NULL,
    client_event_id VARCHAR(100),
    source VARCHAR(30),
    related_date DATE,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_meal_reminder_interaction_event_key UNIQUE (event_key),
    CONSTRAINT chk_meal_reminder_interaction_type CHECK (event_type IN ('OPEN','MEAL_LOG_CONVERSION','OPT_OUT'))
);

CREATE INDEX idx_meal_reminder_interaction_user_date_time
    ON meal_reminder_interactions(user_id, related_date, recorded_at DESC);
CREATE INDEX idx_meal_reminder_interaction_type_time
    ON meal_reminder_interactions(event_type, recorded_at DESC);
