CREATE TABLE notification_platform_policy (
    id BIGINT PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    requested_delivery_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    emergency_stopped BOOLEAN NOT NULL DEFAULT TRUE,
    stop_reason VARCHAR(500),
    updated_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO notification_platform_policy (
    id, requested_delivery_enabled, emergency_stopped, stop_reason, updated_by, updated_at
) VALUES (
    1, FALSE, TRUE, 'Initial safe state: activation requires maker-checker approval and deployment gates.',
    'system', CURRENT_TIMESTAMP
) ON CONFLICT (id) DO NOTHING;

CREATE TABLE notification_engagements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    engagement_type VARCHAR(24) NOT NULL,
    source VARCHAR(24) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_notification_engagement UNIQUE (notification_id, user_id, engagement_type),
    CONSTRAINT chk_notification_engagement_type CHECK (engagement_type IN ('OPENED','CLICKED','DISMISSED','CONVERTED')),
    CONSTRAINT chk_notification_engagement_source CHECK (source IN ('IN_APP','PUSH'))
);

CREATE INDEX idx_notification_engagement_created
    ON notification_engagements(created_at DESC);
