ALTER TABLE admin_approval_requests
    DROP CONSTRAINT IF EXISTS chk_admin_approval_action;

ALTER TABLE admin_approval_requests
    ADD CONSTRAINT chk_admin_approval_action CHECK (action_type IN (
        'SUBSCRIPTION_UPDATE',
        'AI_QUOTA_RESET',
        'AI_ADDON_QUOTA_GRANT',
        'ENTITLEMENT_MATRIX_APPLY',
        'PLAN_FEATURE_UPDATE',
        'AI_QUOTA_REFUND',
        'NOTIFICATION_CAMPAIGN_SCHEDULE',
        'RUNTIME_POLICY_UPDATE',
        'SUBSCRIPTION_NOTIFICATION_POLICY_PUBLISH',
        'SUBSCRIPTION_NOTIFICATION_DEFINITION_PUBLISH',
        'MEAL_REMINDER_POLICY_PUBLISH',
        'MEAL_REMINDER_POLICY_ROLLBACK',
        'MEAL_REMINDER_DEFINITION_PUBLISH',
        'MEAL_REMINDER_REOPEN',
        'MEAL_REMINDER_TEST_SEND'
    ));
