CREATE TABLE meal_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_meal_plans_user_status_start
    ON meal_plans(user_id, status, start_date DESC);

CREATE TABLE meal_plan_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_plan_id BIGINT NOT NULL REFERENCES meal_plans(id) ON DELETE CASCADE,
    plan_date DATE NOT NULL,
    meal_type VARCHAR(30) NOT NULL,
    item_type VARCHAR(30) NOT NULL,
    food_item_id BIGINT REFERENCES food_items(id),
    recipe_id BIGINT REFERENCES recipes(id),
    portion_size DOUBLE PRECISION,
    portion_unit VARCHAR(30),
    serving_count DOUBLE PRECISION,
    item_order INTEGER,
    CONSTRAINT chk_meal_plan_items_one_target CHECK (
        (item_type = 'FOOD_ITEM' AND food_item_id IS NOT NULL AND recipe_id IS NULL)
        OR
        (item_type = 'RECIPE' AND recipe_id IS NOT NULL AND food_item_id IS NULL)
    )
);

CREATE INDEX idx_meal_plan_items_plan_date
    ON meal_plan_items(meal_plan_id, plan_date, meal_type);
