CREATE TABLE IF NOT EXISTS exercise_provider_activity_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(32) NOT NULL,
    provider_activity_type VARCHAR(120) NOT NULL,
    normalized_provider_activity_type VARCHAR(120) NOT NULL,
    exercise_item_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_exercise_provider_activity_mappings_item
        FOREIGN KEY (exercise_item_id) REFERENCES exercise_items(id),
    CONSTRAINT uk_exercise_provider_activity_mapping
        UNIQUE (provider, normalized_provider_activity_type)
);

CREATE INDEX IF NOT EXISTS idx_exercise_provider_activity_mapping_provider
    ON exercise_provider_activity_mappings (provider, active);

INSERT INTO exercise_items (name, met_code, calories_per_minute, description, icon_url, primary_muscle_group, secondary_muscle_groups, equipment, difficulty, instructions, safety_notes, thumbnail_url, video_url, animation_url, default_measurement_type, allowed_measurement_types, ai_eligible, active)
SELECT v.name, v.met_code, v.calories_per_minute, v.description, NULL, v.primary_muscle_group, v.secondary_muscle_groups, v.equipment, v.difficulty, v.instructions, v.safety_notes, NULL, NULL, NULL, v.default_measurement_type, v.allowed_measurement_types, TRUE, TRUE
FROM (VALUES
    ('Hiking', 'HIKING_GENERAL', 6.0, 'Outdoor walking on trails or uneven terrain.', 'Lower Body', 'Glutes, Hamstrings, Calves, Core', 'None', 'BEGINNER', 'Keep a steady pace, shorten steps on climbs, and maintain upright posture.', 'Use appropriate footwear and reduce pace on unstable terrain.', 'DISTANCE', 'DURATION,DISTANCE,MIXED'),
    ('Traditional Strength Training', 'TRADITIONAL_STRENGTH_TRAINING', 5.5, 'General gym-based strength training session.', 'Full Body', 'Chest, Back, Legs, Shoulders, Arms', 'Gym Equipment', 'BEGINNER', 'Use controlled reps, full-body bracing, and adequate rest between sets.', 'Start light and stop if joint pain or form breakdown appears.', 'DURATION', 'DURATION,SETS_REPS,WEIGHT_REPS'),
    ('Functional Strength Training', 'FUNCTIONAL_STRENGTH_TRAINING', 6.5, 'Functional full-body resistance training session.', 'Full Body', 'Core, Legs, Shoulders, Back', 'Mixed Equipment', 'INTERMEDIATE', 'Move with control through compound patterns and maintain stable posture.', 'Scale loads and range of motion if form breaks.', 'DURATION', 'DURATION,SETS_REPS,WEIGHT_REPS'),
    ('HIIT Workout', 'HIIT_WORKOUT', 12.0, 'High intensity interval training session.', 'Full Body', 'Legs, Core, Shoulders', 'None', 'INTERMEDIATE', 'Alternate hard work intervals with planned recovery and keep technique controlled.', 'Avoid maximal intervals without warm-up and stop if dizzy or unusually breathless.', 'DURATION', 'DURATION'),
    ('Dance', 'DANCE_GENERAL', 6.0, 'General dance-based cardio activity.', 'Full Body', 'Legs, Core', 'None', 'BEGINNER', 'Move rhythmically at a sustainable intensity and keep breathing steady.', 'Warm up gradually and avoid sudden twisting if joints are irritated.', 'DURATION', 'DURATION'),
    ('Basketball', 'BASKETBALL_GENERAL', 8.0, 'Basketball game or practice session.', 'Full Body', 'Legs, Core, Shoulders', 'Ball', 'INTERMEDIATE', 'Move with controlled changes of direction and maintain soft landings.', 'Warm up ankles and knees before high intensity play.', 'DURATION', 'DURATION'),
    ('Football / Soccer', 'SOCCER_GENERAL', 8.0, 'Football or soccer match or training session.', 'Lower Body', 'Glutes, Hamstrings, Calves, Core', 'Ball', 'INTERMEDIATE', 'Pace runs, cuts, and ball work with controlled deceleration.', 'Warm up hamstrings, hips, and ankles before sprinting.', 'DURATION', 'DURATION,DISTANCE,MIXED'),
    ('Tennis', 'TENNIS_GENERAL', 7.0, 'Tennis match or practice session.', 'Full Body', 'Shoulders, Core, Legs', 'Racket', 'INTERMEDIATE', 'Use balanced footwork and controlled strokes through the session.', 'Warm up shoulders and reduce intensity if elbow or wrist pain appears.', 'DURATION', 'DURATION'),
    ('Badminton', 'BADMINTON_GENERAL', 6.5, 'Badminton match or practice session.', 'Full Body', 'Shoulders, Core, Legs', 'Racket', 'BEGINNER', 'Use quick but controlled steps and keep strokes relaxed.', 'Warm up shoulders and ankles before fast rallies.', 'DURATION', 'DURATION'),
    ('Boxing', 'BOXING_GENERAL', 10.0, 'Boxing bag work, pads, or sparring-style conditioning.', 'Full Body', 'Shoulders, Core, Legs', 'Gloves', 'INTERMEDIATE', 'Keep guard up, rotate through the hips, and work in controlled rounds.', 'Protect wrists and avoid sparring without appropriate supervision.', 'DURATION', 'DURATION,REPS'),
    ('Kickboxing', 'KICKBOXING_GENERAL', 11.0, 'Kickboxing cardio or skill session.', 'Full Body', 'Shoulders, Core, Hips, Legs', 'Gloves', 'INTERMEDIATE', 'Strike with control, reset stance between combinations, and breathe steadily.', 'Warm up hips and avoid high kicks beyond comfortable range.', 'DURATION', 'DURATION,REPS'),
    ('Core Training', 'CORE_TRAINING', 5.0, 'General core-focused training session.', 'Core', 'Hip Flexors, Shoulders', 'None', 'BEGINNER', 'Brace through the trunk and move with controlled tempo.', 'Avoid exercises that trigger lower-back pain.', 'DURATION', 'DURATION,SETS_REPS,REPS'),
    ('Cross Training', 'CROSS_TRAINING', 8.0, 'Mixed cardio and resistance training session.', 'Full Body', 'Legs, Core, Shoulders, Back', 'Mixed Equipment', 'INTERMEDIATE', 'Blend movement types while keeping intensity sustainable.', 'Scale unfamiliar movements and avoid fatigue-driven form breakdown.', 'DURATION', 'DURATION,MIXED'),
    ('Cooldown', 'COOLDOWN', 2.0, 'Low intensity cooldown after training.', 'Full Body', 'Mobility', 'None', 'BEGINNER', 'Lower intensity gradually and breathe slowly.', 'Do not force deep stretches while fatigued.', 'DURATION', 'DURATION')
) AS v(name, met_code, calories_per_minute, description, primary_muscle_group, secondary_muscle_groups, equipment, difficulty, instructions, safety_notes, default_measurement_type, allowed_measurement_types)
WHERE NOT EXISTS (SELECT 1 FROM exercise_items e WHERE e.met_code = v.met_code);

WITH mappings(provider, provider_activity_type, normalized_provider_activity_type, met_code) AS (
    VALUES
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeRunning', 'RUNNING', 'RUNNING_GENERAL'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeWalking', 'WALKING', 'WALKING_GENERAL'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeCycling', 'CYCLING', 'CYCLING_MODERATE'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeSwimming', 'SWIMMING', 'SWIMMING_FREESTYLE'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeRowing', 'ROWING', 'ROWING_MACHINE'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeElliptical', 'ELLIPTICAL', 'ELLIPTICAL_MODERATE'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeStairClimbing', 'STAIR_CLIMBING', 'STAIR_CLIMBER'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeHiking', 'HIKING', 'HIKING_GENERAL'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeTraditionalStrengthTraining', 'TRADITIONAL_STRENGTH_TRAINING', 'TRADITIONAL_STRENGTH_TRAINING'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeFunctionalStrengthTraining', 'FUNCTIONAL_STRENGTH_TRAINING', 'FUNCTIONAL_STRENGTH_TRAINING'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeHighIntensityIntervalTraining', 'HIGH_INTENSITY_INTERVAL_TRAINING', 'HIIT_WORKOUT'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeYoga', 'YOGA', 'YOGA_HATHA'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypePilates', 'PILATES', 'PILATES_GENERAL'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeDance', 'DANCE', 'DANCE_GENERAL'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeBasketball', 'BASKETBALL', 'BASKETBALL_GENERAL'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeSoccer', 'SOCCER', 'SOCCER_GENERAL'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeTennis', 'TENNIS', 'TENNIS_GENERAL'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeBadminton', 'BADMINTON', 'BADMINTON_GENERAL'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeBoxing', 'BOXING', 'BOXING_GENERAL'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeKickboxing', 'KICKBOXING', 'KICKBOXING_GENERAL'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeCoreTraining', 'CORE_TRAINING', 'CORE_TRAINING'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeCrossTraining', 'CROSS_TRAINING', 'CROSS_TRAINING'),
    ('APPLE_HEALTH', 'HKWorkoutActivityTypeCooldown', 'COOLDOWN', 'COOLDOWN'),

    ('GOOGLE_FIT', 'running', 'RUNNING', 'RUNNING_GENERAL'),
    ('GOOGLE_FIT', 'walking', 'WALKING', 'WALKING_GENERAL'),
    ('GOOGLE_FIT', 'biking', 'BIKING', 'CYCLING_MODERATE'),
    ('GOOGLE_FIT', 'cycling', 'CYCLING', 'CYCLING_MODERATE'),
    ('GOOGLE_FIT', 'swimming', 'SWIMMING', 'SWIMMING_FREESTYLE'),
    ('GOOGLE_FIT', 'rowing', 'ROWING', 'ROWING_MACHINE'),
    ('GOOGLE_FIT', 'elliptical', 'ELLIPTICAL', 'ELLIPTICAL_MODERATE'),
    ('GOOGLE_FIT', 'stair_climbing', 'STAIR_CLIMBING', 'STAIR_CLIMBER'),
    ('GOOGLE_FIT', 'hiking', 'HIKING', 'HIKING_GENERAL'),
    ('GOOGLE_FIT', 'strength_training', 'STRENGTH_TRAINING', 'TRADITIONAL_STRENGTH_TRAINING'),
    ('GOOGLE_FIT', 'interval_training', 'INTERVAL_TRAINING', 'HIIT_WORKOUT'),
    ('GOOGLE_FIT', 'yoga', 'YOGA', 'YOGA_HATHA'),
    ('GOOGLE_FIT', 'pilates', 'PILATES', 'PILATES_GENERAL'),
    ('GOOGLE_FIT', 'dancing', 'DANCING', 'DANCE_GENERAL'),
    ('GOOGLE_FIT', 'basketball', 'BASKETBALL', 'BASKETBALL_GENERAL'),
    ('GOOGLE_FIT', 'soccer', 'SOCCER', 'SOCCER_GENERAL'),
    ('GOOGLE_FIT', 'tennis', 'TENNIS', 'TENNIS_GENERAL'),
    ('GOOGLE_FIT', 'badminton', 'BADMINTON', 'BADMINTON_GENERAL'),
    ('GOOGLE_FIT', 'boxing', 'BOXING', 'BOXING_GENERAL'),
    ('GOOGLE_FIT', 'kickboxing', 'KICKBOXING', 'KICKBOXING_GENERAL'),
    ('GOOGLE_FIT', 'crossfit', 'CROSSFIT', 'CROSS_TRAINING'),

    ('HEALTH_CONNECT', 'RUNNING', 'RUNNING', 'RUNNING_GENERAL'),
    ('HEALTH_CONNECT', 'WALKING', 'WALKING', 'WALKING_GENERAL'),
    ('HEALTH_CONNECT', 'BIKING', 'BIKING', 'CYCLING_MODERATE'),
    ('HEALTH_CONNECT', 'SWIMMING_POOL', 'SWIMMING_POOL', 'SWIMMING_FREESTYLE'),
    ('HEALTH_CONNECT', 'SWIMMING_OPEN_WATER', 'SWIMMING_OPEN_WATER', 'SWIMMING_FREESTYLE'),
    ('HEALTH_CONNECT', 'ROWING', 'ROWING', 'ROWING_MACHINE'),
    ('HEALTH_CONNECT', 'ELLIPTICAL', 'ELLIPTICAL', 'ELLIPTICAL_MODERATE'),
    ('HEALTH_CONNECT', 'STAIR_CLIMBING', 'STAIR_CLIMBING', 'STAIR_CLIMBER'),
    ('HEALTH_CONNECT', 'HIKING', 'HIKING', 'HIKING_GENERAL'),
    ('HEALTH_CONNECT', 'STRENGTH_TRAINING', 'STRENGTH_TRAINING', 'TRADITIONAL_STRENGTH_TRAINING'),
    ('HEALTH_CONNECT', 'HIGH_INTENSITY_INTERVAL_TRAINING', 'HIGH_INTENSITY_INTERVAL_TRAINING', 'HIIT_WORKOUT'),
    ('HEALTH_CONNECT', 'YOGA', 'YOGA', 'YOGA_HATHA'),
    ('HEALTH_CONNECT', 'PILATES', 'PILATES', 'PILATES_GENERAL'),
    ('HEALTH_CONNECT', 'DANCING', 'DANCING', 'DANCE_GENERAL'),
    ('HEALTH_CONNECT', 'BASKETBALL', 'BASKETBALL', 'BASKETBALL_GENERAL'),
    ('HEALTH_CONNECT', 'SOCCER', 'SOCCER', 'SOCCER_GENERAL'),
    ('HEALTH_CONNECT', 'TENNIS', 'TENNIS', 'TENNIS_GENERAL'),
    ('HEALTH_CONNECT', 'BADMINTON', 'BADMINTON', 'BADMINTON_GENERAL'),
    ('HEALTH_CONNECT', 'BOXING', 'BOXING', 'BOXING_GENERAL'),
    ('HEALTH_CONNECT', 'KICKBOXING', 'KICKBOXING', 'KICKBOXING_GENERAL'),
    ('HEALTH_CONNECT', 'CORE_TRAINING', 'CORE_TRAINING', 'CORE_TRAINING'),
    ('HEALTH_CONNECT', 'CROSS_TRAINING', 'CROSS_TRAINING', 'CROSS_TRAINING')
)
INSERT INTO exercise_provider_activity_mappings (provider, provider_activity_type, normalized_provider_activity_type, exercise_item_id, active)
SELECT m.provider, m.provider_activity_type, m.normalized_provider_activity_type, e.id, TRUE
FROM mappings m
JOIN exercise_items e ON e.met_code = m.met_code
WHERE NOT EXISTS (
    SELECT 1
    FROM exercise_provider_activity_mappings existing
    WHERE existing.provider = m.provider
      AND existing.normalized_provider_activity_type = m.normalized_provider_activity_type
);
